Joystream/pioneer

- .github/workflows/gh-pages.yml
- packages/ui/src/pages/Profile/Profile.tsx
- packages/ui/src/providers/Providers.tsx
- packages/ui/src/types.d.ts
- packages/ui/webpack.config.js
Closes #9 
Hopefully no conflicts with the other branch 🤞.
I've tried to use `<BrowserRouter>` but without redirects on custom `404.html` it is not possible. I've reverted to `<HashRouter>` as it is better suites gh-pages.
> Deploy project to gh pages

- packages/ui/src/components/page/Navigation.tsx
- packages/ui/src/components/page/Page.tsx
- packages/ui/src/components/page/SideBar.tsx
- packages/ui/src/components/page/Version.tsx
- packages/ui/src/constants/index.ts
- packages/ui/src/constants/styles.ts
- packages/ui/src/hooks/useAccounts.ts
- packages/ui/src/pages/Profile/Accounts.tsx
- packages/ui/src/pages/Profile/Profile.tsx
- packages/ui/src/providers/GlobalStyle.tsx
- packages/ui/src/providers/Providers.tsx
Closes #15. Adds a basic page styling.
> 🎨 Basic page styling

- packages/ui/package.json
- packages/ui/src/components/AccountInfo.tsx
- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/components/TransferModal.tsx
- packages/ui/src/components/modal.tsx
- packages/ui/src/hooks/useBalances.ts
- packages/ui/src/hooks/useNumberInput.ts
- packages/ui/src/pages/Profile/Accounts.tsx
- packages/ui/src/pages/Profile/ProfileComponent.tsx
- packages/ui/src/utils/formatters.ts
- packages/ui/test/hooks/useNumberInput.test.ts
- packages/ui/test/pages/Accounts.test.tsx
- packages/ui/test/utils/formatters.test.ts
- yarn.lock
In this PR:
- user can select arbitrary value in token transfer modal
- set half/max balance value
- few UI components were refactored as some were duplicated
However, I still face the problem with the development setup as I wan't able to set working environment other than default substrate build on my Apple M1 :/
> 💸 Token transfer amount handling

- packages/ui/src/components/page/NetworkSwitch.tsx
- packages/ui/src/components/page/SideBar.tsx
- packages/ui/src/components/page/Version.tsx
- packages/ui/src/hooks/useLocalStorage.ts
- packages/ui/src/providers/api/provider.tsx
- packages/ui/test/hooks/useLocalStorage.test.ts
Simple network switcher:
- displays currently connected network
- allows switching between local dev and joystream testnet
> 🔄 Network switch

- packages/ui/src/components/modal.tsx
- packages/ui/src/components/selects/AccountSelectTemplate/OptionAccount.tsx
- packages/ui/src/components/selects/AccountSelectTemplate/OptionListAccount.tsx
- packages/ui/src/components/selects/AccountSelectTemplate/SelectAccount.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/pages/Profile/Accounts.tsx
> Modal header scroll and modal styles fixes

- packages/ui/src/components/AccountInfo.tsx
- packages/ui/src/pages/Profile/Accounts.tsx
> Hide long account name overflow

- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/components/modal.tsx
- packages/ui/src/hooks/useBalance.ts
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/TransferModal/TransferModal.tsx
- packages/ui/src/pages/Profile/Accounts.tsx
- packages/ui/src/pages/Profile/ProfileComponent.tsx
- packages/ui/src/pages/Profile/TotalBalances.tsx
- packages/ui/test/modals/TransferModal.test.tsx
> 📥 Transfer tokens to account

- packages/types/package.json
- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/modals/AddMembershipModal.tsx
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- yarn.lock
> 🙅‍♂️ Disable send for empty account

- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/components/page/PageTabs.tsx
- packages/ui/src/hooks/types.ts
- packages/ui/src/hooks/useBalance.ts
- packages/ui/src/hooks/useBalances.ts
- packages/ui/src/hooks/useTotalBalances.ts
- packages/ui/src/pages/Profile/MyAccounts.tsx
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- packages/ui/src/pages/Profile/MyMemberships.tsx
- packages/ui/src/pages/Profile/MyProfileTabs.tsx
> ⚖️ Accounts list – transferable balance

- packages/ui/src/components/page/PageTabs.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- packages/ui/src/pages/Profile/MyMemberships.tsx
- packages/ui/src/pages/Profile/MyProfileTabs.tsx
> Add page tabs animation

- packages/ui/src/components/page/Page.tsx
- packages/ui/src/components/page/PageContent.tsx
- packages/ui/src/components/page/SideBar.tsx
- packages/ui/src/components/page/Sidebar/Breadcrumbs/Breadcrumbs.tsx
- packages/ui/src/components/page/Sidebar/Navigation.tsx
- packages/ui/src/pages/Profile/MyAccounts.tsx
- packages/ui/src/pages/Profile/MyMemberships.tsx
- packages/ui/src/providers/GlobalStyle.tsx
> Fixed sidebar

- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransactionSuccessModal.tsx
- packages/ui/src/modals/TransferModal/TransferModal.tsx
- packages/ui/test/hooks/useTotalBalances.test.tsx
- packages/ui/test/mocks/keyring/Keyring.ts
- packages/ui/test/mocks/keyring/index.ts
- packages/ui/test/modals/TransferModal.test.tsx
Closes #112.
Updated:
- transaction fee is no properly handled in success window
- improved keyring mocks
> 💵 Handle transaction fee in transfer

- packages/ui/src/pages/Profile/MyMemberships/Memberships.tsx
> No memberships page styles

- packages/ui/src/modals/AddMembershipModal.tsx
- packages/ui/src/providers/api/provider.tsx
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/tsconfig.json
> 💰 Display membership fee

- packages/ui/src/components/Modal.tsx
- packages/ui/src/modals/WaitModal.tsx
> 🪞Use React portal for modals

- packages/ui/src/components/forms/Checkbox.tsx
- packages/ui/src/components/forms/LabelLink.tsx
- packages/ui/src/components/icons/CheckboxIcon.tsx
- packages/ui/src/components/typography/Text.tsx
- packages/ui/src/modals/AddMembershipModal.tsx
- packages/ui/src/modals/common.tsx
> Checkbox component

- packages/ui/src/components/Modal.tsx
- packages/ui/src/modals/AddMembershipModal.tsx
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransactionFailureModal.tsx
- packages/ui/src/modals/TransferModal/TransactionSuccessModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/WaitModal.tsx
> Modal sizes via props

- packages/ui/src/components/page/Page.tsx
- packages/ui/src/providers/GlobalStyle.tsx
> Remove overscroll

- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/components/page/Sidebar/ProfileComponent.tsx
- packages/ui/src/components/selects/SelectAccount/OptionAccount.tsx
- packages/ui/src/components/selects/SelectAccount/OptionListAccount.tsx
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
> UI styles fixes

- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/test/modals/TransferModal.test.tsx
> 🔤 Disable value input when no account was chosen

- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/common.tsx
- yarn.lock
> Format token in input

- packages/ui/src/components/MemberInfo.tsx
- packages/ui/src/components/Modal.tsx
- packages/ui/src/components/forms/Checkbox.tsx
- packages/ui/src/components/forms/Input.tsx
- packages/ui/src/components/forms/ToggleCheckbox.tsx
- packages/ui/src/components/icons/ArrowDownExpandedIcon.tsx
- packages/ui/src/components/icons/FounderMemberIcon.tsx
- packages/ui/src/components/icons/VerifiedMemberIcon.tsx
- packages/ui/src/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/CurrentMember.tsx
- packages/ui/src/components/typography/TokenValue.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/modals/common.tsx
- packages/ui/src/pages/Profile/MyMemberships/MemberItem.tsx
- packages/ui/src/providers/GlobalStyle.tsx
> Restyle member info component

- packages/ui/jest.config.ts
- packages/ui/src/components/AccountInfo.tsx
- packages/ui/src/mocks/data/raw/members.json
- packages/ui/src/pages/Profile/MyProfileTabs.tsx
- packages/ui/test/components/CurrentMember.test.tsx
- packages/ui/test/hooks/useMembership.test.tsx
- packages/ui/test/mocks/keyring/accounts.ts
- packages/ui/test/mocks/keyring/signers.ts
- packages/ui/test/mocks/members/index.ts
- packages/ui/test/mocks/server/index.ts
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/test/modals/TransferModal.test.tsx
- packages/ui/test/pages/Accounts.test.tsx
- packages/ui/test/pages/MyMemberships.test.tsx
- packages/ui/test/setup.ts
> ⭐️ Highlight member accounts

- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
> 🧤 Improve look and feel of clickable headers

- packages/ui/src/components/AccountInfo.tsx
- packages/ui/src/utils/formatters.ts
- packages/ui/test/pages/Accounts.test.tsx
- packages/ui/test/utils/formatters.test.ts
> ✂️ Shorten address display

- packages/ui/src/components/MemberInfo.tsx
- packages/ui/src/components/buttons/Buttons.tsx
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- packages/ui/src/pages/Profile/MyMemberships/MemberItem.tsx
- packages/ui/src/pages/Profile/MyMemberships/Memberships.tsx
> 👤 Memberships page

- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- packages/ui/src/pages/Profile/MyMemberships/Memberships.tsx
> Sorting arrows for accounts

- packages/ui/src/components/AccountInfo.tsx
- packages/ui/src/components/CopyComponent.tsx
- packages/ui/src/components/buttons/CopyButton.tsx
- packages/ui/src/components/icons/CopyIcon.tsx
- packages/ui/src/components/icons/symbols/FailureSymbol.tsx
- packages/ui/src/components/icons/symbols/SuccessSymbol.tsx
- packages/ui/src/constants/styles.ts
> Copy button + styles

- packages/ui/src/components/AddMembershipButtonSwitch.tsx
- packages/ui/src/components/Help.tsx
- packages/ui/src/components/Modal.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/SwitchMemberModal.tsx
> Switch members restyling

- packages/ui/src/components/Modal.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/SwitchMemberModal.tsx
- packages/ui/src/modals/AddMembershipModal/AddMembershipFailureModal.tsx
- packages/ui/src/modals/AddMembershipModal/AddMembershipModal.tsx
- packages/ui/src/modals/AddMembershipModal/AddMembershipSuccessModal.tsx
- packages/ui/src/modals/AddMembershipModal/MembershipFormModal.tsx
- packages/ui/src/modals/AddMembershipModal/SignCreateMemberModal.tsx
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransactionFailureModal.tsx
- packages/ui/src/modals/TransferModal/TransactionSuccessModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/TransferModal/TransferModal.tsx
- packages/ui/src/modals/WaitModal.tsx
> Close on outside modal click

- packages/ui/src/providers/GlobalStyle.tsx
> Text selection styles

- packages/ui/src/components/buttons/Buttons.tsx
> Ghost button hover style

- packages/ui/src/components/page/PageTabs.tsx
> Tabs hover style

- packages/ui/src/components/Help.tsx
- packages/ui/src/components/icons/symbols/LinkSymbol.tsx
- packages/ui/src/components/icons/symbols/SuccessSymbol.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/pages/Profile/MyAccounts/TotalBalances.tsx
> Help tooltip styles

- packages/ui/src/components/Link.tsx
> Link component

- packages/ui/src/components/account/SelectAccount/SelectedAccount.tsx
- packages/ui/src/components/account/SelectAccount/index.ts
- packages/ui/src/modals/TransferInviteModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferDetailsModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferFailureModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferInviteModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferSuccessModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
> 🆘 Add Transfer Invites transaction to frontend

- packages/ui/src/App.tsx
- packages/ui/src/components/ConnectionStatus.tsx
- packages/ui/src/components/page/SideNotification.tsx
- packages/ui/src/components/typography/Text.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/providers/api/provider.tsx
> Side notification component

- packages/ui/src/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/api/queries/__generated__/members.generated.tsx
- packages/ui/src/api/queries/members.graphql
- packages/ui/src/api/schemas/schema.graphql
- packages/ui/src/mocks/resolvers.ts
- packages/ui/src/mocks/server.ts
> 🕵️ Member search queries

- packages/ui/src/components/SortedListHeaders.tsx
- packages/ui/src/pages/Profile/MyAccounts/Accounts.tsx
- packages/ui/src/pages/Profile/MyMemberships/Memberships.tsx
- packages/ui/src/pages/Profile/MyMemberships/helpers.ts
- packages/ui/src/utils/sorting/Comparator.ts
- packages/ui/src/utils/sorting/sortMemberships.ts
- packages/ui/test/utils/Comparator.test.ts
- packages/ui/test/utils/sortMemberships.test.ts
> 🐝 Add member sorting to frontend

- packages/ui/src/common/types/memberships.ts
- packages/ui/src/modals/AddMembershipModal/MembershipFormModal.tsx
- packages/ui/src/modals/AddMembershipModal/SignCreateMemberModal.tsx
- packages/ui/test/modals/AddMembershipModal.test.tsx
> 📼 Add support for the 'I was referred' option

- packages/ui/src/components/forms/FieldError.tsx
- packages/ui/src/components/forms/Input.tsx
- packages/ui/src/modals/AddMembershipModal/MembershipFormModal.tsx
- packages/ui/src/modals/AddMembershipModal/formReducer.ts
- packages/ui/src/modals/AddMembershipModal/useFormValidation.ts
- packages/ui/src/modals/TransferInviteModal/TransferDetailsModal.tsx
- packages/ui/test/components/CurrentMember.test.tsx
- packages/ui/test/helpers/selectMember.ts
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/test/modals/TransferInviteModal.test.tsx
> 💪 Validate user handle

- packages/ui/src/components/Help.tsx
- packages/ui/src/components/icons/FounderMemberIcon.tsx
- packages/ui/src/components/icons/VerifiedMemberIcon.tsx
- packages/ui/src/components/membership/MemberInfo.tsx
- packages/ui/src/components/membership/MemberProfile/MemberProfile.tsx
- packages/ui/src/components/membership/components.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/CurrentMember.tsx
- packages/ui/src/components/selects/select.tsx
- packages/ui/src/pages/Profile/MyMemberships/MemberItem.tsx
- packages/ui/test/helpers/selectAccount.ts
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/test/modals/TransferModal.test.tsx
> Roles and statuses with tooltip

- packages/ui/src/components/membership/SelectMember/OptionsListMember.tsx
- packages/ui/src/components/membership/SelectMember/SelectMember.tsx
- packages/ui/src/modals/InviteMemberModal/InviteFormModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferDetailsModal.tsx
- packages/ui/test/helpers/selectMember.ts
- packages/ui/test/modals/InviteMemberModal.test.tsx
> 🍭 Simplify member select

- packages/ui/src/components/page/Sidebar/CurrentMember/CurrentMember.tsx
- packages/ui/test/components/CurrentMember.test.tsx
> 🦧 Open Select Membership dialog on login

- packages/ui/src/components/account/SelectAccount/SelectedAccount.tsx
- packages/ui/src/components/buttons/Toggle.tsx
- packages/ui/src/components/forms/InputComponent.tsx
- packages/ui/src/components/typography/Text.tsx
- packages/ui/src/modals/AddMembershipModal/AddMembershipSuccessModal.tsx
- packages/ui/src/modals/InviteMemberModal/InviteFormModal.tsx
- packages/ui/src/modals/TransferInviteModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferDetailsModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferSuccessModal.tsx
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransactionSuccessModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/UpdateMembershipModal/SignUpdateMembershipModal.tsx
- packages/ui/src/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
- packages/ui/src/modals/UpdateMembershipModal/UpdateMembershipSuccessModal.tsx
- packages/ui/src/modals/common.tsx
> Input components implementation in modals

- packages/ui/src/components/Help.tsx
- packages/ui/src/modals/AddMembershipModal/MembershipFormModal.tsx
- packages/ui/src/modals/AddMembershipModal/SignCreateMemberModal.tsx
- packages/ui/src/modals/TransferInviteModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/UpdateMembershipModal/SignUpdateMembershipModal.tsx
> Helper tooltips bugfix

- packages/ui/src/components/Modal.tsx
- packages/ui/src/components/icons/Loader.tsx
- packages/ui/src/components/membership/MemberProfile/MemberProfile.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/SwitchMemberModal.tsx
- packages/ui/src/modals/AddMembershipModal/AddMembershipFailureModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferFailureModal.tsx
- packages/ui/src/modals/TransferModal/TransactionFailureModal.tsx
- packages/ui/src/modals/UpdateMembershipModal/UpdateMembershipFailureModal.tsx
- packages/ui/src/modals/WaitModal.tsx
- packages/ui/src/providers/GlobalStyle.tsx
> Change modal sizes

- packages/ui/src/components/Modal.tsx
- packages/ui/src/components/forms/Checkbox.tsx
- packages/ui/src/components/forms/LabelLink.tsx
- packages/ui/src/components/membership/MemberProfile/MemberDetails.tsx
- packages/ui/src/components/page/SideNotification.tsx
- packages/ui/src/components/page/Sidebar/CurrentMember/CurrentMember.tsx
- packages/ui/src/components/typography/Text.tsx
- packages/ui/src/modals/AddMembershipModal/MembershipFormModal.tsx
> Restyle checkbox component (sizes, colors)

- packages/ui/src/components/page/PageTabs.tsx
> Bolder active tabs via text-stroke

- packages/ui/src/components/membership/MemberProfile/MemberProfile.tsx
> Restyle side panel header

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/components/TransferInviteButton.tsx
- packages/ui/src/components/membership/AddMembershipButton.tsx
- packages/ui/src/components/membership/MemberProfile/MemberDetails.tsx
- packages/ui/src/components/membership/MemberProfile/MemberProfile.tsx
- packages/ui/src/components/membership/MemberProfile/index.ts
- packages/ui/src/components/membership/MemberProfile/types.ts
- packages/ui/src/components/page/Sidebar/CurrentMember/CurrentMember.tsx
- packages/ui/src/hooks/useModal.ts
- packages/ui/src/hooks/useTransactionFee.ts
- packages/ui/src/hooks/useTransferInviteFee.ts
- packages/ui/src/mocks/data/mockBlocks.ts
- packages/ui/src/mocks/data/mockMembers.ts
- packages/ui/src/mocks/data/raw/members.json
- packages/ui/src/mocks/server.ts
- packages/ui/src/modals/AddMembershipModal/AddMembershipSuccessModal.tsx
- packages/ui/src/modals/AddMembershipModal/index.tsx
- packages/ui/src/modals/AddMembershipModal/types.ts
- packages/ui/src/modals/TransferInviteModal/TransferInviteModal.tsx
- packages/ui/src/modals/TransferInviteModal/index.ts
- packages/ui/src/modals/TransferInviteModal/types.ts
- packages/ui/src/pages/Profile/MyMemberships/MemberItem.tsx
- packages/ui/src/providers/modal/context.tsx
- packages/ui/src/providers/modal/provider.tsx
- packages/ui/src/providers/modal/types.ts
- packages/ui/test/mocks/server/index.ts
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/test/modals/TransferInviteModal.test.tsx
> 🎫 Transfer invites from member profile

- packages/ui/src/components/membership/MemberInfo.tsx
- packages/ui/src/components/membership/MemberProfile/MemberProfile.tsx
- packages/ui/src/membership/components/EditMembershipButton.tsx
> Move edit member button to modal header

- packages/types/src/blog.ts
- packages/types/src/common.ts
- packages/types/src/forum.ts
- packages/types/src/index.ts
- packages/types/src/members.ts
- packages/types/src/proposals.ts
- packages/types/src/scripts/generateAugmentCodec.ts
- packages/types/src/working-group/index.ts
- yarn.lock
It looks like I didn't copy everything correctly.
> 🧑‍🔧 Fix types package

- packages/ui/src/App.tsx
- packages/ui/src/assets/images/Members/AvatarPlaceholder.tsx
- packages/ui/src/components/membership/components.tsx
- packages/ui/src/components/page/SideBar.tsx
- packages/ui/src/components/page/Sidebar/LinksIcons/WorkingGroupsIcon.tsx
- packages/ui/src/components/typography/Subscription.tsx
- packages/ui/src/constants/styles.ts
- packages/ui/src/pages/Groups/Groups.tsx
- packages/ui/src/pages/Groups/WorkingGroup.tsx
- packages/ui/src/pages/Groups/WorkingGroups.tsx
> Sliced working group

- packages/ui/src/App.tsx
- packages/ui/src/hooks/useToggle.ts
- packages/ui/src/mocks/useSudoBudget.ts
- packages/ui/src/modals/AddMembershipModal/SignCreateMemberModal.tsx
- packages/ui/src/modals/InviteMemberModal/InviteMemberModal.tsx
- packages/ui/src/modals/InviteMemberModal/WorkingGroupBudgetModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferSuccessModal.tsx
- packages/ui/test/mocks/chainTypes.ts
- packages/ui/test/mocks/transactions.ts
- packages/ui/test/modals/AddMembershipModal.test.tsx
- packages/ui/test/modals/InviteMemberModal.test.tsx
- packages/ui/test/modals/UpdateMembershipModal.test.tsx
- packages/ui/test/utils/isValidAddress.test.ts
- packages/ui/test/utils/sortMemberships.test.ts
> 💰 Working group budget check

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/components/TransferButton.tsx
- packages/ui/src/components/icons/TransferIcons.tsx
- packages/ui/src/hooks/useTransactionFee.ts
- packages/ui/src/modals/TransferInviteModal/RequirementFailedModal.tsx
- packages/ui/src/modals/TransferInviteModal/TransferInviteModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/modals/TransferModal/TransferModal.tsx
- packages/ui/src/modals/TransferModal/index.ts
- packages/ui/src/modals/TransferModal/types.ts
- packages/ui/test/modals/TransferModal.test.tsx
- packages/ui/test/utils/sortMemberships.test.ts
> 💥 Add modal for failed balance check

- packages/ui/src/components/buttons/Buttons.tsx
> Resolve button on hover bug

- packages/ui/src/components/buttons/Toggle.tsx
> Get toggle's arrows back

- packages/ui/src/components/page/SideBar.tsx
- packages/ui/src/components/page/Sidebar/NavigationLink.tsx
> Navigation link styles

- packages/ui/src/components/ConnectionStatus.tsx
- packages/ui/test/components/ConnectionStatus.test.tsx
> 🪃 Auto-close connection status notification

- packages/ui/src/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
> Restyle last breadcrumb

- packages/ui/src/modals/InviteMemberModal/InviteMemberModal.tsx
- packages/ui/src/modals/InviteMemberModal/InviteSuccessModal.tsx
- packages/ui/test/modals/InviteMemberModal.test.tsx
> 🎊 Add InviteSuccessModal

- README.md
- package.json
- packages/ui/package.json
> 🌍 Add build storybook preview configuration

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/AppPage.tsx
- packages/ui/src/app/hooks/usePageTabs.ts
- packages/ui/src/app/pages/Profile/MyAccounts.tsx
- packages/ui/src/app/pages/Profile/MyMemberships.tsx
- packages/ui/src/app/pages/Profile/components/MyProfileTabs.tsx
- packages/ui/src/app/pages/WorkingGroups/MyApplications.tsx
- packages/ui/src/app/pages/WorkingGroups/MyRoles.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/app/pages/WorkingGroups/components/WorkingGroupsTabs.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/Breadcrumbs.tsx
> 🌱 Openings stubs

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/mocks/data/mockWorkingGroups.ts
- packages/ui/src/mocks/data/raw/workingGroups.json
- packages/ui/src/mocks/resolvers.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/hooks/useOpenings.ts
- packages/ui/src/working-groups/hooks/useWorkingGroups.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroup.ts
> 👷 Mock working group data

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/memberships/hooks/useMembership.ts
- packages/ui/src/mocks/data/mockOpenings.ts
- packages/ui/src/mocks/data/mockWorkingGroups.ts
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/mocks/data/raw/workingGroups.json
- packages/ui/src/mocks/hooks/useSudoBudget.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroup.ts
> 🎣 Fetch openings data

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/app/pages/WorkingGroups/components/OpeningsTab.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/mocks/resolvers.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/OpeningsList.stories.tsx
- packages/ui/src/working-groups/components/OpeningsList.tsx
- packages/ui/src/working-groups/hooks/useOpenings.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroup.ts
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/src/working-groups/types/index.ts
> 🚪 Display opening data from query node

- packages/ui/src/common/components/Help.tsx
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberListItem/MemberListItem.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/components/components.tsx
> Past components style fixes

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/index.ts
- packages/ui/src/app/pages/WorkingGroups/components/OpeningsTab.tsx
> 🪖 Stub Working Group history tab

- packages/ui/src/mocks/data/raw/workingGroups.json
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroup.ts
> 🏦 Display working group budget

- packages/ui/src/app/pages/Profile/components/Accounts.tsx
- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/common/components/BadgeViolet.ts
- packages/ui/src/common/components/CountBadge.tsx
- packages/ui/src/common/components/Loading.tsx
- packages/ui/src/common/components/Tabs.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/common/components/statistics/MultiTokenValueStat.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/common/components/statistics/Statistics.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
> Layout fix on website

- packages/ui/src/app/pages/WorkingGroups/MyApplications.tsx
- packages/ui/src/working-groups/components/ApplicationsList.tsx
- packages/ui/src/working-groups/hooks/useApplications.ts
- packages/ui/src/working-groups/types/WorkingGroupApplication.ts
> 💀 Add My Applications skeleton

- packages/ui/src/common/components/Stepper.stories.tsx
- packages/ui/src/common/components/Stepper.tsx
- packages/ui/src/common/components/StepperModal.tsx
> 🪜 Stepper component

- packages/ui/src/app/pages/WorkingGroups/MyApplications.tsx
- packages/ui/src/app/pages/WorkingGroups/helpers.ts
- packages/ui/src/working-groups/model/isPendingApplication.ts
- packages/ui/test/working-groups/pages/MyApplications.test.tsx
> ℹ️ Add more informative states to MyApplications

- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRolePrepareModal.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> 🪙 Apply stake step

- packages/ui/package.json
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/common/components/CKEditor.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/statistics/MultiTokenValueStat.tsx
- packages/ui/src/common/constants/styles.ts
- packages/ui/src/mocks/data/mockOpenings.ts
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/mocks/resolvers.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/ApplicationQuestionInput.tsx
- packages/ui/src/working-groups/hooks/useOpeningQuestions.ts
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRolePrepareModal.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- yarn.lock
> 🏗 Application form builder

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/mocks/data/mockWorkingGroups.ts
- packages/ui/src/mocks/data/raw/workingGroups.json
- packages/ui/src/working-groups/hooks/useWorkers.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
> ⚙️ Add group workers history

- packages/ui/src/working-groups/components/ApplicationQuestionInput.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplicationStep.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRolePrepareModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
> 💅 Application form updates

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/common/components/page/Sidebar/LinksIcons/MembersIcon.tsx
#430 Add empty members page and integrate it with the navigation system
> 📄 Add the Members page

- packages/ui/src/common/components/BadgeViolet.ts
- packages/ui/src/common/components/typography/Badge.ts
> Fix badge components

- packages/ui/src/common/components/buttons/Buttons.tsx
> Fix button icons on hover

- packages/ui/src/common/components/page/Sidebar/LinksIcons/MembersIcon.tsx
> Fix current navbar members icon

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/mocks/data/mockApplications.ts
- packages/ui/src/mocks/data/raw/applications.json
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/mocks/resolvers.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/hooks/useApplicationQuestionAnswers.ts
- packages/ui/src/working-groups/hooks/useOpenings.ts
- packages/ui/src/working-groups/hooks/useWorkers.ts
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/ApplicationDetailsModal.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/FormDetails.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/ApplicationFormQuestionAnswer.ts
- packages/ui/src/working-groups/types/ApplicationQuestionAnswer.ts
> 🌵 Display form answers in application details

- packages/ui/src/accounts/components/AccountInfo.tsx
- packages/ui/src/app/pages/WorkingGroups/MyApplications.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/buttons/CopyButton.tsx
- packages/ui/src/common/components/buttons/Toggle.tsx
- packages/ui/src/common/components/icons/FileIcon.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/common/components/selects/components.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/working-groups/components/ApplicationsList.tsx
- packages/ui/src/working-groups/components/OpeningAndApplicationsComponents/OACStyledComponents.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
> Design fixes from list

- .eslintrc.json
- packages/ui/.storybook/main.js
- packages/ui/dev/webpack.shared.js
- packages/ui/jest.config.ts
- packages/ui/src/app/App.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.tsx
- packages/ui/src/memberships/components/MemberList/MemberList.stories.tsx
- packages/ui/webpack.config.js
Updated the path aliases configuration to have proper sorting.
I've also made configuration of various webpack's options reusable.
> 👺 Path aliases

- packages/ui/src/common/components/Tabs.tsx
> Upgrade tabs elements

- packages/ui/src/memberships/components/MembersSection.tsx
> Fix memberships table one more time

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/charts/PercentageChart.stories.tsx
- packages/ui/src/common/components/charts/PercentageChart.tsx
- packages/ui/src/common/components/statistics/TokenValueStat.stories.tsx
- packages/ui/src/common/model/JoystreamNode/getEventParam.ts
- packages/ui/src/common/model/JoystreamNode/index.ts
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipModal.tsx
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/mocks/data/mockOpenings.ts
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/working-groups/components/OpeningFormPreview.stories.tsx
- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
- packages/ui/src/working-groups/components/OpeningsList.stories.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.stories.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRolePrepareModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSuccessModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/model/index.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
Sorry for the changes in other components:
1. The `PercentageChart` caused React errors in the console
2. I've unified getting some mocks because it is easier to change one method rather than 5 stories :D
In this PR:
- I've added better types for substrate event data reading
- Implemented the "Success" step data retrieval that _should_ be consistent with Joystream event naming
- The stepper / form data typings needs some work in a follow-up PR
> 🎉 Apply fore a role success

- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
> Breadcrumbs fixes

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
> Fix wg tabs in history tab

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/icons/ArrowIcon.tsx
- packages/ui/test/accounts/modal/TransferModal.test.tsx
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
> Buttons text alignment

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/working-groups/components/ApplicantsList.tsx
- packages/ui/src/working-groups/components/Worker.tsx
- packages/ui/src/working-groups/components/WorkersList.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
- yarn.lock
See #292 
* Integrate applications with GraphQL
TODO:
Add 'created' footer
> 🎓Open position preview applicants

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/AppPage.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/constants/breadcrumbs.ts
- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/app/pages/Proposals/components/ProposalsTabs.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/common/components/page/PageHeader.tsx
- packages/ui/src/common/components/page/Sidebar/LinksIcons/ProposalsIcon.tsx
- packages/ui/src/common/components/storybookParts/previewStyles.tsx
- packages/ui/src/proposals/components/AddProposalButton/AddProposalButton.stories.tsx
- packages/ui/src/proposals/components/AddProposalButton/AddProposalButton.tsx
- packages/ui/src/proposals/components/AddProposalButton/index.ts
- packages/ui/src/proposals/components/NoProposals/NoProposals.stories.tsx
- packages/ui/src/proposals/components/NoProposals/NoProposals.tsx
- packages/ui/src/proposals/components/NoProposals/index.ts
- packages/ui/src/proposals/constants/routes.ts
> 📥 Setup Proposals page

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/AboutDateColumn.tsx
- packages/ui/src/common/components/BlockTime.tsx
- packages/ui/src/common/queries/__generated__/blocks.generated.tsx
- packages/ui/src/common/queries/blocks.graphql
- packages/ui/src/common/types/Block.ts
- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
- packages/ui/src/memberships/hooks/useMembership.ts
- packages/ui/src/memberships/types/memberships.ts
- packages/ui/src/mocks/data/raw/blocks.json
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/GeneralDetails.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/working-groups/pages/MyApplications.test.tsx
* Add footer component with created date and block info
> 🦶 Open position preview footer

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/memberships/components/AddMembershipButton.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
> Update sidebar buttons

- packages/ui/package.json
- packages/ui/webpack.config.js
> Show component names in devtools

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
> WG opening row arrow + new button style

- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> 🎭 Issue proper extrinsic when applying for role

- packages/ui/src/common/components/buttons/Toggle.tsx
- packages/ui/src/working-groups/components/OpeningAndApplicationsComponents/OACStyledComponents.tsx
> Move arrow in opening row to center

- packages/ui/src/common/components/page/PageContent.tsx
> Finaly fixed pinned to bottom content on pages

- packages/ui/src/common/components/BadgeRed.ts
- packages/ui/src/common/components/BadgeViolet.ts
- packages/ui/src/working-groups/components/OpeningAndApplicationsComponents/OACStyledComponents.tsx
> Implement new overflow with full max width

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/hooks/useOpenings.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
See #497 
This is naive implementation, it needs adjusting mocks
> 🛠 Add pagination for past openings

- packages/ui/src/common/components/Tabs.tsx
> Remove tabs reverse animation

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/icons/LinkIcon.tsx
> Use buttons group in WG Openings

- packages/ui/src/common/components/page/SideNotification.tsx
> Update side notification shadow

- packages/ui/src/common/components/SidePane/SidePane.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
> Add copy button into member side panel

- packages/ui/src/common/components/Modal/Modal.tsx
> Update success modal spaces

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/AppPage.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/icons/BlockIcon.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/common/components/statistics/NumericValueStat.tsx
> Fix opening page preview

- packages/ui/dev/scripts/generators/generateWorkers.js
- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/helpers.ts
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberList/Members.tsx
- packages/ui/src/memberships/components/MemberListItem/Member.tsx
- packages/ui/src/memberships/components/MemberListItem/MyMember.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/helpers.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/memberships/types/casting.ts
- packages/ui/src/memberships/types/memberships.ts
- packages/ui/src/mocks/data/mockMembers.ts
- packages/ui/src/mocks/data/raw/applications.json
- packages/ui/src/mocks/data/raw/blocks.json
- packages/ui/src/mocks/data/raw/members.json
- packages/ui/src/mocks/data/raw/openings.json
- packages/ui/src/mocks/data/raw/upcomingOpenings.json
- packages/ui/src/mocks/data/raw/workers.json
- packages/ui/src/mocks/data/raw/workingGroups.json
- packages/ui/src/working-groups/helpers.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/test/_mocks/members/index.ts
- packages/ui/test/membership/helpers.test.ts
> 🙄 Handle member roles

- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/common/components/List/ListHeader.tsx
- packages/ui/src/memberships/components/MembersSection.tsx
- packages/ui/src/mocks/data/mockProposals.ts
- packages/ui/src/mocks/hooks/useMockDelay.ts
- packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
- packages/ui/src/proposals/hooks/useProposals.ts
> 🖼️ Complete the proposals current page layout

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/working-groups/components/Roles/MyRoleAccount.tsx
> 🔄 Add move tokens button

- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRolePrepareModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleSignModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleSuccessModal.tsx
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/test/working-groups/modals/LeaveRoleModal.test.tsx
> 🚪 Add a Leave Role modal

- packages/ui/src/common/components/SidePane/SidePane.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/ApplicationDetailsModal.tsx
> Side panel smaller top size for Applications

- .eslintrc.json
- packages/ui/src/accounts/providers/accounts/provider.tsx
- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/Pagination/Pagination.stories.tsx
- packages/ui/src/common/components/WaitModal.stories.tsx
- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
- packages/ui/src/common/logger/error.ts
- packages/ui/src/common/logger/index.ts
- packages/ui/src/common/logger/info.ts
- packages/ui/src/common/providers/keyring/provider.tsx
- packages/ui/src/memberships/hooks/useMembers.ts
- packages/ui/src/memberships/hooks/useMembership.ts
- packages/ui/src/memberships/providers/membership/provider.tsx
- packages/ui/src/mocks/hooks/useMockMembers.ts
- packages/ui/src/mocks/hooks/useSudoBudget.ts
- packages/ui/src/proposals/hooks/useProposals.ts
> ⛔️ Forbid calling console in code, use custom logger instead

- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/working-groups/components/OpeningsList.tsx
Closes #610 
Closes #510 
To avoid using buttons without onClick wrapped by Link to change location on Link click.
> Add links looks like buttons

- packages/ui/src/common/components/forms/Checkbox.tsx
> Update checkbox and side label styles

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/working-groups/hooks/useGroupStatistics.ts
- packages/ui/src/working-groups/hooks/useWorkers.ts
> 🪨 Add a dashboard with stats to About Group tab

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/working-groups/components/Roles/MyRoleAccount.tsx
> 🧥 Handle dynamic balance types and stake height

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/components/StatusBadges.tsx
> ⌨️ WG about tab styling

- packages/ui/src/accounts/components/SelectAccount/SelectedAccount.tsx
- packages/ui/src/common/components/Warning.tsx
- packages/ui/src/common/components/buttons/Buttons.stories.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/buttons/DropDownToggle.tsx
- packages/ui/src/common/components/buttons/LinkButtons.stories.tsx
- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/common/components/buttons/Toggle.tsx
> 🖲 Update buttons styles

- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/Warning.tsx
> 📏 Minor style fixes for modals

- packages/ui/src/common/components/Pagination/Pagination.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/page/PageContent.tsx
> 👉🏻 Pagination with buttons style

- packages/ui/src/common/components/Warning.tsx
> 🎟 Fix warning component styles

- packages/ui/src/common/components/forms/Checkbox.stories.tsx
- packages/ui/src/common/components/forms/Radio.stories.tsx
- packages/ui/src/common/components/forms/Radio.tsx
> 📻 Radio button component

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
- yarn.lock
> ✌️ Handle application and opening buttons

- packages/ui/.storybook/preview.jsx
- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/CopyComponent.stories.tsx
- packages/ui/src/common/components/FailureModal.stories.tsx
- packages/ui/src/common/components/Stepper.stories.tsx
- packages/ui/src/common/components/TransactionModal.stories.tsx
- packages/ui/src/common/components/WaitModal.stories.tsx
- packages/ui/src/common/components/buttons/Buttons.stories.tsx
- packages/ui/src/common/components/buttons/CloseButton.stories.tsx
- packages/ui/src/common/components/buttons/LinkButtons.stories.tsx
- packages/ui/src/common/components/forms/Checkbox.stories.tsx
- packages/ui/src/common/components/forms/InputComponent.stories.tsx
- packages/ui/src/common/components/forms/Radio.stories.tsx
- packages/ui/src/common/components/forms/TogglableIcon.stories.tsx
- packages/ui/src/common/components/forms/ToggleCheckbox.stories.tsx
- packages/ui/src/common/components/selects/select.stories.tsx
Added sort & stories grouping.
> 📘 Storybook updates

- packages/ui/src/common/components/Activities/Activities.stories.tsx
- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/Activities/ActivityToIconMap.tsx
- packages/ui/src/common/components/Link.tsx
- packages/ui/src/common/components/ModalLink.tsx
- packages/ui/src/common/components/RouterLink.tsx
- packages/ui/src/common/components/icons/activities/HiredIcon.tsx
- packages/ui/src/common/hooks/useActivities.ts
- packages/ui/src/memberships/components/MemberModalLink.tsx
- packages/ui/src/working-groups/components/Activities/ApplicationWithdrawnContent.tsx
- packages/ui/src/working-groups/components/Activities/AppliedOnOpeningContent.tsx
- packages/ui/src/working-groups/components/Activities/LeaderSetContent.tsx
- packages/ui/src/working-groups/components/Activities/StatusTextChangedContent.tsx
- packages/ui/src/working-groups/types/WorkingGroupActivity.ts
See: #301 
The main feature of this one is the ModalLink component. I tried to enforce decent type control in it - it works, but doesn't look very elegant IMO
> 🪑 Add convenience components for activities

- packages/ui/src/working-groups/components/OpeningsList.tsx
> ⛰ Fix button sizes in opening list

- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/TransactionModal.stories.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/buttons/FilterButtons.tsx
- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/common/components/buttons/Toggle.tsx
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/components/icons/PlusIcon.tsx
- packages/ui/src/memberships/components/AddMembershipButton.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/memberships/components/InviteMemberButton.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
- packages/ui/src/proposals/components/AddProposalButton.tsx
- packages/ui/src/working-groups/components/OpeningsList.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSuccessModal.tsx
- packages/ui/src/working-groups/modals/ChangeAccountModal/ChangeAccountSuccessModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRolePrepareModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleSuccessModal.tsx
> 👺 Fix buttons sizes. Sizes are required

- packages/ui/src/app/App.tsx
- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/proposals/hooks/usePastProposals.ts
> 🕰️ Open the Past Proposals tab

- packages/ui/src/mocks/data/mockOpenings.ts
> 📙 Fix ApplyForRoles success step

- packages/ui/src/app/pages/Profile/MyMemberships.tsx
- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/common/components/page/PageHeader.tsx
> 🔝 Move memberships buttons to page header

- packages/ui/src/common/components/Activities/Activities.stories.tsx
- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/Activities/ActivityToIconMap.tsx
- packages/ui/src/common/hooks/useActivities.ts
- packages/ui/src/working-groups/components/Activities/OpeningAddedContent.tsx
- packages/ui/src/working-groups/components/Activities/OpeningCanceledContent.tsx
- packages/ui/src/working-groups/components/Activities/WorkerStartedLeavingContent.tsx
- packages/ui/src/working-groups/types/WorkingGroupActivity.ts
> 🧹 Distinguish between Leader and Regular activities

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
- packages/ui/src/common/constants/styles.ts
> ⏱ Fix tooltip show/hide timeout

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
> 🥞 Handle openings stake

- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsTransferableModal.tsx
- packages/ui/src/common/components/Info.tsx
- packages/ui/src/common/components/Stepper.stories.tsx
- packages/ui/src/common/components/Stepper.tsx
- packages/ui/src/common/components/Tooltip/TooltipDefault.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/common/components/typography/Text.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSuccessModal.tsx
> 🦶🏻 Role success step

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
- packages/ui/src/common/components/charts/PercentageChart.tsx
- packages/ui/src/mocks/data/mockOpenings.ts
- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
> 🎪 Show more button in applying modal

- packages/ui/src/app/hooks/usePageTabs.ts
- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/app/pages/WorkingGroups/components/WorkingGroupsTabs.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/memberships/providers/membership/context.tsx
- packages/ui/src/memberships/providers/membership/provider.tsx
- packages/ui/test/membership/hooks/useMyMemberships.test.tsx
- packages/ui/test/working-groups/components/WorkingGroupsTabs.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
- packages/ui/test/working-groups/modals/ChangeAccountModal.test.tsx
- packages/ui/test/working-groups/modals/LeaveRoleModal.test.tsx
> 🙈 Hide Working Groups "My" tabs from non-members

- packages/ui/src/common/components/forms/DatePicker/DatePicker.stories.tsx
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterBox.stories.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterBox.tsx
- packages/ui/src/common/components/forms/TogglableIcon.stories.tsx
- packages/ui/src/common/components/forms/TogglableIcon.tsx
- packages/ui/src/common/components/forms/types.ts
- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/select.stories.tsx
- packages/ui/src/common/utils.ts
- packages/ui/src/mocks/data/mockProposals.ts
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.stories.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
- packages/ui/src/proposals/components/ProposalFilters/index.ts
- packages/ui/src/proposals/types/proposals.ts
> 🧃 Add the Proposals filters component

- packages/ui/src/common/components/forms/TogglableIcon.tsx
> ✨ Toggle icon style

- packages/ui/src/accounts/hooks/useBalance.ts
- packages/ui/src/accounts/hooks/useBalances.ts
- packages/ui/src/accounts/model/toBalances.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/accounts/hooks/useTotalBalances.test.tsx
- packages/ui/test/accounts/model/toBalances.test.ts
> 🧮 Update balances calculation

- packages/ui/package.json
- yarn.lock
> 🧠 Increase Webpack memory limits

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
> 🐽 Display information that no openings found

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
Closes #718 
Was extremely hard to fix 🥸
> 🤕 Change initial openings page to first in history

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
Fix merge error after #728 merge
> ♻️ Fix merge error

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/buttons/FilterButtons.tsx
- packages/ui/src/common/components/forms/Calendar/Calendar.tsx
- packages/ui/src/common/components/forms/Calendar/components.tsx
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
> 🗓 Date picker styling

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRoles.tsx
- packages/ui/src/common/components/ContextMenu/ContextMenu.stories.tsx
- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
- packages/ui/src/common/components/ContextMenu/index.ts
- packages/ui/src/common/components/Tooltip/ContextMenu.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/mocks/data/mockApplications.ts
- packages/ui/src/mocks/data/seedWorkers.ts
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
- packages/ui/src/working-groups/hooks/useWorker.ts
- packages/ui/src/working-groups/modals/ChangeAccountModal/ChangeAccountModal.tsx
- packages/ui/src/working-groups/modals/ChangeAccountModal/index.ts
- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleModal.tsx
- packages/ui/src/working-groups/modals/LeaveRoleModal/types.ts
- packages/ui/test/working-groups/modals/ChangeAccountModal.test.tsx
- packages/ui/test/working-groups/modals/LeaveRoleModal.test.tsx
> 📑 Context menu

- packages/ui/src/mocks/hooks/useMockDelay.ts
> 🔧 Fix mock delay

- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsAccountItem.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsInsufficientBalanceModal.stories.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsInsufficientBalanceModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsLockedModal.stories.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsLockedModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsTransferableModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/constants.ts
- packages/ui/src/accounts/modals/MoveFoundsModal/index.ts
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
* Add new modal in case of insufficient balance
* Refactor move founds modal to meet useHasRequiredStake value
* WorkingGroupsOpenings eslint errors
> 💳 Implement move founds modal on apply for opening

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
We should fix that on project level: #755
> 🎨 Fix MyRole layout

- packages/ui/dev/scripts/generators/generateOpeningsAndApplications.js
- packages/ui/dev/scripts/generators/generateWorkers.js
- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/common/components/Tooltip/Tooltip.tsx
- packages/ui/src/common/components/statistics/MultiTokenValueStat.tsx
- packages/ui/src/common/components/statistics/StakeStat.stories.tsx
- packages/ui/src/common/components/statistics/StakeStat.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/common/components/statistics/TokenValueStat.stories.tsx
- packages/ui/src/common/components/statistics/TokenValueStat.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.stories.tsx
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.stories.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/test/_mocks/server/seeds/index.ts
- packages/ui/test/_mocks/working-groups/workers.ts
- packages/ui/test/working-groups/pages/MyRoles.test.tsx
Closes #713
Closes #666 was already fine
I just opened new PR, it was easier
> 🏉 Implement minimal stake height for my role

- packages/ui/src/working-groups/components/Roles/RolesList.tsx
Closes #710
Just changed badge in this PR
> 🦡 Proper group badge

- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterBox.stories.tsx
- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/select.stories.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/common/components/selects/types.ts
- packages/ui/src/common/utils.ts
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.stories.tsx
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
- packages/ui/src/mocks/components/storybook/MockApolloProvider.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
- packages/ui/src/proposals/components/ProposalFilters/SelectProposer.stories.tsx
- packages/ui/src/proposals/components/ProposalFilters/SelectProposer.tsx
- packages/ui/src/proposals/hooks/useProposers.ts
> 🤵 Implement Proposer Select

- packages/ui/src/common/constants/index.ts
- packages/ui/src/common/constants/numbers.ts
- packages/ui/src/common/model/blocksToTime.ts
- packages/ui/src/common/model/relativeTime.ts
- packages/ui/src/common/model/significantTimeUnit.ts
- packages/ui/src/working-groups/components/NextPayoutStat.tsx
- packages/ui/src/working-groups/model/getNextPayout.ts
- packages/ui/test/common/model/blocksToTime.test.ts
- packages/ui/test/working-groups/model/getNextPayout.test.ts
> 🧅 Add Next Payout component

- packages/ui/src/app/App.tsx
- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
- packages/ui/test/app/pages/Members.test.tsx
> 🐴 Access Member Profile through a link

- packages/ui/src/app/App.tsx
- packages/ui/src/app/Providers.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/hooks/useLocalStorage.ts
- packages/ui/src/common/hooks/useNetwork.ts
- packages/ui/src/common/providers/api/provider.tsx
- packages/ui/test/app/pages/Settings.test.tsx
See #743:
*   added Settings page (simplest scenario)
*   added network switch in the Settings page
> ⚙️ Network switch

- packages/ui/src/mocks/helpers.ts
- packages/ui/src/mocks/resolvers/baseResolvers.ts
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/hooks/useWorkingGroup.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/test/working-groups/components/WorkingGroupListItem.test.tsx
> Count working group openings

- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/selects/components.tsx
> ⭕️ Resolve inputs/selects double border

- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/components/components.tsx
> 👩‍🔧 Fix tooltips triggers styles

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/ApplicantsList.tsx
- packages/ui/src/working-groups/components/Worker.tsx
- packages/ui/src/working-groups/components/WorkersList.stories.tsx
- packages/ui/src/working-groups/components/WorkersList.tsx
- packages/ui/src/working-groups/hooks/useWorkers.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
Closes #715 
Actually this task had a bit bigger scope. Our Worker template was used in applicants list, I handle this as well
> ⛑ Add link to application in workers/applicants list

- packages/ui/src/common/components/Activities/ActivityRouterLink.tsx
- packages/ui/src/common/components/ModalLink.tsx
- packages/ui/src/working-groups/components/Activities/ApplicationWithdrawnContent.tsx
- packages/ui/src/working-groups/components/Activities/AppliedOnOpeningContent.tsx
- packages/ui/src/working-groups/components/Activities/LeaderSetContent.tsx
- packages/ui/src/working-groups/components/Activities/OpeningAddedContent.tsx
- packages/ui/src/working-groups/components/Activities/OpeningCanceledContent.tsx
- packages/ui/src/working-groups/components/Activities/StatusTextChangedContent.tsx
- packages/ui/src/working-groups/components/Worker.tsx
- packages/ui/src/working-groups/hooks/useWorkingGroup.ts
> 👟 Activities link restyle

- packages/ui/src/working-groups/components/WorkersList.tsx
- packages/ui/src/working-groups/components/WorkersTableList/WorkersTableList.tsx
- packages/ui/src/working-groups/hooks/useOpenings.ts
- packages/ui/src/working-groups/hooks/useWorkers.ts
- packages/ui/src/working-groups/types/Worker.ts
In this PR, I have refactored and improved code readability due to previous PR and a bit more
> 🥥 Improve code readability for useWorkers and useOpenings

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
> 🪙 Show only active workers in WG openings

- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/hooks/useCountOpenings.ts
- packages/ui/src/working-groups/hooks/useCountWorkers.ts
- packages/ui/src/working-groups/hooks/useWorkingGroup.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/test/working-groups/components/WorkingGroupListItem.test.tsx
> 🐸  Count working group workers

- packages/ui/src/mocks/components/storybook/MockApolloProvider.tsx
- packages/ui/src/proposals/components/ProposalFilters/SelectProposer.stories.tsx
> Fix the `<MockApolloProvider />` used in storybook

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/index.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/model/workingGroupName.ts
- packages/ui/test/app/pages/WorkingGroup.test.tsx
- packages/ui/test/working-groups/model/workingGroupName.test.ts
> 🪡 Map Working Group name to URL param

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/working-groups/components/WorkersTableList/WorkersTableList.tsx
- packages/ui/src/working-groups/hooks/useWorkers.ts
- packages/ui/src/working-groups/hooks/useWorkersPagination.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
Closes #795 
Also fixed Eslint warning in `PageContent.tsx`
> 🎰 Add pagination for WG past workers

- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/icons/CalendarIcon.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
> 📚 Inputs with smaller height prop

- packages/ui/src/common/components/forms/FilterBox/FilterBox.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
> 🧽 Fix proposals filter box

- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.stories.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
- packages/ui/src/proposals/hooks/usePastProposals.ts
> 🤴 Add the `<SelectProposer />` to `<ProposalFilters />`

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/working-groups/hooks/useGroupDebt.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
This PR together with #818 close #415
I've done counting debt only for active workers, because later we can just add leaving status to our WHERE
> 🫁 Implement WG debt

- packages/ui/src/common/components/ContextMenu/ContextMenu.stories.tsx
- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/hooks/useOutsideClick.ts
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
> 📻 Close context menu on action select

- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/common/components/selects/MultiSelect.tsx
- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/components.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/common/components/selects/types.ts
- packages/ui/src/common/constants/styles.ts
- packages/ui/src/common/utils.ts
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.stories.tsx
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
- packages/ui/src/memberships/components/SelectMemberRoles/SelectMemberRoles.stories.tsx
- packages/ui/src/memberships/components/SelectMemberRoles/SelectMemberRoles.tsx
- packages/ui/src/memberships/components/SelectMemberRoles/index.ts
- packages/ui/src/memberships/hooks/useAllMemberRoles.ts
- packages/ui/test/common/utils/utils.test.ts
> Select member roles

- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/types.ts
- packages/ui/src/proposals/components/ProposalFilters/SelectProposer.tsx
> 🔧 Fix the `<SelectProposer />` option selection

- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/common/components/Tabs.tsx
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterBox.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterLabel.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/page/Sidebar/Navigation.tsx
- packages/ui/src/common/components/selects/MultiSelect.tsx
- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/components.tsx
- packages/ui/src/common/components/selects/select.stories.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- yarn.lock
> 🎍 Selects restyle

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/proposals/components/AddProposalButton.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/index.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🦅 Introduce new proposal modal

- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/common/components/Info.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalWarningModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/index.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> ☄️ Handle warning in add proposal modal

- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
- packages/ui/src/common/components/Notifications/Notifications.stories.tsx
- packages/ui/src/common/components/Notifications/Notifications.tsx
- packages/ui/src/common/components/Notifications/NotificationsButton.tsx
- packages/ui/src/common/components/Notifications/NotificationsPanel.tsx
- packages/ui/src/common/components/Notifications/index.ts
- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/Breadcrumbs.tsx
- packages/ui/src/common/hooks/useOutsideClick.ts
See #851 
Please understand that the mere awareness of CSS existing makes me go to sleep with the lights on
> 🌫 Add a Notifications panel

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/components/BadgeStatus/BadgesRow.ts
- packages/ui/src/common/constants/dates.ts
- packages/ui/src/common/constants/index.ts
- packages/ui/src/common/model/formatters.ts
- packages/ui/src/common/types/helpers.ts
- packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.stories.tsx
- packages/ui/src/proposals/hooks/useBlocksToProposalExecution.ts
- packages/ui/src/proposals/types/proposals.ts
- packages/ui/test/common/model/formatters.test.ts
> ⏱️ Add the "Time left" bit of the Proposal page

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.stories.tsx
- packages/ui/src/proposals/components/RationalePreview/RationalePreview.stories.tsx
- packages/ui/src/proposals/components/RationalePreview/RationalePreview.tsx
- packages/ui/src/proposals/components/RationalePreview/index.ts
- packages/ui/src/proposals/types/proposals.ts
> 🔭 Implement the proposal page rationale part

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
I just noticed it wasn't there yet while looking at something else, and it could be added easily
> 🍄 Add Next Payout stat to Worker Role page

- packages/ui/src/common/components/Progress/ProgressBar.stories.tsx
- packages/ui/src/common/components/Progress/ProgressBar.tsx
- packages/ui/src/common/components/Progress/index.ts
- packages/ui/src/common/components/statistics/FractionValue.tsx
- packages/ui/src/common/components/statistics/NumericValueStat.tsx
- packages/ui/src/common/components/statistics/StatisticBar.stories.tsx
- packages/ui/src/common/components/statistics/StatisticBar.tsx
- packages/ui/src/common/components/statistics/StatisticHeader.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/common/components/statistics/Statistics.stories.tsx
- packages/ui/src/common/components/statistics/TokenValueStat.tsx
- packages/ui/src/common/components/statistics/index.tsx
- packages/ui/src/common/components/storybookParts/previewStyles.tsx
See #866
(Reuse and refactor some code from #671)
> 🍫 Implement the StatisticBar component

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/components/storybookParts/previewStyles.tsx
- packages/ui/src/common/hooks/useCouncilSize.ts
- packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.stories.tsx
- packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.tsx
- packages/ui/src/proposals/components/StatisticsPreview/index.tsx
- packages/ui/src/proposals/hooks/useBlocksToProposalExecution.ts
- packages/ui/src/proposals/hooks/useVoteCount.ts
- packages/ui/src/proposals/types/index.ts
- packages/ui/test/proposals/hooks/useVoteCount.test.ts
> 📊 Implement a `<ProposalStatistics />` component

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/StakingAccountStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🐝 Handle required stake and staking account in add proposal modal

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/CKEditor/index.ts
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalDetailsStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/test/_mocks/components/CKEditor.tsx
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🥋 Handle proposal details step in new proposal

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalDetailsStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.tsx
> 💎 Show "How to rationale" modal together with main modal

- packages/ui/src/accounts/components/AccountLocks.stories.tsx
- packages/ui/src/accounts/components/AccountLocks.tsx
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/accounts/model/toBalances.ts
- packages/ui/src/accounts/types/balances.ts
- packages/ui/src/app/pages/Profile/MyAccounts.tsx
- packages/ui/src/app/pages/Profile/components/AccountItem.tsx
- packages/ui/test/_mocks/chainTypes.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/accounts/hooks/useMyTotalBalances.test.tsx
- packages/ui/test/accounts/model/toBalances.test.ts
- packages/ui/test/app/pages/MyProfile/MyAccounts.test.tsx
Display recoverable balances – see #790:
*   fix balance locks handling
*   display recoverable locks in the UI
> 🚑 Display recoverable balances

- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalTypeStep.tsx
> 📚 CKEditor styles fixes

- packages/ui/src/common/components/selects/SimpleSelect.tsx
> Fix simpleSelect states styles

- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/common/components/page/Sidebar/Navigation.tsx
> 🪤 Scrollable sidebar menu

- packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
- packages/ui/src/accounts/components/SelectAccount/helpers.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/StakingAccountStep.tsx
- yarn.lock
> 🤑 Filter accounts by compatible balance for the stake step

- packages/ui/dev/mocks/lib/api.ts
- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
> 🧑‍🏫 Show better errors in console

- packages/ui/src/proposals/hooks/useProposals.ts
> 🔧 Fix the `useProposals` status filter

- packages/ui/dev/mocks/commands/transfer.ts
- packages/ui/dev/mocks/index.ts
- packages/ui/dev/mocks/lib/options.ts
> 💸 Add transfer tokens command

- packages/ui/src/proposals/components/RationalePreview/RationalePreview.tsx
> ䷟ Fix rationale item title and layout

- packages/ui/jest.config.ts
- packages/ui/src/common/components/BadgeStatus/BadgeStatus.ts
- packages/ui/src/common/components/List/List.tsx
- packages/ui/src/common/components/typography/Subscription.tsx
- packages/ui/src/common/hooks/useActivities.ts
- packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
- packages/ui/src/proposals/constants/styles.ts
- packages/ui/src/working-groups/components/Activities/OpeningAnnouncedContent.tsx
- packages/ui/test/app/pages/ProposalPreview.test.tsx
> ⅊ Update proposals items

- packages/ui/src/memberships/components/components.tsx
- packages/ui/src/proposals/components/VotesPreview/VotePreview.tsx
- packages/ui/src/proposals/components/VotesPreview/VotesPreview.tsx
> 🗳 Fix voting block items

- packages/ui/src/common/components/forms/ToggleCheckbox.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
> 🧼 Styles for selected proposals type items

- packages/ui/src/working-groups/hooks/useMyRoleIds.ts
> 🪝 Fix hooks usage in useMyRoleIds()

- packages/ui/src/common/components/Activities/Activities.tsx
- packages/ui/src/common/components/Activities/ActivitiesBlock.tsx
- packages/ui/src/common/components/Activities/ActivityComponent.tsx
- packages/ui/src/common/components/Notification.tsx
- packages/ui/src/common/components/Notifications/Notifications.tsx
- packages/ui/src/common/components/Notifications/NotificationsButton.tsx
- packages/ui/src/common/components/Notifications/UnreadNotificationIndicator.tsx
- packages/ui/src/common/components/page/SidePanel.tsx
- packages/ui/src/common/constants/animations.ts
- packages/ui/src/common/types/Activity.ts
> 👹 Unread activities state + indicator component

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
> ⬅️ Restyle previous button

- .eslintrc.json
- packages/ui/package.json
- yarn.lock
Closes #972 
The plugin also includes a ruleset for ensuring that all variables present in Effect/Memo hooks are included in the dependencies list, but I'd opt for discussing it before including it, for interesting reasons.
> 🤌 Add rules of hooks ESLint plugin

- packages/ui/src/common/hooks/useNumberInput.ts
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/FundingRequest.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/index.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- yarn.lock
> 🏧 Add proposal funding request

- packages/ui/src/common/model/machines/getSteps.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/CreateWorkingGroupLeadOpening.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
- packages/ui/test/common/model/machines/getSteps.test.ts
Initial work for #873.
I've changed a bit how we handle specific parameters to allow nesting multiple different steps.
> 🤹 Add working group lead opening proposal

- packages/ui/src/working-groups/components/OpeningsList/OpeningsPagination.tsx
> 🕘 WG history tab past openings list styles

- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/common/components/Notifications/NotificationsButton.tsx
> 🔔 Change notifications button styles

- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/common/components/List/List.tsx
- packages/ui/src/common/components/icons/Loader.tsx
- packages/ui/src/common/components/icons/SearchProcessIcon.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/common/components/page/SearchProcess.tsx
- packages/ui/src/common/components/page/SidePanel.tsx
> 🔍 Searching process window

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SignTransactionModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
> Handle proposal sign & send transaction

- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionWorkingGroup.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionsListWorkingGroup.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.stories.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/index.ts
Required for #873 
In the wire frames: https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=232%3A796
> 🧺 Add select working group component

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/components/ProposalPreview/CreateLeadOpeningDetailsComponent.tsx
- packages/ui/src/proposals/components/ProposalPreview/ProposalProperties.stories.tsx
- packages/ui/src/proposals/components/ProposalPreview/ProposalProperties.tsx
Closes #803 
Also added storybook entries for viewing convenience
> 🍙 Add Description preview to Lead Opening proposal preview

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/CreateWorkingGroupLeadOpening.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/CreateWorkingGroupLeadOpening.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.stories.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
> 🥓 Working group and opening details step

- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/common/components/statistics/Statistics.tsx
- packages/ui/src/proposals/components/ProposalPreview/FundingRequestDetailsComponent.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningDetails.tsx
> 🔲 Upgrade statistics

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/statistics/StatisticButton.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/common/components/statistics/Statistics.tsx
- packages/ui/src/proposals/components/ProposalPreview/FundingRequestDetailsComponent.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningDetails.tsx
> 🔳 Statistic button

- packages/ui/src/common/hooks/useBlockInput.ts
- packages/ui/test/common/hooks/useBlockInput.test.ts
- packages/ui/test/setup.ts
> 🏗 Add useBlockInput hook

- packages/ui/package.json
- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/CKEditor/MarkdownEditor.js
- packages/ui/src/common/components/Forum/ForumComment.stories.tsx
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.stories.tsx
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
- packages/ui/src/common/utils.ts
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
- packages/ui/test/app/pages/ProposalPreview.test.tsx
- packages/ui/test/common/utils/utils.test.ts
- yarn.lock
> ✍️ Add the discussion comment box with mention support

- packages/ui/src/common/components/selects/components.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/common/components/selects/types.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionWorkingGroup.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
> Working group select styles

- packages/ui/src/common/hooks/useNumberInput.ts
- packages/ui/test/common/hooks/useNumberInput.test.ts
> 🦃 Allow initial BN in useNumberInput

- packages/ui/src/common/components/Activities/Activities.stories.tsx
- packages/ui/src/working-groups/components/Activities/WorkerStartedLeavingContent.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupActivity/casts.ts
- packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
> 🥎 Change "Worker Started Leaving" activity text

- packages/ui/dev/scripts/generators/generateProposals.ts
- packages/ui/dev/scripts/generators/utils.ts
Re-rolling mocks is a pointless activity that doesn't engender personal growth
> 🧠 Ensure all proposal types are generated

- packages/ui/src/common/helpers.ts
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🧪 Add tests for Funding Request and Transaction

- packages/ui/package.json
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
- yarn.lock
> 🚀 Handle runtime upgrade proposal creation

- packages/ui/src/common/model/machines/getSteps.ts
- packages/ui/test/common/model/machines/getSteps.test.ts
> 👣 Stepper fix

- packages/ui/src/common/components/List/List.stories.tsx
- packages/ui/src/common/components/List/List.tsx
- packages/ui/src/common/components/List/ListHeader.tsx
- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/common/components/page/Sidebar/NavigationLink.tsx
- packages/ui/src/common/types/helpers.ts
- packages/ui/src/memberships/components/MemberList/Members.tsx
- packages/ui/src/memberships/components/MembersSection.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
> 🧹 Fix proposal pages browser console errors

- packages/ui/src/common/components/selects/SimpleSelect.tsx
> 🏢 Limit select options height

- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
> 🕧 Datepicker empty state placeholder

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> ⬅️ Move 'previous step' button to the left side

- packages/ui/src/proposals/components/ProposalPreview/LeadStakeComponent.tsx
- packages/ui/src/proposals/components/ProposalPreview/RuntimeUpgradeComponent.tsx
> 😕 Fixes in statistic elements content

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.tsx
> 💧 Add dropzone styles

- packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
> 🧬 Fix toggles for trigger & discussion

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/components/BadgeStatus/BadgeStatus.ts
- packages/ui/src/proposals/components/ProposalStages.tsx
- packages/ui/src/proposals/components/VotesPreview/VotesPreview.stories.tsx
- packages/ui/src/proposals/hooks/useVotingRounds.ts
- packages/ui/test/proposals/hooks/useVotingRounds.test.ts
Closes #1035 
Closes #1037
See #801
> 👀 Show Proposal outcome more clearly on the proposal page

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SlashWorkingGroupLead.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
> 🤺 Handle slash working group lead

- packages/ui/src/proposals/components/ProposalStages.tsx
Sorry about that, my IDE was hanging yesterday and I didn't realize this had not been staged my commit
> 🪛 Fix deciding proposals voting stage tab

- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/common/components/page/Sidebar/NavigationLink.tsx
> 🙄 Adjust sidebar links

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.stories.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.tsx
- packages/ui/src/common/components/statistics/FractionValue.tsx
- packages/ui/src/common/components/statistics/StatisticBar.tsx
- packages/ui/src/common/constants/dates.ts
- packages/ui/src/common/model/formatters.ts
> 🔧 Fix the Opening statistic mismatch

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.tsx
> 🤓 Validate wasm file and change typo

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/hooks/useVotingRounds.ts
- packages/ui/test/proposals/hooks/useVotingRounds.test.ts
> 🛠️ Render proposals which have never been Deciding

- packages/ui/src/common/components/Stepper/Stepper.tsx
> 🧑‍⚖️ Match the case of the proposal history stages

- packages/ui/src/mocks/resolvers/baseResolvers.ts
> 🔒 Show closed WorkingGroupOpening only in history tab

- packages/ui/src/app/pages/WorkingGroups/UpcomingOpening.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.stories.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.tsx
> 🔨 Fix Upcoming Opening statistic mismatch

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/test/working-groups/pages/MyRoles.test.tsx
> 🍒 Change My Role content when not viewed by role owner

- packages/ui/test/forum/pages/ForumThread.test.tsx
> 🧶 Handle simple test for thread page

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/index.ts
- packages/ui/src/forum/modals/CreateThreadModal/machine.ts
- packages/ui/src/forum/modals/CreateThreadModal/stories/CreateThreadModal.stories.tsx
- packages/ui/test/forum/modals/CreateThreadModal.test.tsx
Closes #1069 
I'm not too familiar with xstate so I wouldn't mind a closer review on that, as well as the look of modal in general
> 🥦 Add first step of Create Thread modal

- packages/ui/src/working-groups/constants.ts
> 🟣 Fill empty badge status

- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
> 🚛 Increase members filter box title font size

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.tsx
> 🅱️ Handle multiple files/errors validation

- packages/ui/dev/scripts/generators/generateProposals.ts
- packages/ui/src/common/components/typography/Text.tsx
- packages/ui/src/forum/components/ForumComment/ForumComment.stories.tsx
- packages/ui/src/forum/components/category/CategoryListItem.stories.tsx
- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/category/PostInfo.tsx
- packages/ui/src/forum/components/category/ThreadInfo.tsx
- packages/ui/src/forum/components/category/index.ts
- packages/ui/src/forum/constant/index.ts
- packages/ui/src/forum/constant/routes.ts
- packages/ui/src/forum/constant/styles.ts
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/forum/types/ForumPost.ts
- packages/ui/src/forum/types/ForumThread.ts
- packages/ui/src/memberships/components/Avatar.tsx
- packages/ui/src/memberships/components/MemberStack/MemberStack.stories.tsx
- packages/ui/src/memberships/components/MemberStack/MemberStack.tsx
- packages/ui/src/memberships/components/MemberStack/index.ts
- packages/ui/src/mocks/data/raw/proposals.json
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/ProposalWithDetails.ts
> 🛍️ Implement the CategoryListItem component

- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalTypeStep.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionWorkingGroup.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionsListWorkingGroup.tsx
> 🚭 Show extra text for disabled WG option with no lead

- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/common/components/selects/types.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
- packages/ui/test/_helpers/selectAccount.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🤖 Create Working Group Lead Opening Proposal tests

- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/PreviewThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/stories/CreateThreadDetailsModal.stories.tsx
- packages/ui/src/forum/modals/CreateThreadModal/stories/PreviewThreadModal.stories.tsx
> 🥧 Add a Create Thread Preview

- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/modals/TransactionModal/MultiTransactionModal.stories.tsx
- packages/ui/src/common/modals/TransactionModal/MultiTransactionModalHeader.tsx
- packages/ui/src/common/modals/TransactionModal/MultiTransactionStep.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> Multitransaction header content + styling

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadSignModal.tsx
It's a bit ugly but the page is under construction anyway.
Also swatted some issues that weren't immediately apparent in tests
> 🎻 Add Create Thread modal to Categories page

- packages/ui/package.json
- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/CKEditor/MarkdownEditor.d.ts
- packages/ui/src/common/components/CKEditor/MarkdownEditor.js
- yarn.lock
> 🧀 Add an inline markdown editor

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/components/buttons/CopyButton.tsx
- packages/ui/src/common/components/icons/symbols/FailureSymbol.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
> ✅/❌  Show copy result by custom copy button

- packages/ui/src/app/hooks/usePageTabs.ts
- packages/ui/src/app/pages/Forum/ForumCategories.tsx
- packages/ui/src/app/pages/Forum/components/ForumTabs.tsx
- packages/ui/src/forum/hooks/useForumCategories.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/mocks/data/seedForum.ts
- packages/ui/src/mocks/resolvers/baseResolvers.ts
- packages/ui/src/mocks/server.ts
> 🕴️ Filter the Forum Categories result by parent id

- packages/ui/src/forum/components/category/CategoryListItem.stories.tsx
- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/category/storybook-helpers.ts
- packages/ui/src/forum/hooks/useForumCategories.ts
- packages/ui/src/forum/hooks/useForumSubcategories.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/mocks/data/seedForum.ts
- packages/ui/src/mocks/resolvers/baseResolvers.ts
- packages/ui/src/mocks/server.ts
Closes #1191 
See [#1188](https://github.com/Joystream/pioneer/pull/1188#discussion_r684318348)
> 🔧 Fix the `forumcategoryparent` field

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Forum/Forum.tsx
- packages/ui/src/app/pages/Forum/ForumCategories.tsx
- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/app/pages/Forum/components/ForumTabs.tsx
- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/constant/routes.ts
- packages/ui/src/forum/hooks/useForumCategories.ts
- packages/ui/src/forum/hooks/useForumCategory.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/forum/types/ForumCategoryWithDetails.ts
- packages/ui/src/memberships/components/MemberStack/MemberStack.tsx
- packages/ui/src/mocks/server.ts
Still requires #1196 and #1197 to complete #1058
> 🎩 Implement the top part of the category page

- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
> ✍🏻 Fix edition time styles

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/components/threads/ThreadList.stories.tsx
- packages/ui/src/forum/components/threads/ThreadList.tsx
- packages/ui/src/forum/components/threads/ThreadListItem.stories.tsx
- packages/ui/src/forum/helpers/storybook.ts
> 🧶 Implement the `<ThreadList />` component

- .github/workflows/CI.yml
- package.json
- packages/ui/package.json
It seems to work (at least right now), let's see if we get no hiccups over the week
> 🍭 Add a memory constraint to CI tests

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
> 🤢 Remove tooltip delay

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/forum/types/ForumCategoryWithDetails.ts
- packages/ui/src/forum/types/index.ts
> 📜 View Archived Category Page 

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
Closes #1077 
This also hides reactions to a post, but they aren't completely implemented yet, so they probably will be moved around some more in near future
> 🛹 Hide post options in archived threads

- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadSignModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/utils.ts
- packages/ui/test/forum/modals/CreateThreadModal.test.tsx
> 🔌 Add minimum fee requirement to Create Thread modal

- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberListItem/Member.tsx
- packages/ui/src/memberships/components/MemberListItem/MyMember.tsx
- packages/ui/src/memberships/components/components.tsx
- packages/ui/src/memberships/components/types.ts
- packages/ui/src/memberships/modals/BindStakingAccountModal/BindStakingAccountModal.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSuccessModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberSuccessModal.tsx
- packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteSuccessModal.tsx
- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipSuccessModal.tsx
- packages/ui/src/proposals/components/ProposalPreview/LeadStakeComponent.tsx
> 👤 Member info clickable

- packages/ui/src/app/pages/Members/Members.tsx
> 🕵️ Fix member search

- packages/ui/src/forum/components/category/CategoryListItem.stories.tsx
- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/category/ForumCategoryList.stories.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/forum/types/ForumCategoryWithDetails.ts
- packages/ui/src/mocks/components/storybook/MockApolloProvider.tsx
> 🔧 Fix and filter `<CategoryListItem />` subcategory links

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/hooks/useRouteQuery.ts
- packages/ui/src/common/types/index.ts
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/modals/CreateThreadModal/PreviewThreadModal.tsx
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
> 🖇 Handle scroll to post by link

- packages/ui/src/app/pages/Forum/Forum.tsx
- packages/ui/src/app/pages/Forum/ForumMyThreads.tsx
- packages/ui/src/forum/hooks/useForumCategoryThreads.ts
- packages/ui/src/forum/hooks/useForumMyThreads.ts
- packages/ui/src/forum/hooks/useMyThreads.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/mocks/data/raw/forumPosts.json
- packages/ui/src/mocks/data/raw/forumThreads.json
> ⛏ Handle my threads hook and page

- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/category/ThreadCount.tsx
- packages/ui/src/forum/hooks/useForumCategoryThreadCount.ts
> 🫖 Account for status in category item threads count

- packages/ui/src/accounts/components/TransferButton.tsx
- packages/ui/src/app/pages/Profile/components/AccountItem.tsx
- packages/ui/src/app/pages/Profile/components/Accounts.tsx
- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
- packages/ui/src/common/components/List/List.tsx
- packages/ui/src/memberships/components/EditMembershipButton.tsx
- packages/ui/src/memberships/components/MemberList/Members.tsx
- packages/ui/src/memberships/components/MemberListItem/Fileds.tsx
- packages/ui/src/memberships/components/MemberListItem/Member.tsx
- packages/ui/src/memberships/components/MemberListItem/MyMember.tsx
- packages/ui/src/memberships/components/MembersSection.tsx
- packages/ui/src/memberships/components/TransferInviteButton.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/Opening.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/components/OpeningsList/OpeningsListRow.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpening.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningListItem.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
- packages/ui/src/working-groups/components/ToggleableItemStyledComponents.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/components/WorkingGroupsList.tsx
Closes #1287 
Closes #1292  
Closes #1293  
Closes #1294 
Closes #1295  
Closes #1296 
Closes #1313
> 🎳 Whole WG item is clickable link

- packages/ui/src/common/components/selects/SimpleSelect.tsx
Closes #1311 
[@figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=2985%3A111662)
> Show half of last select option

- packages/ui/src/memberships/components/Avatar.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
[@figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=2599%3A109614)
Closes #1319
> Update member size and content in proposal item

- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
- packages/ui/src/common/components/buttons/Buttons.tsx
- packages/ui/src/common/components/buttons/CopyButton.tsx
- packages/ui/src/forum/components/PostList/PostContextMenu.tsx
- packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/components/threads/LikeButton.tsx
- packages/ui/src/forum/modals/CreateThreadModal/PreviewThreadModal.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumPost.ts
- packages/ui/src/proposals/types/ProposalWithDetails.ts
- packages/ui/test/forum/components/PostEditor.test.tsx
- packages/ui/test/forum/components/PostListItem.test.tsx
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
For the longest time I had no idea how to test these buttons because they have no text in them, but then I found out I can add titles to them, which I think we should be doing anyway for the sake of accessibility
> 🦻 Factor in post status when displaying options

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberStack/MemberStack.tsx
> 🎫 Member info list from remaining list

- packages/ui/src/forum/components/threads/LatestActivity.tsx
- packages/ui/src/forum/components/threads/ThreadListItem.tsx
> 🔝 Align to top thread list item content

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/common/components/BadgeStatus/BadgesRow.ts
> 🏷🗺 Remove tag placeholder from thread. Add thread tags maps

- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/test/forum/components/PostListItem.test.tsx
> 💔 Remove like button from thread posts

- packages/ui/src/forum/components/threads/ThreadFilters.tsx
> 🧹 Remove tags select from thread filter

- packages/ui/src/app/pages/Forum/ForumOverview.tsx
> 🍗 Remove participated polls block

- packages/ui/src/forum/components/threads/ThreadItem.tsx
> 💬 Thread link from overview

- packages/ui/src/forum/components/threads/ThreadList.tsx
- packages/ui/src/forum/components/threads/ThreadListItem.tsx
- packages/ui/src/forum/constant/styles.ts
> 🗳 Remove voter column from threads

- packages/ui/src/common/components/Search/HighlightedText.tsx
- packages/ui/src/common/components/Search/SearchResultItem.tsx
> 🕵🏻‍♂️ Fix search result text styles

- packages/ui/src/app/pages/Forum/components/ForumTabs.tsx
- packages/ui/src/forum/constant/routes.ts
> 🚰 Remove tags tab

- packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
> 🗓␛ Close datepicker on escape click

- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/Search/SearchResultsModal.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
- packages/ui/src/proposals/components/ProposalPreview/CreateLeadOpeningDetailsComponent.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.tsx
- packages/ui/src/proposals/modals/VoteRationale/VoteRationale.tsx
- packages/ui/src/working-groups/components/Activities/ActivitiesModals/StakeChanged/StakeChangedModal.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/ApplicationDetailsModal.tsx
> 🪟␛ Close modals on escape button

- packages/ui/src/forum/components/threads/ThreadItem.tsx
See #1062 
Thread breadcrumbs sometimes don't fit in there - mostly in suggested threads - this could be addressed in a follow-up, though I'm not sure what's the best way to do it
> 🍔 Display thread overview details

- packages/ui/src/proposals/components/ProposalPreview/RuntimeUpgradeComponent.tsx
> 🐛 Fix content jumping in 'Download wasm file' button

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/src/forum/components/Thread/ThreadNewPost.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/index.ts
- packages/ui/test/forum/components/NewThreadPost.test.tsx
- packages/ui/test/forum/modals/CreatePostModal.test.tsx
Closes #1317
This is a version that creates a locked (non-editable) post. Handling editable posts to be done in a follow-up, and we'll probably need a design for a modal step that explains what this does and what the post deposit is for.
Issue for an editable post can be found here: #1341
> 🦈 Create a post in thread

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/hooks/useLocation.ts
- packages/ui/src/common/types/helpers.ts
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/hooks/useForumThreadPosts.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
- packages/ui/test/forum/hooks/useForumThreadPosts.test.ts
- packages/ui/test/forum/pages/ForumThread.test.tsx
> ⛓️ Link to any post from its id and thread id 

- packages/ui/src/app/pages/Forum/ForumOverview.tsx
- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/common/hooks/useLocalStorage.ts
- packages/ui/src/forum/components/Thread/WatchlistButton.tsx
- packages/ui/src/forum/components/threads/RandomThreadsBrowser.tsx
- packages/ui/src/forum/components/threads/ThreadBrowser.tsx
- packages/ui/src/forum/components/threads/WatchlistThreadsBrowser.tsx
- packages/ui/src/forum/constant/index.ts
- packages/ui/src/forum/constant/localStorageKeys.ts
- packages/ui/src/forum/hooks/useWatchlistedThreads.ts
- packages/ui/test/_mocks/forum/threads.ts
- packages/ui/test/forum/components/ForumBreadcrumbs.test.tsx
- packages/ui/test/forum/components/WatchlistButton.test.tsx
- packages/ui/test/forum/components/WatchlistThreadsBrowser.test.tsx
See #1057 
Also updated `useLocalStorage` a bit. Item type can now be any type (because there's `JSON.stringify`/`parse` in there anyway) and the returned type is now `<T | undefined>` (TS didn't notice this, but `window.localStorage.getItem()` returns undefined if the key isn't there, and it's better to state that explicitly so it doesn't surprise us later)
> ⌚️ Add forum watchlist

- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.stories.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
- packages/ui/src/forum/modals/PostActionModal/DeletePostModal/DeletePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/index.ts
- packages/ui/src/forum/modals/PostActionModal/PostActionSignModal.tsx
- packages/ui/src/forum/modals/PreviewPostModal/PreviewPostModal.stories.tsx
- packages/ui/src/forum/modals/PreviewPostModal/PreviewPostModal.tsx
- packages/ui/src/mocks/data/raw/forumPosts.json
- packages/ui/src/mocks/data/raw/forumThreads.json
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
> 🏎 Add post edit preview and refactor edit/delete modals

- packages/ui/src/mocks/resolvers/baseResolvers.ts
> 🪛 Fix the root categories and archived query MirageJS result

- packages/ui/src/common/components/selects/SimpleSelect.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
- packages/ui/test/accounts/components/SelectAccount.test.tsx
> ☔️ Close roles dropdown only on apply button

- packages/ui/src/common/components/selects/MultiSelect.tsx
- packages/ui/src/common/components/statistics/DurationStatistics.tsx
- packages/ui/src/common/utils.ts
- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/threads/ThreadItem.tsx
- packages/ui/src/forum/components/threads/ThreadListItem.tsx
- packages/ui/test/common/utils/utils.test.ts
> 🧽 Cleanup React warnings

- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningListItem.tsx
> 🆔 Hide long working group ID

- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
Closes #1363 
Follow-ups: #1088 #1427
> 🐸 Use ForumPostMetadata for create/edit posts

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
> ⚗️ Fix tooltips 'end' position after API upgrade

- packages/ui/src/common/components/Search/SearchResultsModal.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/forum/components/threads/ThreadItem.tsx
- packages/ui/src/forum/components/threads/ThreadItemBreadcrumbs.tsx
> 🥨 Reuse the search result breadcrumbs in ThreadItem

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
- packages/ui/src/common/components/BadgeStatus/BadgeStatus.ts
- packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
- packages/ui/src/proposals/constants/styles.ts
> 🛹 Fix long badges cut

- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
> 🔦 Longer post highlight animation

- packages/ui/src/common/components/Tabs.tsx
> 🟣 Indicator for tab inner changes

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/constants/breadcrumbs.ts
- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/app/pages/Council/Election.tsx
- packages/ui/src/app/pages/Council/PastCouncils.tsx
- packages/ui/src/app/pages/Council/PastElections.tsx
- packages/ui/src/app/pages/Council/PastVotes.tsx
- packages/ui/src/app/pages/Council/components/CouncilTabs.tsx
- packages/ui/src/council/constants/index.ts
- packages/ui/src/council/constants/routes.ts
> 🌱 Add council base routes and pages

- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadSignModal.tsx
- packages/ui/test/forum/modals/CreateThreadModal.test.tsx
> 🧄 Factor in thread and post deposit in thread creation

- packages/ui/src/common/api/schemas/schema.graphql
Added the recent updates to the schema.
See #1431
> Update schema with isVisible filters

- packages/ui/src/mocks/data/seedProposals.ts
- packages/ui/src/proposals/hooks/useProposals.ts
> 🧑‍⚖️ Use isFinalized field to fetch proposals

- packages/ui/src/app/pages/Forum/ForumMyThreads.tsx
- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/common/components/Pagination/Pagination.tsx
- packages/ui/src/forum/components/PostList/PostList.tsx
> 🙈 Hide pagination component when there's only one page

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/forum/hooks/useForumThreadPosts.ts
- packages/ui/src/forum/hooks/useThreadLatestPost.ts
- packages/ui/src/forum/types/ForumPost.ts
- packages/ui/src/mocks/data/seedForum.ts
- packages/ui/test/forum/hooks/useForumThreadPosts.test.ts
> 👓 Use the isVisible field to fetch posts

- packages/ui/src/common/components/Search/SearchResultItem.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/forum/components/threads/ThreadItem.stories.tsx
- packages/ui/src/forum/components/threads/ThreadItemBreadcrumbs.tsx
- packages/ui/test/forum/components/ThreadItemBreadcrumbs.test.tsx
> 🥖 Keep the thread item breadcrumbs on one line

- packages/ui/src/app/pages/Forum/ForumArchived.tsx
- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/app/pages/Forum/ForumMyThreads.tsx
- packages/ui/src/forum/components/threads/ThreadList.tsx
- packages/ui/src/forum/constant/index.ts
- packages/ui/src/forum/constant/pagination.ts
- packages/ui/src/forum/hooks/useForumCategoryThreads.ts
- packages/ui/src/forum/hooks/useForumThreadPosts.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/test/forum/hooks/useForumCategoryThreads.test.ts
Closes #1458 
I've done pagination for archived page. Now we can use this pagination for each place where we need it. I think we also need it in category page.
> 📄 Handle optional pagination for threads hook

- packages/ui/src/common/utils.ts
- packages/ui/src/forum/components/threads/ThreadItemBreadcrumbs.tsx
Sorry I was done with this but then I realized the behavior was sometime strange whenever the window would resize
> 🗜️ Fix the thread item breadcrumbs expanding on resize

- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
- packages/ui/src/memberships/hooks/useIsMyMembership.ts
> 🎟️ Hide the "transfer invites" button of other users

- packages/ui/src/forum/components/PostList/PostEditor.tsx
Closes #1463 
As it turns out, the edited text was missing from the memo deps list.
I opted to use `useCallback` instead, as to not render too many hooks too often
> 🦇 Pass correct transaction parameters in Edit Post

- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
- packages/ui/src/common/modals/TransactionModal/TransactionModal.tsx
- packages/ui/src/common/model/machines/transaction.ts
- packages/ui/test/common/model/machines/transactionMachine.test.tsx
> 👨🏼‍🔧 Fix transaction flow when using Polkadot extension

- packages/ui/src/common/modals/TransactionModal/TransactionModal.tsx
- packages/ui/src/common/model/machines/transaction.ts
- packages/ui/test/common/model/machines/transactionMachine.test.tsx
> 🔐 Show transaction error modal when Polkadot extension is closed

- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
- packages/ui/src/memberships/components/MemberRoles.stories.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/hooks/useAllMemberRoles.ts
- packages/ui/src/memberships/hooks/useMemberExtraInfo.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/memberships/types/Member.ts
- packages/ui/src/memberships/types/casting.ts
- packages/ui/test/membership/helpers.test.ts
> 🕵️ Show missing member info exept for "Being a council"

- packages/ui/src/common/components/Progress/ProgressBar.stories.tsx
- packages/ui/src/common/components/Progress/ProgressBar.tsx
- packages/ui/src/common/components/typography/Text.tsx
- packages/ui/src/forum/components/Council/CandidateCard.tsx
- packages/ui/src/forum/components/Council/CandidateVote.stories.tsx
- packages/ui/src/forum/components/Council/CandidateVote.tsx
> 🗳 Candidate vote

- packages/ui/src/common/components/SidePane/SidePaneTable.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/FormDetails.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/GeneralDetails.tsx
> 🪆 Fix application details nesting + form tab layout

- packages/ui/src/forum/components/category/CategoryListItem.tsx
- packages/ui/src/forum/components/category/LatestPost.tsx
> 💇🏼‍♀️ Trim long thread category title

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/HistoryTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/components/OpeningsHistory.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/components/WorkersHistory.tsx
- packages/ui/src/forum/hooks/useForumThreadPosts.ts
- packages/ui/src/working-groups/hooks/useOpeningsPagination.ts
- packages/ui/src/working-groups/hooks/usePastWorkersPagination.ts
- packages/ui/src/working-groups/hooks/useWorkersPagination.ts
- packages/ui/test/forum/hooks/useForumThreadPosts.test.ts
> 🎨 UI updates

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
Preliminary council schema. See: Joystream/joystream#2672
> 🧑‍⚖️ Add initial council schema

- packages/ui/src/mocks/server.ts
Closes #1500 
All that was missing was a resolver on the mock server
> 🍂 Add application unique resolver to mock server

- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.stories.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.stories.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
- packages/ui/src/working-groups/hooks/useWorkerEarnings.ts
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/test/_mocks/working-groups/workers.ts
- packages/ui/test/working-groups/hooks/useWorkerEarnings.test.tsx
Closes #1495 
This looks nice for now, but seeing how payouts take place every ~24h, I'm a little worried they'll start adding up really quickly - each of one's roles might end up having to fetch thousands of events before counting, after just three years.
> 🥝 Calculate worker's total earnings

- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/src/forum/components/Thread/ThreadTitle.tsx
- packages/ui/src/forum/modals/EditThreadTitleModal/EditThreadTitleModal.tsx
- packages/ui/src/forum/modals/EditThreadTitleModal/index.ts
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/index.ts
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/index.ts
- packages/ui/test/forum/modals/CreatePostModal.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
> 🔐 Clear editing states after submitting transaction 

- packages/ui/src/app/pages/Council/Election.tsx
- packages/ui/src/app/pages/Council/components/CouncilTabs.tsx
- packages/ui/src/council/hooks/useElectionStage.ts
- packages/ui/src/council/hooks/useElectionState.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/council/components/CouncilTabs.test.tsx
- packages/ui/test/council/pages/Election.test.tsx
> 🗳 Handle election state for election preview

- packages/ui/src/app/App.tsx
- packages/ui/src/proposals/constants/routes.ts
> 🕯️ Redirect /proposals to /proposals/current

- packages/ui/src/app/pages/Council/Election.tsx
- packages/ui/src/common/components/NoData.tsx
- packages/ui/src/council/components/election/announcing/AnnounceCandidacyButton.tsx
- packages/ui/src/council/components/election/announcing/AnnouncingStage.tsx
- packages/ui/src/council/components/election/announcing/NoCandidates.tsx
> 📣 Introduce no candidates components

- packages/ui/dev/scripts/generators/council/generateCouncils.ts
- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/council/components/councilList/CouncilList.stories.tsx
- packages/ui/src/council/components/councilList/CouncilList.tsx
- packages/ui/src/mocks/data/raw/councilors.json
- packages/ui/src/mocks/data/raw/councils.json
- packages/ui/src/mocks/data/seedCouncils.ts
- packages/ui/src/mocks/server.ts
- packages/ui/test/_mocks/council/index.ts
- packages/ui/test/council/pages/Council.test.tsx
Closes #1385
Closes #1526
Closes #1527
> 🧑‍🤝‍🧑 Sort councilors and handle empty state

- packages/ui/src/app/pages/Council/Election.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
> 🙈 Hide apply button in past openings

- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
> 🪜 Fix the Markdown editor height

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/council/components/election/ElectionTabs.tsx
- packages/ui/src/council/components/election/announcing/AnnouncingStage.tsx
- packages/ui/src/council/hooks/useElectionStage.ts
- packages/ui/src/council/types/Election.ts
- packages/ui/src/mocks/data/raw/candidates.json
- packages/ui/test/council/pages/Election.test.tsx
> 💆🏼‍♂️ Handle my candidates for election preview

- packages/ui/src/app/pages/Forum/ForumThread.tsx
> 🙈 Hide the suggested thread section

- packages/ui/src/forum/components/category/LatestPost.tsx
- packages/ui/src/forum/components/category/PopularThread.tsx
- packages/ui/src/forum/hooks/useCategoryLatestPost.ts
> ⚓️ Links to post and thread from thread category

- packages/ui/dev/scripts/generators/generateProposals.ts
- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/Activities/ActivityToIconMap.tsx
- packages/ui/src/mocks/data/raw/proposals.json
- packages/ui/src/mocks/data/seedEvents.ts
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostCreatedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostDeletedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostEditedContent.tsx
- packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
- packages/ui/src/proposals/queries/proposalsEvents.graphql
- packages/ui/src/proposals/types/ProposalsActivities/casts.ts
- packages/ui/src/proposals/types/ProposalsActivities/types.ts
...and that's proposals activities complete.
Closes #1444
> 🚧 Add proposal discussion activities

- packages/ui/src/council/modals/CandidacyPreview/CandidacyDetails.stories.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyDetails.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.stories.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberModal.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
See #1388 
I tried to add some sort of a mock data hook for a Candidate object but I wasn't very happy with it because Candidate in the GQL schema isn't completed yet. Instead, I focused on reusing the member preview as best as possible, for now
> 🍦 Candidacy preview modal skeleton

- packages/ui/dev/query-node-mocks/generators/council/generateCouncils.ts
- packages/ui/src/council/hooks/useCandidate.ts
- packages/ui/src/council/modals/CandidacyPreview/CandidacyDetails.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.stories.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
- packages/ui/src/council/modals/CandidacyPreview/types.ts
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/Candidate.ts
- packages/ui/src/council/types/index.ts
- packages/ui/src/mocks/components/storybook/MockApolloProvider.tsx
- packages/ui/src/mocks/data/raw/candidates.json
- packages/ui/src/mocks/data/raw/councilors.json
- packages/ui/src/mocks/data/raw/councils.json
- packages/ui/src/mocks/server.ts
See #1389 
Certain fields are missing from the schema, others I'm not yet sure how to look for (past election stats).
These I'm hoping to complete in follow-up PRs
> 🍸 Fetch candidacy details

- packages/ui/src/proposals/components/ProposalDiscussions.tsx
> ↘️ Fix proposal reply

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/RewardAccountStep.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> 💶 Handle reward account step for announce candidacy

- packages/ui/src/council/hooks/useCouncilSize.ts
- packages/ui/src/proposals/hooks/useVotingRounds.ts
- packages/ui/test/proposals/hooks/useVotingRounds.test.ts
> 🔀 Move useCouncilSize hook to council

- packages/ui/src/council/hooks/useElectionRemainingPeriod.ts
> 🧑‍🔧 Support inactive revealing and voting remaining periods

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/council/components/election/announcing/AnnouncingStage.tsx
- packages/ui/src/council/hooks/useElectionCandidatesIds.ts
- packages/ui/src/council/modals/CandidacyPreview/CandidacyDetails.tsx
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
- packages/ui/src/council/modals/CandidacyPreview/types.ts
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/memberships/components/MemberProfile/MemberModal.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
- packages/ui/src/mocks/data/seedCouncils.ts
- packages/ui/test/council/modals/CandidacyPreview.test.tsx
- packages/ui/test/council/pages/Election.test.tsx
Closes #1388 
Opening this as a new PR because github broke and didn't include the last couple of commits in the PR
> 🚲 Cycle candidates

- packages/ui/test/council/modals/CandidacyPreview.test.tsx
Fixes: https://github.com/Joystream/pioneer/runs/3813415741.
> 🥞 Fix types in tests

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/TitleAndBulletPointsStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/machine.ts
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> 📭 Handle title and bullet points for announce candidacy

- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalDetailsStep.tsx
Fixed editor height on small screens.
> 🪡 Change minRows default for CKEditor

- .github/workflows/CI.yml
> 📬 Add pull_request trigger to CI configuration

- packages/ui/src/accounts/components/AccountLockInfo.stories.tsx
- packages/ui/src/accounts/components/AccountLockInfo.tsx
- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/common/components/List/ListHeader.tsx
- packages/ui/src/council/components/PastVotes/PastVote/PastVote.tsx
- packages/ui/src/council/modals/RecoverVoteStake/RecoverVoteStakeModal.tsx
- packages/ui/src/council/modals/RecoverVoteStake/RecoverVoteStakeSignModal.tsx
- packages/ui/src/council/modals/RecoverVoteStake/RecoverVoteStakeSuccessModal.tsx
- packages/ui/src/council/modals/RecoverVoteStake/index.ts
- packages/ui/src/council/modals/RecoverVoteStake/machine.ts
- packages/ui/test/council/modals/RecoverVoteStakeModal.test.tsx
> ♻️ Add Recover vote stake transaction modal

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/StakingAccountStep.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleStakeStep.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
> 🐊 Validate other staking account

- packages/ui/src/council/hooks/useCandidateIdByMember.ts
- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/Success.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
Closes #1623 
We should wait for council schema upgrade on Olympia to get functionality fully working. But It's performing well with tests.
> 🔮 Handle see my announcement button for announce candidacy modal

- docs/mocks.md
- packages/ui/dev/chain-spec/data/.gitignore
- packages/ui/dev/chain-spec/docker-compose.yml
- packages/ui/dev/chain-spec/index.ts
> 📓 Document the chain specs generation

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalItemVoteDetails.tsx
- packages/ui/src/proposals/components/VoteForProposalButton.tsx
- packages/ui/src/proposals/components/VoteStatusComponent.stories.tsx
- packages/ui/src/proposals/components/VoteStatusComponent.tsx
- packages/ui/src/proposals/components/VotesPreview/VotesPreview.tsx
- packages/ui/src/proposals/hooks/useHasMemberVotedOnProposal.tsx
- packages/ui/test/_mocks/server/seeds/index.ts
- packages/ui/test/app/pages/ProposalPreview.test.tsx
> 🪵 Display councillor vote on proposal page

- packages/ui/src/common/components/Stepper/Stepper.tsx
- packages/ui/src/common/components/Stepper/types.ts
- packages/ui/src/common/model/machines/getSteps.ts
- packages/ui/src/forum/modals/PostHistoryModal/PostHistoryModal.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> 🐾 Fix history modal stepper

- packages/ui/package.json
- packages/ui/webpack.config.js
- yarn.lock
Looks like type checking is pretty slow :roll\_eyes: This PR implements some of the [webpack's performance suggestions](https://webpack.js.org/configuration/performance/).
Most notably:
*   make ts-loader only transpile the code
*   the TS type checking is off-loaded to a background task
*   some other optimizations from the guide
> 🐆 Webpack build time optimization

- packages/ui/src/working-groups/modals/ApplicationDetailsModal/ApplicationDetailsModal.tsx
- packages/ui/src/working-groups/modals/ApplicationDetailsModal/GeneralDetails.tsx
Issue https://github.com/Joystream/pioneer/issues/1497
N.B. I'm unable to test this because I need some openings, apply to them, and check cases when my application was hired and was not hired. I cannot do that by myself on Olympia, and if I try to run the node in dev mode according to the docs, UI is not working properly, I see a bunch of errors in console, and UI crashes to a white screen.
```
joystream-node --dev --tmp --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --log runtime
```
> 1497 - Application side-modal updates

- packages/ui/dev/query-node-mocks/generators/generateProposals.ts
- packages/ui/src/mocks/data/raw/proposals.json
- packages/ui/src/proposals/components/VotesPreview/VotesPreview.stories.tsx
- packages/ui/src/proposals/hooks/useVotingRounds.ts
- packages/ui/test/proposals/hooks/useVotingRounds.test.ts
Closes #1730 
As it turns out it doesn't really matter if rounds start at 0 or 1, but nonetheless we've changed mocks to reflect the real network and added some new test cases for `useVotingRounds` as it didn't account for some edge cases.
> 🏐 Add test cases for voting rounds
