Joystream/pioneer

- packages/ui/src/council/components/PastVotes/PastVote/PastVote.stories.tsx
- packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
- packages/ui/src/council/components/election/CandidateVote/RevealVoteButton.tsx
- packages/ui/src/council/components/election/voting/VotingStage.tsx
- packages/ui/src/council/hooks/useCommitment.ts
- packages/ui/src/council/hooks/useElectionVotes.ts
- packages/ui/src/council/hooks/useMyVotingAttempts.ts
- packages/ui/src/council/hooks/useStoredCastVotes.ts
- packages/ui/src/council/hooks/useVerifiedVotingAttempts.ts
- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/Vote.ts
- packages/ui/test/council/components/ElectionVotes.test.tsx
> 🪄 Show non stored revealed votes in Revealing stage

- docs/mocks.md
- packages/ui/dev/chain-spec/configs/revealing.ts
- packages/ui/dev/chain-spec/configs/voting.ts
- packages/ui/dev/chain-spec/index.ts
- packages/ui/src/common/helpers.ts
The votes casting sometime works and sometime does not. But it doesn't seems to be link to the chain spec so I will keep looking into it.
Also I wanted to set the duration as a positional option argument but I'm having some issue getting yargs to do what I want !
> 🎛️ Set candidates and custom stage duration in the chain spec

- packages/ui/src/app/components/PageHeaderWithHint.tsx
- packages/ui/src/common/components/Tooltip/Tooltip.tsx
- packages/ui/src/common/components/buttons/HintButton.tsx
> 🥱 Close tooltip hint

- packages/ui/src/app/pages/Council/PastElections/PastElections.tsx
> 🙈  Hide table headers when there is no past elections

- packages/ui/src/proposals/components/AddProposalButton.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalDetailsStep.tsx
- packages/ui/test/proposals/components/AddProposalButton.test.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
Closes #1510 
In addition to validating title/description length, the max active proposals number is also checked when displaying the button.
> 🦀 Add proposal parameters verification

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/Opening.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningListItem.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> ⛏ Display opening hiring/applications statistics correctly

- packages/ui/src/common/components/TransactionStatus/TransactionStatusNotification.tsx
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingPlugin.tsx
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingTokens.tsx
- packages/ui/src/common/modals/OnBoardingModal/components/ConnectAccountItem.tsx
- packages/ui/src/common/modals/OnBoardingModal/components/NoAccountStep.tsx
- packages/ui/src/common/modals/OnBoardingModal/components/SelectAccountStep.tsx
> 🛳 Some improvements for onboarding steps modal

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
> 🪆 Fix tooltip nesting

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
Issue https://github.com/Joystream/pioneer/issues/888
> 888 - External link support for tooltips

- packages/ui/src/app/pages/Forum/ForumArchived.tsx
- packages/ui/src/forum/hooks/useArchivedForumCategories.ts
- packages/ui/src/forum/hooks/useForumCategories.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/test/forum/hooks/useArchivedForumCategories.test.ts
- packages/ui/test/forum/hooks/useForumCategories.test.ts
- yarn.lock
Issue https://github.com/Joystream/pioneer/issues/1260
For Archived Categories moderators array is always empty now:
> 1260 - Archived <CategoryListItem /> shouldn't query Moderators

- packages/ui/src/working-groups/types/WorkingGroupApplication.ts
> Delete unused fields from WorkingGroupApplication type

- packages/ui/jest.config.js
- packages/ui/package.json
- packages/ui/src/app/App.tsx
- packages/ui/src/app/constants/routes.ts
- packages/ui/src/app/pages/Terms/PrivacyPolicy.tsx
- packages/ui/src/app/pages/Terms/TermsOfService.tsx
- packages/ui/src/app/pages/Terms/index.ts
- packages/ui/src/app/pages/Terms/md/Privacy.md
- packages/ui/src/app/pages/Terms/md/ToS.md
- packages/ui/src/app/pages/Terms/md/index.d.ts
- packages/ui/src/common/components/forms/LabelLink.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/test/app/pages/PrivacyPolicy.test.tsx
- packages/ui/test/app/pages/TermsOfService.test.tsx
- packages/ui/test/common/modals/OnBoardingModal.test.tsx
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
- packages/ui/webpack.config.js
- yarn.lock
Add _Terms of Service_ and  _Privacy and Cookies_  as .md files and display them as separate pages using _raw-display_ package
Closes #1778
> ⚖️ Add terms pages

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/Signal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/index.ts
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 📡 Signal proposal

- packages/ui/src/common/constants/videoHints.ts
Closes #1792 – PR used to check embeddable videos from Atlas: Joystream/atlas#1606.
> 🎥 Use videos from atlas

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SlashWorkingGroupLead.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/WorkingGroupLeadOpening.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/types.ts
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
> 👷 Select working group parameter for proposals

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
> 📇 Allow the same address for root and controller accounts

- packages/ui/src/app/components/PageHeaderWithHint.tsx
- packages/ui/src/common/components/buttons/HintButton.tsx
I think we had an issue for this bug can't find it 🤔
> ฺ Fix hint button z-index

- packages/ui/dev/query-node-mocks/generateMocks.ts
- packages/ui/dev/query-node-mocks/generators/generateProposals.ts
- packages/ui/src/mocks/data/raw/proposals.json
- packages/ui/src/mocks/data/seedProposalDetails.ts
- packages/ui/src/proposals/helpers/getDetailsRenderStructure.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/ProposalDetails.ts
- packages/ui/test/_mocks/server/seeds/index.ts
- packages/ui/test/app/pages/ProposalPreview.test.tsx
See #1835 
This adds parameters display to preview pages of:
* UpdateWorkingGroupBudget
* SetMaxValidatorCount
* FillWorkingGroupLeadOpening
* SetWorkingGroupLeadReward
* TerminateWorkingGroupLead
* SetMembershipPrice
* SetCouncilBudgetIncrement
> 🍺 Display proposal parameters

- packages/ui/src/common/components/Modal/Modal.tsx
> 🙄 Fix modal overflow

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpening/UpcomingOpeningDetails.tsx
> 🏙 Multi columns statistics

- packages/ui/src/common/components/page/PageContent.tsx
> 🎬 Fix page layout cut

- .gitignore
- docs/README.md
- packages/ui/.env.example
- packages/ui/package.json
- packages/ui/src/app/config.ts
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/providers/api/provider.tsx
- packages/ui/webpack.config.js
- yarn.lock
> 🏄‍♂️ Added .env variables to override Olympia-Testnet addresses

- .env
- packages/ui/.env.example
- packages/ui/src/app/config.ts
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
- packages/ui/src/mocks/server.ts
> 📩 Parse membership faucet url from .env

- .env
- packages/ui/.env.example
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
See: Joystream/atlas#1596
Update the faucet integration after Joystream/membership-faucet#8
> 🚚  Pass all information to membership faucet

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetWorkingGroupLeadReward.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/model/proposalDetails.ts
- packages/ui/src/working-groups/hooks/useWorkingGroup.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- yarn.lock
> 🙈 Set working group lead reward

- packages/ui/src/common/providers/onboarding/provider.tsx
- packages/ui/src/memberships/components/AddMembershipButton.tsx
> 🙈 Hide onboarding when have funds

- packages/ui/src/common/components/TransactionStatus/TransactionStatus.tsx
- packages/ui/src/common/components/buttons/TransactionButton.stories.tsx
- packages/ui/src/common/hooks/useProcessTransaction.ts
- packages/ui/src/common/modals/TransactionModal/TransactionModal.tsx
- packages/ui/src/common/model/machines/transaction.ts
- packages/ui/src/common/providers/transaction/context.tsx
- packages/ui/src/common/providers/transaction/provider.tsx
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/common/components/TransactionButton.test.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
- packages/ui/test/forum/modals/CreatePostModal.test.tsx
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- packages/ui/test/proposals/modals/VoteForProposalModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> 😬 Tx button

- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
> 🐛 Signal specifics shouldn't be in an array

- packages/ui/src/app/config.ts
- packages/ui/src/app/config/index.ts
- packages/ui/src/app/config/network.ts
- packages/ui/src/app/index.ts
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/hooks/useNetwork.ts
- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
- packages/ui/src/common/providers/api/provider.tsx
- packages/ui/src/mocks/server.ts
Related: #1845, #1812
Waiting for: #1849
> 🎒 Unify network config

- docs/README.md
- docs/testenv.md
> 📔 Add docs about running local dev env

- packages/ui/src/app/pages/Election/Election.tsx
- packages/ui/test/council/pages/Election.test.tsx
> 🥊 Fix election round displaying

- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFoundsTransferableModal.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/Modal/Modals.tsx
> 👾  Fixed funds move modal style

- packages/ui/src/app/pages/Proposals/ProposalsModule.tsx
> 🥖  Proposal breadcrumbs fix

- packages/ui/src/common/components/Tooltip/Tooltip.tsx
> 🦅  Fixed tooltip on disabled buttons

- packages/ui/src/accounts/model/filterAccounts.ts
> 🤡 Fixed transferable validations

- packages/ui/src/app/pages/Council/PastCouncils/PastCouncil.tsx
- packages/ui/src/app/pages/Election/PastElections/PastElection.tsx
- packages/ui/src/app/pages/Proposals/ProposalsModule.tsx
- packages/ui/test/council/pages/PastCouncil.test.tsx
- packages/ui/test/council/pages/PastElection.test.tsx
Just improved some breadcrumb texts and added a redirect so we don't have a breadcrumb that leads to a blank page.
> 🍋 Assorted breadcrumbs fixes

- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> 🙈 Show vote button only when stage is voting

- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
> 🏎️  Removed hanging zero in Membership Details

- packages/ui/src/accounts/providers/accounts/provider.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipModal.tsx
- packages/ui/src/memberships/providers/membership/provider.tsx
- packages/ui/test/membership/hooks/useMyMemberships.test.tsx
Big thanks for help @Qcza 
closes #1913
> 🎉  Solution to flashing onboarding top bar on app load

- packages/ui/src/bounty/components/Description.stories.tsx
- packages/ui/src/bounty/components/Descriptions.tsx
- packages/ui/test/bounty/components/Description.test.tsx
> 🥸 Create reusable description

- packages/ui/src/bounty/components/BountyListItem/BountyDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyInformations.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyListItem.stories.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyListItem.tsx
- packages/ui/src/bounty/components/BountyListItem/components/DetailBox.tsx
- packages/ui/src/bounty/components/BountyListItem/components/FundingDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/components/JudgmentDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/components/WithdrawalDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/components/WorkingDetails.tsx
- packages/ui/src/bounty/helpers.ts
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/common/components/BadgeStatus/BadgeStatus.ts
- packages/ui/src/common/components/Progress/ProgressBar.tsx
- packages/ui/src/common/components/Progress/ProgressBarWithRange.tsx
- packages/ui/src/common/components/typography/TokenValue.tsx
- packages/ui/src/common/constants/styles.ts
- packages/ui/src/memberships/components/Avatar.tsx
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/components.tsx
- packages/ui/test/bounty/components/BountyListItem.test.tsx
> 🌍  BountyListItem

- packages/ui/src/app/pages/Bounty/components/AddBountyButton.tsx
- packages/ui/src/app/pages/Bounty/components/BountiesHeader.stories.tsx
- packages/ui/src/app/pages/Bounty/components/BountiesHeader.tsx
- packages/ui/src/app/pages/Bounty/components/BountiesLayout.tsx
> 🐴 Add Header for Bounties page 

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/common/utils/casting.ts
- packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
- packages/ui/src/forum/hooks/useForumActivities.ts
- packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
- packages/ui/src/forum/queries/forumEvents.graphql
- packages/ui/src/forum/queries/index.ts
- packages/ui/src/forum/types/ForumActivity/casts.ts
- packages/ui/src/mocks/data/seedApplications.ts
- packages/ui/src/mocks/data/seedCouncils.ts
- packages/ui/src/mocks/data/seedWorkers.ts
- packages/ui/src/mocks/helpers/seedEntities.ts
- packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
- packages/ui/test/app/pages/Members.test.tsx
~~Requires https://github.com/thesan/joystream/pull/2~~
Requires https://github.com/Joystream/joystream/pull/2918
Closes #1524
> 🕹️ Use Forum events which implement the Event interface

- packages/ui/dev/query-node-mocks/generateMocks.ts
- packages/ui/dev/query-node-mocks/generators/generateBounties.ts
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
- packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
- packages/ui/src/mocks/data/index.ts
- packages/ui/src/mocks/data/raw/bounties.json
- packages/ui/src/mocks/data/raw/bountyContributions.json
- packages/ui/src/mocks/data/raw/bountyEntries.json
- packages/ui/src/mocks/data/seedBounties.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
~~Require #1990~~
It adds the first draft for the schema from https://github.com/Joystream/joystream/pull/2945 and part of the some mocks.
~~Note that `BountyEntry` is currently wrong (it should be fixed in https://github.com/Joystream/joystream/pull/2945). Also the events and the forum thread is missing from the mocks.~~
> ✍️ Add the bounty schema

- packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
> fix: Change past election round number to cycleId

- packages/ui/src/accounts/modals/MoveFoundsModal/AccountMoveFundsLocks.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MemberRowsList.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsTransferableModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/index.ts
- packages/ui/src/accounts/modals/MoveFoundsModal/styles.ts
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
> 🔒 Display account locks in Move Funds modal

- packages/ui/src/council/modals/CandidacyPreview/CandidacyDetails.tsx
> 🧵 Remove candidacy thread

- packages/ui/dev/query-node-mocks/generators/forum/generateForumThreads.ts
- packages/ui/dev/query-node-mocks/generators/generateBounties.ts
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/mocks/data/raw/bounties.json
- packages/ui/src/mocks/data/raw/bountyContributions.json
- packages/ui/src/mocks/data/raw/bountyEntries.json
- packages/ui/src/mocks/data/seedBounties.ts
- packages/ui/src/mocks/helpers/randomBlock.ts
Mostly mocks the `Bounty.discussionThread` and the events
> ✏️ Update bounty schema and mocks

- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
Restore Worker field in GetBountyQuery
> ♻️ Regenerate bounty queries

- packages/metadata-protobuf/compiled/index.d.ts
- packages/metadata-protobuf/compiled/index.js
- packages/metadata-protobuf/proto/Bounty.proto
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
> 🧑‍🔧 Fix bounty schema issues

- packages/ui/src/common/utils.ts
- packages/ui/src/mocks/helpers/seedEntities.ts
- packages/ui/test/_mocks/bounty/helpers.ts
- packages/ui/test/common/utils/utils.test.ts
> 🤿 Fix helpers to seed bounties in tests

- packages/ui/src/app/pages/Bounty/BountiesCurrent.tsx
- packages/ui/src/bounty/components/TopContributors/TopContributors.stories.tsx
- packages/ui/src/bounty/components/TopContributors/TopContributors.tsx
- packages/ui/src/bounty/hooks/useBountyContributions.ts
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/queries/bounty.graphql
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/services/i18n/dict/en/bounty.json
Closes #2068
Closes #1966 
Closes #1927
> 🔎 Contributors query

- packages/ui/src/bounty/components/WithdrawInfo/WithdrawInfo.stories.tsx
- packages/ui/src/bounty/components/WithdrawInfo/WithdrawInfo.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.stories.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/index.ts
- packages/ui/src/bounty/modals/WithdrawContributionModal/machine.ts
- packages/ui/src/bounty/modals/WithdrawSignModal/WithdrawSignModal.tsx
- packages/ui/src/bounty/modals/WithdrawSignModal/index.ts
- packages/ui/src/services/i18n/dict/en/bounty.json
- packages/ui/src/services/i18n/dict/en/common.json
- packages/ui/test/bounty/components/WinthdrawInfo.test.tsx
- packages/ui/test/bounty/modals/WithdrawContributionModal.test.tsx
> Refactor withdraw contribution modal

- packages/ui/src/bounty/components/BountyDiscussion/BountyDiscussion.stories.tsx
- packages/ui/src/bounty/components/BountyDiscussion/BountyDiscussion.tsx
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/queries/bounty.graphql
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
- packages/ui/test/bounty/components/BountyDiscussion.test.tsx
- packages/ui/test/bounty/components/BountyListItem.test.tsx
- packages/ui/test/bounty/components/BountyPreviewHeader.test.tsx
> Add bounty discussion

- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
- packages/ui/src/memberships/hooks/useMembers.ts
> ⚗️ Enable filtering by multiple roles

- packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
> 💂‍♀️ bugfix/added ScrolledModalBody component

- packages/ui/src/bounty/components/BountyListItem/BountyDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/components/TerminatedDetails.tsx
- packages/ui/src/bounty/helpers.ts
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/mocks/data/raw/bounties.json
> 😶‍🌫️ Feature/bounty terminated

- packages/ui/src/bounty/components/BountiesList.tsx
- packages/ui/src/common/components/icons/NoResults.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
> 🪘 Empty bounty list display

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Forum/ForumModule.tsx
- packages/ui/src/app/pages/Forum/components/ForumTabs.tsx
- packages/ui/src/app/pages/Overview/Overview.tsx
- packages/ui/src/app/pages/Overview/OverviewModule.tsx
- packages/ui/src/app/pages/Overview/components/OverviewMain.tsx
- packages/ui/src/forum/constant/routes.ts
- packages/ui/src/overview/constants/routes.ts
- packages/ui/src/services/i18n/dict/en/overview.json
closes #2131 , also routing was added
> 💁  feature/salutations, breadcrumbs and routing added

- packages/ui/src/common/components/storybookParts/previewStyles.tsx
- packages/ui/src/overview/components/Banners/Banners.stories.tsx
- packages/ui/src/overview/components/Banners/Banners.tsx
> 😶‍🌫️ Add generic banner for Guest view sidebar

- packages/ui/src/common/components/statistics/StatisticHeader.tsx
- packages/ui/src/overview/components/EarnedAndReward/EarnedAndReward.stories.tsx
- packages/ui/src/overview/components/EarnedAndReward/EarnedAndReward.tsx
> 🥇 Earned and reward components

- packages/ui/dev/node-mocks/commands/proposals/create.ts
- packages/ui/dev/node-mocks/index.ts
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
> 🤝 Fix add "runtime upgrade" proposal transaction

- packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
- packages/ui/src/mocks/server.ts
- packages/ui/src/overview/components/CouncilOverview/CouncilOverview.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalTile.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsOverview.stories.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsOverview.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsTilesList.tsx
- packages/ui/src/proposals/hooks/useProposalsCount.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/services/i18n/dict/en/overview.json
- packages/ui/test/_mocks/proposals/index.ts
- packages/ui/test/overview/components/ProposalsOverview.test.tsx
- packages/ui/test/proposals/hooks/useProposals.test.tsx
> 💡 Add Proposals central widget

- packages/ui/package.json
- packages/ui/src/common/api/queries/__generated__/queryNode.generated.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
- packages/ui/src/memberships/components/MemberListItem/Fileds.tsx
- packages/ui/src/memberships/components/MemberListItem/Member.tsx
- packages/ui/src/memberships/components/MemberListItem/MyMember.tsx
- packages/ui/src/memberships/hooks/useMemberRowWorkDetails.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
Add the balances, slashed and terminated data to the member, and my member rows
See #2223
> 🧩 Add missing data to the member rows

- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 📜 Fix create lead opening proposal transaction

- packages/ui/src/proposals/components/Activities/ProposalCancelledContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalCreatedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDecisionMadeContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionModeContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostCreatedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostDeletedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalDiscussionPostEditedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalExecutedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalStatusUpdatedContent.tsx
- packages/ui/src/proposals/components/Activities/ProposalVotedContent.tsx
> 🖇️ Fix links in Proposals Activities

- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsLockedModal.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsTransferableModal.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/StakingPolicyAndReward.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/StakingAccountStep.tsx
> 🙈 bugfix/create-proposal-flow

- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> Fix the applyOnOpening transaction staking account

- packages/ui/src/accounts/components/AccountItem/components/LockItem.tsx
- packages/ui/src/accounts/components/AccountLockInfo.tsx
- packages/ui/src/accounts/components/AccountLocks.tsx
- packages/ui/src/accounts/modals/MoveFoundsModal/AccountMoveFundsLocks.tsx
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/accounts/types/balances.ts
- packages/ui/test/_mocks/chainTypes.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/accounts/hooks/useHasRequiredStake.test.tsx
See #2223 (5th point)
Closes #2168
Closes #1748
> 🔑 Update the lock logic and ids

- packages/ui/src/forum/components/PostList/PostContextMenu.tsx
- packages/ui/src/forum/hooks/useForumPostParents.ts
- packages/ui/src/forum/model/postsToDeleteMap.ts
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
- packages/ui/test/forum/model/postsToDeleteMap.test.ts
> 🔨 Fix forum post deletion

- packages/ui/src/bounty/modals/SubmitJudgementModal/SubmitJudgementModal.tsx
- packages/ui/test/bounty/modals/SubmitJudgementModal.test.tsx
I've updated the test for the oracle judgement. I think these should pass for this part to be ready.
> 🧑‍⚖️ Fix Oracle judgement

- packages/ui/src/common/components/TransactionStatus/TransactionStatus.tsx
> 🐇 Hide Transaction success after 3 seconds

- packages/ui/src/app/components/PageHeaderWithHint.tsx
> 🤡 Feature/Tutorial-movies-hidden

- packages/ui/src/bounty/hooks/useBountyForumCategory.ts
- packages/ui/src/bounty/modals/AddBountyModal/AddBountyModal.tsx
- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/mocks/data/index.ts
- packages/ui/test/bounty/modals/AddBountyModal.test.tsx
> 🕸️ Add bounty threads in the oldest active root category

- packages/ui/src/forum/components/category/LatestPost.tsx
- packages/ui/src/forum/components/category/PopularThread.tsx
- packages/ui/src/forum/hooks/useCategoryLatestPost.ts
> 😶‍🌫️ Bugfix/empty page forum

- packages/ui/src/working-groups/hooks/useRewardPeriod.ts
> 🥸 bugfix/applying-to-opening

- packages/ui/dev/query-node-mocks/generators/generateBounties.ts
- packages/ui/src/app/pages/Bounty/components/BountyMain.tsx
- packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
- packages/ui/src/bounty/components/tabs/BountyTab.tsx
- packages/ui/src/bounty/hooks/useBounties.ts
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/queries/bounty.graphql
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/common/types/Block.ts
- packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
- packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
- packages/ui/src/mocks/data/raw/bounties.json
- packages/ui/src/mocks/data/raw/bountyContributions.json
- packages/ui/src/mocks/data/raw/bountyEntries.json
- packages/ui/src/mocks/data/seedBounties.ts
- packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
- packages/ui/test/_mocks/bounty/helpers.ts
- packages/ui/test/bounty/components/BountyListItem.test.tsx
- packages/ui/test/bounty/components/BountyPreviewHeader.test.tsx
- packages/ui/test/bounty/hooks/useBounties.test.tsx
Update the bounty schema based on the changes from Joystream/joystream#2945
(part of #2251)
> 📐 Update the bounty schema

- packages/ui/src/bounty/modals/AddBountyModal/components/FundingDetailsStep.tsx
> 🙈bugfix/funding period toggle fixed

- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
- packages/ui/test/bounty/modals/SubmitWorkModal.test.tsx
> 📮 Fix submit work modal

- packages/ui/src/common/components/EditableInputList/EditableInputList.stories.tsx
- packages/ui/src/common/components/EditableInputList/EditableInputList.tsx
- packages/ui/src/common/components/forms/ToggleCheckbox.tsx
> 👀 Feature/Create reusable input list component

- packages/ui/src/bounty/modals/AddBountyModal/AddBountyModal.tsx
- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/src/bounty/modals/AddBountyModal/machine.ts
- packages/ui/src/common/utils.ts
- packages/ui/test/bounty/modals/AddBountyModal.test.tsx
Closes #2350
I did this low-prio one, to easily be able to work on #2412 with the latest runtime.
> ✂️ Make the forum thread optional to create a bounty

- packages/ui/src/memberships/providers/membership/provider.tsx
> 👀Bugfix/#2534

- packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
> ContributeFundsModal refactor

- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
> 👾 bugfix: proposal creation with closed discussion mode

- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/app/pages/UpcomingOpening.test.tsx
- packages/ui/test/app/pages/WorkingGroup.test.tsx
Closes #2501
Should be rebased once #2525 is merged
Should be merged after Joystream/joystream#3386
> 🧐 Query & display the actual opening title

- packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
- packages/ui/src/bounty/modals/AddBountyModal/components/JudgingDetailsStep.tsx
> Small fixes on bounty

- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/test/bounty/modals/AddBountyModal.test.tsx
> 👀 helper for url validation

- packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
- packages/ui/src/bounty/modals/AnnounceWorkEntryModal/machine.ts
> 🤯  bugfix/account membership is selectable

- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/index.ts
> 💰 Display the correct proposal discution postDeposit

- .env
- packages/ui/dev/helpers/chain-spec/index.ts
- packages/ui/dev/node-mocks/data/addresses.ts
- packages/ui/dev/query-node-mocks/generators/generateMembers.ts
- packages/ui/src/accounts/hooks/useTransactionFee.ts
- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
- packages/ui/test/council/modals/VoteForCouncilModal.test.tsx
> 💥 Fix voting modal crashing after picking a member

- packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
- packages/ui/src/council/types/CouncilActivities/casts.ts
> 🏃 Fix the new candidate activity

- packages/ui/src/app/pages/Bounty/Bounty.tsx
- packages/ui/src/bounty/hooks/useBounty.ts
- packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
- packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.tsx
- packages/ui/src/bounty/modals/SubmitJudgementModal/SubmitJudgementModal.tsx
- packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.tsx
- packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.tsx
Refetch after:
Closes #2576 
Closes #2605
> 🌭 Refech Bounty after actions

- packages/ui/src/council/components/election/revealing/RevealingStage.tsx
- packages/ui/src/council/hooks/useElectionVotes.ts
- packages/ui/src/council/modals/RevealVote/RevealVoteModal.tsx
> 🗳️ Refetch votes after reveal

- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
> 👀 Bugfix/ create membership confirmation - correct base branch

- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/app/pages/WorkingGroup.test.tsx
- packages/ui/test/overview/components/WorkingGroupsOverview.test.tsx
> 🧐 Show the correct opening title

- packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
> Fixes on Submit Work messages

- packages/ui/src/bounty/components/BountyListItem/BountyListItem.tsx
> 📷 Show the actual bounties banner on the lists

- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/memberships/hooks/useRefetchMyMemberships.ts
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSuccessModal.tsx
- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipSuccessModal.tsx
> 🐶 Refetch myMemberships on creation and edition

- packages/ui/src/app/config/network.ts
- packages/ui/src/app/index.ts
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/hooks/useNetwork.ts
- packages/ui/src/common/providers/network-endpoints/context.ts
- packages/ui/src/common/providers/network-endpoints/provider.tsx
- packages/ui/src/mocks/server.ts
:warning: This should be merged (not squashed merged) and the branch should not be deleted (although I think the current GH setting prevents it)
> Merge network hotfixes back into dev

- packages/ui/src/common/helpers.ts
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
> 👁 Feature/WG descriptions added

- packages/ui/src/council/types/PastCouncil.ts
> Fix on Past Council blank page error

- packages/ui/src/bounty/components/modalsButtons/SubmitJudgementButton.tsx
> Fix for announce work on judgement modal

- packages/ui/src/working-groups/components/ApplicationsList.tsx
> 🥸 bugfix/additional validation added

- packages/ui/src/bounty/components/Descriptions.tsx
> 🖼️ Fix Bounty image size

- packages/ui/src/overview/components/DeadlineList/ProposalListItem.tsx
- packages/ui/src/overview/components/OverviewInfoElement.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalTile.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsOverview.tsx
- packages/ui/src/overview/components/WorkingGroupsOverview/WorkingGroupsTilesList.tsx
- packages/ui/src/overview/queries/__generated__/overview.generated.tsx
- packages/ui/src/overview/queries/overview.graphql
- packages/ui/src/overview/types/casts.ts
- packages/ui/src/proposals/hooks/useProposalsCount.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/test/overview/components/ProposalsOverview.test.tsx
> 🔧 Fix overview QN errors

- packages/ui/src/app/App.tsx
> 🛣  feature/ change default route

- packages/ui/src/bounty/components/BountyListItem/components/FundingDetails.tsx
> 🚧 Fix bounty funding progressbar

- packages/ui/src/bounty/components/modalsButtons/ClaimRewardButton.tsx
- packages/ui/src/bounty/components/modalsButtons/WithdrawWorkEntryButton.tsx
- packages/ui/src/bounty/modals/ClaimRewardModal/ClaimRewardModal.tsx
- packages/ui/src/bounty/modals/ClaimRewardModal/types.ts
- packages/ui/src/bounty/modals/WithdrawSignModal/WithdrawSignModal.tsx
- packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.tsx
- packages/ui/src/bounty/modals/WithdrawWorkEntryModal/index.ts
- packages/ui/test/_mocks/bounty/helpers.ts
- packages/ui/test/_mocks/bounty/index.ts
- packages/ui/test/bounty/components/BountyListItem.test.tsx
- packages/ui/test/bounty/hooks/useBounties.test.tsx
- packages/ui/test/bounty/modals/ClaimReward.test.tsx
- packages/ui/test/bounty/modals/WithdrawWorkEntryWork.test.tsx
> 🏹 Open all bounty modals after picking a member

- packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
- packages/ui/test/bounty/modals/AnnounceWorkEntryModal.test.tsx
> 🧊 Fix entry stake value and validation

- packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
- packages/ui/src/bounty/components/BountyWinnerListItem/BountyWinnerListItem.tsx
- packages/ui/src/bounty/components/tabs/WinnersTab.tsx
- packages/ui/src/bounty/helpers.ts
- packages/ui/src/bounty/modals/ClaimRewardModal/ClaimRewardModal.tsx
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/test/_mocks/bounty/index.ts
- packages/ui/test/bounty/components/BountyPreviewHeader.test.tsx
- packages/ui/test/bounty/modals/ClaimReward.test.tsx
> 💇 Remove BountyEntryStatusCashedOut from the schema

- packages/ui/src/bounty/components/Descriptions.tsx
> 📏 Set bounty image max width

- packages/ui/src/accounts/hooks/useStakingAccountStatus.ts
- packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
- packages/ui/src/bounty/modals/AuthorizeTransactionModal/AuthorizeTransactionModal.tsx
- packages/ui/src/common/hooks/useSchema.ts
- packages/ui/src/memberships/model/validation.ts
- packages/ui/test/_mocks/transactions.ts
- packages/ui/test/bounty/modals/AuthorizeTransactionModal.test.tsx
> 🤙 Fix on announce work entry tx

- packages/ui/src/bounty/components/WithdrawInfo/WithdrawInfo.stories.tsx
- packages/ui/src/bounty/components/WithdrawInfo/WithdrawInfo.tsx
- packages/ui/src/bounty/modals/ClaimRewardModal/ClaimRewardModal.tsx
- packages/ui/src/bounty/modals/WithdrawSignModal/WithdrawSignModal.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
- packages/ui/test/bounty/components/WinthdrawInfo.test.tsx
- packages/ui/test/bounty/modals/ClaimReward.test.tsx
This shows and details the actual amount "cashed out" by bounty winners, which is the reward (already shown before) **+ the amount their entries stake**
> 🤑 Add the stake amount to the cashout sign modal

- packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsOverview.tsx
- packages/ui/src/overview/components/ProposalsOverview/ProposalsTilesList.tsx
- packages/ui/src/overview/components/WorkingGroupsOverview/WorkingGroupsOverview.tsx
- packages/ui/src/overview/components/WorkingGroupsOverview/WorkingGroupsTilesList.tsx
> 0️⃣ Fix overview counters

- packages/ui/src/accounts/hooks/useTransactionFee.ts
- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/model/machines/transaction.ts
- packages/ui/src/common/providers/transaction/context.tsx
- packages/ui/src/common/providers/transaction/provider.tsx
> 🚧 Show a loader while waiting for the transaction fee

- packages/ui/src/accounts/components/AccountItem/components/LocksDetails.tsx
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/council/hooks/useLatestElection.ts
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/LatestElection.ts
> 🦎 Fix voting locks recovering

- packages/ui/src/working-groups/modals/LeaveRoleModal/LeaveRoleSignModal.tsx
> 🛣 Bugfix/leave role fixed

- packages/ui/src/memberships/components/MemberListItem/Fileds.tsx
> 🪛 bugfix/small style fix

- packages/ui/src/memberships/components/Avatar.tsx
- packages/ui/src/memberships/components/components.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
> 🤖 bugfix/avatar style fixed

- docs/mocks.md
- packages/ui/dev/node-mocks/commands/council/announce.ts
- packages/ui/dev/node-mocks/commands/members/create.ts
- packages/ui/dev/node-mocks/commands/opening/apply.ts
- packages/ui/dev/node-mocks/commands/opening/create.ts
- packages/ui/dev/node-mocks/commands/opening/fill.ts
- packages/ui/dev/node-mocks/commands/upcomingOpening/create.ts
- packages/ui/dev/node-mocks/index.ts
- packages/ui/dev/node-mocks/lib/api.ts
> ✍️ Add upcoming opening script

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModal.tsx
- packages/ui/src/proposals/modals/VoteForProposal/machine.ts
:warning: this should be merged not squash merged
> Merge olympia hotfixes (#2862) into dev

- packages/ui/.env.example
- packages/ui/dev/helpers/apiBenchmarking.ts
- packages/ui/dev/helpers/index.ts
- packages/ui/dev/node-mocks/lib/api.ts
- packages/ui/src/api/hooks/useApiBenchmarking.ts
- packages/ui/src/common/providers/api/provider.tsx
- packages/ui/src/common/utils/benchmark.ts
See #2905
```sh
yarn workspace ui helpers api-benchmarking
```
> 🕵️ Add some chain api benchmarking utilities

- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/test/accounts/hooks/useHasRequiredStake.test.tsx
> 📥 Enable voting stake reuse

- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
https://github.com/Joystream/pioneer/issues/2394
> 2394 - Show correct stake required for the WG Opening

- packages/ui/src/bounty/components/BountyListItem/BountyInformations.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyListItem.tsx
- packages/ui/src/bounty/components/BountyTiles/CommonTiles.tsx
- packages/ui/src/bounty/components/BountyTiles/FundingTiles.tsx
- packages/ui/src/bounty/helpers.ts
- packages/ui/src/bounty/modals/AddBountyModal/components/FundingDetailsStep.tsx
- packages/ui/src/bounty/modals/AddBountyModal/components/GeneralParametersStep.tsx
- packages/ui/src/bounty/modals/AddBountyModal/components/WorkingDetailsStep.tsx
- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/queries/bounty.graphql
- packages/ui/src/bounty/types/Bounty.ts
- packages/ui/src/bounty/types/casts.ts
- packages/ui/src/common/components/statistics/BlockDurationStatistics.tsx
- packages/ui/src/common/components/typography/DurationValue.tsx
- packages/ui/src/services/i18n/dict/en/bounty.json
> 👁Bugfix/bounty style fixes

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CancelWorkingGroupLeadOpening.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/FillWorkingGroupLeadOpening.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroupApplication/SelectWorkingGroupApplication.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroupOpening/SelectWorkingGroupOpening.tsx
https://github.com/Joystream/pioneer/issues/2419
> 2419 - Pass placeholder as props for SelectWorkingGroupOpening.

- packages/ui/package.json
- yarn.lock
> 🎲 Improvement on refetching after app interaction

- packages/ui/src/bounty/components/BountyListItem/components/JudgmentDetails.tsx
- packages/ui/src/bounty/components/BountyListItem/components/TerminatedDetails.tsx
> 🍡bugfix/fixed entrants list

- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/WarningModal.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🙈 bugfix/hide caution for create a proposal

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
https://github.com/Joystream/pioneer/issues/2821
> 2821: Create WG opening isn't clear enough on what leave_unstaking_period does

- README.md
- docs/README.md
- docs/testenv.md
- packages/ui/.env.example
- packages/ui/src/app/config/network.ts
- packages/ui/src/common/hooks/useNetwork.ts
I started making these changes on the `rhodes` branch but the doc is embarrassingly out dated :cold_sweat: 
See #2801
> ✍️ Hotfix update the testnet and doc

- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/proposals/hooks/useBlocksToProposalExecution.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/ProposalWithDetails.ts
- packages/ui/src/proposals/types/proposals.ts
- packages/ui/test/common/components/Mention.test.tsx
> ⏲️ Fix the Proposal "Time left" counter

- packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
#2689
This bug comes from adding `Become a member` header
Originally, main body height is 100%, it is natural to have scroll when we add it on top screen
So, I made `Become a member` header as sticky header
> Fix Vertical scroller on empty screen

- packages/ui/src/accounts/components/AccountItem/AccountItem.tsx
- packages/ui/src/accounts/components/AccountItem/AccountItemLoading.tsx
- packages/ui/src/accounts/components/Accounts.tsx
- packages/ui/src/common/components/ListItemLoader.tsx
- packages/ui/src/common/components/Skeleton.ts
- packages/ui/src/common/components/statistics/TokenValueStat.tsx
- packages/ui/src/common/components/typography/TokenValue.tsx
- packages/ui/src/common/constants/animations.ts
- packages/ui/src/common/constants/styles.ts
- packages/ui/test/accounts/components/MyAccounts.test.tsx
- packages/ui/test/working-groups/components/MyEarningsStat.test.tsx
> 🙈 POC: Loading state on accounts list

- packages/ui/src/bounty/components/BountyTiles/CommonTiles.tsx
- packages/ui/src/bounty/components/BountyTiles/FundingTiles.tsx
- packages/ui/src/common/components/statistics/BlockDurationStatistics.tsx
- packages/ui/src/common/components/typography/DurationValue.tsx
- packages/ui/test/overview/components/CouncilOverview.test.tsx
> 🥸bugfix/fixed period length

- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/test/forum/components/NewThreadPost.test.tsx
> fix/2423 Keep editable check button is not noticeable in Forum

- packages/ui/src/bounty/modals/AddBountyModal/AddBountyModal.tsx
- packages/ui/test/bounty/modals/AddBountyModal.test.tsx
> 🧨 Hotfix on AddBountyModal validation mode

- packages/ui/src/proposals/modals/AddNewProposal/components/WarningModal.tsx
> 💂‍♀️ bugfix/improve warning modal section

- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
- packages/ui/src/overview/components/WorkingGroupsOverview/WorkingGroupsOverview.tsx
- packages/ui/src/working-groups/types/WorkingGroup.ts
> 🪛hotfix/overview section hidden

- packages/ui/src/working-groups/modals/IncreaseWorkerStakeModal/IncreaseWorkerStakeModal.tsx
- packages/ui/src/working-groups/modals/IncreaseWorkerStakeModal/machine.ts
- packages/ui/test/working-groups/modals/IncreaseWorkerStakeModal.test.tsx
> 👀 fix/increase worker stake validation refactor

- packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalFormModal.stories.tsx
- packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModal.tsx
- packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModalForm.tsx
- packages/ui/src/proposals/modals/VoteForProposal/machine.ts
> 🌵 Refactor on vote for proposal validation

- packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
- packages/ui/src/bounty/components/BountyMainComponents/BountySuccessful.tsx
- packages/ui/src/bounty/components/BountyMainComponents/BountyTerminated.tsx
- packages/ui/src/bounty/components/BountySidebar/BountySidebar.tsx
- packages/ui/src/bounty/components/BountySlashedListItem/BountySlashedListItem.stories.tsx
- packages/ui/src/bounty/components/BountySlashedListItem/BountySlashedListItem.tsx
- packages/ui/src/bounty/components/tabs/SlashedTab.tsx
- packages/ui/src/bounty/helpers.ts
> 🦝 Fix on bounty judgement rationale

- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
> ⏰Bugfix/buy membership modal

- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.stories.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/machine.ts
> ✉️ Bugfix/create thread form refactor

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/components/VotesPreview/VotePreview.tsx
- packages/ui/src/proposals/components/VotesPreview/VotesPreview.tsx
- packages/ui/src/proposals/types/proposals.ts
> 🧷 Fix on proposal not voted section

- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilFormModal.tsx
- packages/ui/test/council/modals/VoteForCouncilModal.test.tsx
> 🧧 Validation staking account on council vote

- packages/ui/src/app/pages/Election/Election.tsx
- packages/ui/src/common/hooks/useRefetchQueries.ts
> 🐕 Refetch election queries after the announcing stage

- packages/ui/src/forum/hooks/useLatestForumThreads.ts
- packages/ui/src/forum/hooks/useMyThreads.ts
- packages/ui/src/forum/hooks/useWatchlistedThreads.ts
https://github.com/Joystream/pioneer/issues/2831
Before: 
After:
> Exclude moderated threads from my threads, latest threads and watchlisted threads.

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
https://github.com/Joystream/pioneer/issues/2712
> Strip backslashes in MarkdownPreview to make it work

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
> Fix invalid stake on WG opening page

- packages/ui/jest.config.js
> ⏱️ Increase test timeout

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberFormModal.tsx
- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
- packages/ui/src/memberships/model/validation.ts
- packages/ui/test/membership/modals/InviteMemberModal.test.tsx
> 🦚 Fix on invite member modal 

- packages/ui/src/council/hooks/useCouncilorWithDetails.ts
- packages/ui/src/council/types/PastCouncil.ts
> 🛠️ Fix PastCouncils page loading

- packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
- packages/ui/src/app/pages/Bounty/components/BountiesTabs.tsx
- packages/ui/src/bounty/components/BountiesList.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyInformation.tsx
- packages/ui/src/bounty/components/BountyListItem/BountyListItem.tsx
- packages/ui/src/bounty/components/BountyListItem/components/FundingDetails.tsx
- packages/ui/src/bounty/hooks/useUserBountyTabsInformation.ts
- packages/ui/src/bounty/modals/WithdrawSignModal/WithdrawSignModal.tsx
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/bounty/queries/bounty.graphql
- packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
- packages/ui/src/council/components/pastCouncil/PastCouncilWorkingGroups/PastCouncilWorkingGroupsItem.tsx
:warning: this should be merged not squash merged
Closes #3170
> Fix bounties page on `dev`

- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/common/components/buttons/CopyButton.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
- packages/ui/src/proposals/constants/styles.ts
> Add proposal ID to proposal card (#2296)

- packages/ui/src/council/types/PastCouncil.ts
- packages/ui/src/council/types/PastCouncilWorkingGroup.ts
> 💥 Fix past councils WG page crash

- packages/ui/src/app/components/FMBanner.tsx
- packages/ui/src/common/components/icons/USFlag.tsx
> 🖇️ Add links to FM banner

- packages/ui/package.json
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
- yarn.lock
https://pioneer-2-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/forum/thread/174:
https://pioneer-2-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/proposals/preview/165?post=187:
Closes #2425
> Markdown Support: Use RemarkGFM to support additional syntax.

- packages/ui/src/app/pages/Bounty/Bounty.tsx
- packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
- packages/ui/src/bounty/components/BountySidebar/Periods.tsx
- packages/ui/src/common/components/typography/DurationValue.tsx
- packages/ui/src/common/hooks/useRefetchQueries.ts
Fixes refresh issue introduced by #3150 as part of #2592
> 🔧 Fix the bounty page constant refresh

- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteFormModal.tsx
> 📬bugfix/transfer invite validation added

- packages/ui/src/accounts/components/AccountItem/components/LockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/LocksDetails.tsx
- packages/ui/src/accounts/components/AccountItem/components/RecoverButton.tsx
- packages/ui/src/accounts/hooks/useIsVoteStakeLocked.ts
- packages/ui/src/accounts/modals/RecoverBalance/RecoverBalanceSignModal.tsx
- packages/ui/src/council/components/election/voting/VotingStage.tsx
> 🔄 Fix recovering Vote stake

- packages/ui/src/common/components/buttons/Toggle.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
Fixing: https://github.com/Joystream/pioneer/issues/2220 with the approach proposed by @thesan
> #2220 Put onClick={toggleOpen} to the whole Toggle component.

- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/machine.ts
> Add prev step button on ApplyForRoleModal (#2445)

- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
- packages/ui/src/common/components/Modal/Modals.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SlashWorkingGroupLead.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> ☕ Follow up of new proposal modal validation

- docs/mocks.md
- packages/ui/dev/node-mocks/commands/forumCategory/create.ts
- packages/ui/dev/node-mocks/commands/opening/apply.ts
- packages/ui/dev/node-mocks/commands/opening/create.ts
- packages/ui/dev/node-mocks/commands/opening/fill.ts
- packages/ui/dev/node-mocks/commands/setLead.ts
- packages/ui/dev/node-mocks/commands/upcomingOpening/create.ts
- packages/ui/dev/node-mocks/consts.ts
- packages/ui/dev/node-mocks/index.ts
> 🧰 Add the `node-mocks forumCategory:create` command

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
> 💬 Fix the proposal and bounty discussions style

- packages/ui/src/accounts/components/AccountItem/components/LockDate.tsx
- packages/ui/src/accounts/components/AccountItem/components/LockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/LockItemWrapper.tsx
- packages/ui/src/accounts/components/AccountItem/components/LockLinkButton.tsx
- packages/ui/src/accounts/components/AccountItem/components/LockRecoveryTime.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/BoundAccountLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/BountyLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilCandidateLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilorLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/InvitationLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/ProposalLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/VoteLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/WorkingGroupLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/styles.ts
- packages/ui/src/accounts/components/AccountItem/components/types.ts
- packages/ui/src/common/components/BlockTime/BlockInfo.tsx
- packages/ui/src/proposals/hooks/useBlocksToProposalExecution.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/proposals.ts
> ⌚ Fix locks recovery time

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
If upcoming events equal 0 hide them.
> #2705 empty upcoming openings section

- packages/ui/src/accounts/components/AccountItem/components/LockRecoveryTime.tsx
- packages/ui/src/accounts/components/AccountItem/components/LocksDetails.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilorLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/styles.ts
- packages/ui/src/accounts/hooks/useRecoveryConditions.ts
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/test/accounts/hooks/useMyTotalBalances.test.tsx
- packages/ui/test/accounts/model/toBalances.test.ts
- packages/ui/test/app/pages/MyProfile/MyAccounts.test.tsx
Closes #3109 
Scope: https://github.com/Joystream/pioneer/issues/3109#issuecomment-1174870115
> ⏲️ Recovery time for worker application stake fixes

- packages/ui/src/common/components/Modal/Modal.tsx
> Fix bounties modals not resizing with windows size

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
> 👨‍🚀 Filter withdrawn applications from openings

- packages/ui/src/common/components/Modal/Modal.tsx
> 🖌️ Fix extra "padding" in modals

- packages/ui/src/accounts/components/AccountLocks.tsx
- packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
- packages/ui/src/council/components/pastCouncil/PastCouncilMembers/PastCouncilMembersItem.tsx
- packages/ui/src/council/components/pastCouncil/PastCouncilsList/PastCouncilListItem.tsx
- packages/ui/src/memberships/components/MemberInfo.tsx
- packages/ui/src/memberships/components/MemberList/MemberList.stories.tsx
- packages/ui/src/memberships/components/MemberList/Members.tsx
- packages/ui/src/memberships/components/MemberListItem/Fields.tsx
- packages/ui/src/memberships/components/MemberListItem/Member.tsx
- packages/ui/src/memberships/components/MemberListItem/MemberListItem.stories.tsx
- packages/ui/src/memberships/components/MemberListItem/MyMember.tsx
- packages/ui/src/memberships/components/MemberListItem/components/MemberCreated.tsx
- packages/ui/src/memberships/components/MemberListItem/components/MemberReferrer.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/components/MembersSection.tsx
- packages/ui/src/memberships/hooks/useMembers.ts
- packages/ui/src/memberships/hooks/useMembership.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/memberships/types/Member.ts
- packages/ui/src/memberships/types/casting.ts
- packages/ui/test/app/pages/Members.test.tsx
- packages/ui/test/council/components/ElectionVotes.test.tsx
- packages/ui/test/council/pages/PastCouncil.test.tsx
Follow-up: #2888 
UI side of work: @Palllke2015
> :neckbeard: New columns for members list

- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/app/pages/Election/Election.tsx
- packages/ui/src/app/pages/Forum/ForumCategories.tsx
- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
- packages/ui/src/common/hooks/useRefetchQueries.ts
- packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
- packages/ui/test/council/pages/Council.test.tsx
> 🐻‍❄️ Polling on chosen pages

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/helpers.ts
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> 🔥 Hotfix on staking for candidacy

- packages/ui/src/proxyApi/models/payload.ts
> 🪲 Fix carthage `ProxyApi` related bugs

- packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
- packages/ui/src/common/helpers.ts
- packages/ui/src/working-groups/components/SelectWorkingGroup/OptionsListWorkingGroup.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/model/workingGroupName.ts
> 🔒 Unlocking Gateway WG

- packages/ui/src/common/providers/transactionFees/provider.tsx
> ♾️ Fix for infinite waiting modal

- packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
- packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
- packages/ui/src/common/components/Modal/Modals.tsx
- packages/ui/src/common/components/Tooltip/Tooltip.tsx
- packages/ui/src/common/utils/validation.ts
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/src/working-groups/modals/ApplyForRoleModal/helpers.ts
> 🤙 Fix on carthage validation issues

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/RewardAccountStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/helpers.ts
- packages/ui/src/council/modals/AnnounceCandidacy/machine.ts
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> 🌶️ Fix the `announceCandidacy` reward account choice

- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
> ♻️ Refetch after faucet registration

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
> 😶‍🌫️ Update on member name validation

- packages/ui/src/accounts/hooks/useHasRequiredStake.ts
- packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
- packages/ui/src/overview/components/CouncilOverview/CouncilTilesList.tsx
> 🦺 Fix on few BN sortings

- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteFormModal.tsx
> ⏺️ Fix on TransferInviteModal validation

- packages/ui/src/common/components/TransactionFee.stories.tsx
- packages/ui/src/common/components/TransactionFee.tsx
> 🛑 Remove extra tooltip on transaction fee info

- packages/ui/src/proposals/components/ProposalDetails/renderers/Member.tsx
- packages/ui/src/proposals/helpers/getDetailsRenderStructure.ts
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
> 🔧 Fixes the wrong group for fill WG opening proposal

- packages/ui/dev/helpers/nextCouncilStage.ts
- packages/ui/dev/node-mocks/commands/council/announce.ts
- packages/ui/dev/node-mocks/commands/council/elect.ts
- packages/ui/dev/node-mocks/commands/council/reveal.ts
- packages/ui/dev/node-mocks/commands/council/vote.ts
- packages/ui/dev/node-mocks/index.ts
- packages/ui/package.json
> 🗳️ Add a `node-mocks council:elect` for testing node

- packages/ui/src/council/types/CouncilActivities/casts.ts
> 🌳 Fix on council activities error

- packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModal.tsx
> ♨️ Hotfix on respawning vote for proposal modal

- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteModal.tsx
- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteSuccessModal.tsx
- packages/ui/src/memberships/modals/TransferInviteModal/machine.ts
> 🌵 Fix on transfer invite modal success CTA

- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
> 🌳 Displaying fees on create thread modal

- packages/ui/src/accounts/components/AccountItem/components/lockItems/WorkingGroupLockItem.tsx
> 🎲  Fix on application lock CTA

- packages/ui/src/council/hooks/useElectionVotes.ts
> 🩹 Another BN sorting fix

- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberRequirementsModal.tsx
> 🎊 Invite member requirements copy change

- packages/ui/src/common/utils/validation.ts
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
resolves last comment from #3453
> 🙈 Ignoring validation for undefined constants

- packages/ui/src/forum/types/ForumCategory.ts
- packages/ui/src/forum/types/ForumCategoryWithDetails.ts
> 👻 Fix on forum phantom subcategories

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
> 🕳️  Hide referrer on onboarding

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
> 🧯 Execution conditions validation for update WG budget

- packages/ui/src/bounty/modals/AuthorizeTransactionModal/AuthorizeTransactionModal.tsx
- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
- packages/ui/src/council/modals/AnnounceCandidacy/components/transactions/AnnounceCandidacyTransaction.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/transactions/CandidacyNoteTransaction.tsx
- packages/ui/src/memberships/modals/BindStakingAccountModal/BindStakingAccountModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberSignModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SignTransactionModal.tsx
- packages/ui/src/proposals/modals/ChangeThreadMode/SignTransactionModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSignModal.tsx
> 🧛 Fix for fee balance validation across multiple modals

- packages/ui/src/common/hooks/useProcessTransaction.ts
> 🔥 Fallback tx fee to zero

- packages/ui/src/common/providers/transactionFees/provider.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSignModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberSignModal.tsx
- packages/ui/src/memberships/modals/utils.ts
> 💢 Additional validation for membership creating

- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberRequirementsModal.tsx
> 🛩️ Small link and wording change 

- packages/ui/src/accounts/modals/ClaimVestingModal/ClaimVestingModal.tsx
> :feelsgood: Fix for vesting fee check

- packages/ui/src/common/utils/validation.ts
- packages/ui/src/common/utils/validation.tsx
- packages/ui/src/memberships/model/validation.ts
> 🚧 Improvement on staking account status UX

- packages/ui/src/common/model/JoystreamNode/errorEvents.ts
- packages/ui/src/common/utils/proxy.ts
- packages/ui/src/proxyApi/models/payload.ts
- packages/ui/src/proxyApi/utils/proxy.ts
> 🔧 Fix tx event serialization

- packages/ui/src/bounty/modals/AuthorizeTransactionModal/AuthorizeTransactionModal.tsx
- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
- packages/ui/src/forum/modals/CreateThreadModal/CreateThreadSignModal.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostSignModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/index.ts
- packages/ui/src/forum/modals/PostActionModal/PostActionSignModal.tsx
> 🦺 Improvement for forum actions with invitation lock

- packages/ui/src/common/hooks/useProcessTransaction.ts
- packages/ui/src/common/model/machines/transaction.ts
> 🐾 Show transaction fee error

- packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
> 🐧 Onboarding pending status

- packages/ui/src/council/components/PastVotes/PastVote/PastVote.tsx
> 🔥 Hotfix on recover button on past vote

- packages/ui/src/council/hooks/useElectionVotes.ts
> 📨 Removing invalid memoization

- packages/ui/src/memberships/model/validation.ts
> 🧯 Fix on external resources validation

- packages/ui/src/common/components/page/PageTitle.tsx
- packages/ui/src/forum/components/Thread/ThreadTitle.tsx
Fixes https://github.com/Joystream/pioneer/issues/3266
> 🙈 fix: Delete and Edit buttons are shown on removed thread pages #3266

- packages/ui/src/accounts/components/AccountItem/components/lockItems/WorkingGroupLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/types.ts
- packages/ui/src/app/providers/QueryNodeProvider.tsx
> 🔒 WG lock UI refactor

- packages/ui/src/accounts/components/AccountItem/components/LockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/LockRecoveryTime.tsx
- packages/ui/src/accounts/components/AccountItem/components/RecoverButton.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilCandidateLockItem.tsx
- packages/ui/test/app/pages/MyProfile/MyAccounts.test.tsx
> 🇪🇹 Update on candidate lock ETA

- packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
- packages/ui/src/app/components/OnboardingOverlay/components/BenefitListItem.tsx
- packages/ui/src/app/components/OnboardingOverlay/components/BenefitsTable.tsx
- packages/ui/src/common/components/Stepper/VerticalStaticStepper.tsx
> 🌵 Onboarding overlay cosmetic fixes

- packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
- packages/ui/src/council/components/election/revealing/RevealingStage.tsx
- packages/ui/src/council/model/electionVotingResultComparator.ts
> 🏛️ Past election result sorting

- packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
- packages/ui/src/accounts/modals/TransferModal/TransferSignModal.tsx
- packages/ui/src/common/utils/validation.tsx
> 🆕 New message on for all tokens transfer

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
>  🎨 Quick fix to captcha theme

- packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.tsx
> ✊ Account for abstention in quorum

- packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
> 🧥 Considering WG name mapping in search

- packages/ui/src/common/modals/SignTransactionModal/SignTransactionModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
> ❌ Fix validation on carthage

- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilFormModal.tsx
- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
> 🔧 Fix the vote for council modal

- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilCandidateLockItem.tsx
> 🚫 Fix on 404 election link

- packages/ui/src/app/pages/Forum/ForumThread.tsx
Fixes https://github.com/Joystream/pioneer/issues/3122
> fix: Forum first post time display issue

- packages/ui/src/proposals/components/ProposalList/ProposalItemVoteDetails.tsx
- packages/ui/test/proposals/components/ProposalListItem.test.tsx
> 👻 Hiding unnecessary loader on proposal list item

- packages/ui/src/council/types/Election.ts
> 🔥 Hotfix: Hide withdrawn candidates

- packages/ui/src/accounts/hooks/useStakingAccountsLocks.ts
> 🔥 Hotfix: Allow reusing voting stake in next election

- packages/ui/src/common/model/formatters.ts
- packages/ui/test/common/model/formatters.test.ts
> 🤐 Fix the < 0.01 JOY sign

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Fixes https://github.com/Joystream/pioneer/issues/3297
> fix: tooltips on account creation

- packages/ui/src/common/hooks/useQueryNode.ts
- packages/ui/src/common/hooks/useQueryNodeTransactionStatus.ts
> 🧷 Subscription timeout

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/overview/queries/__generated__/overview.generated.tsx
- packages/ui/src/working-groups/components/ApplicationsList.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
fixes display of applications counters in #3665
> 🎐 Consider withdrawn applications in counters

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/model/workingGroupName.ts
see [#3399 ](https://github.com/Joystream/pioneer/pull/3399#issuecomment-1283548439) (fixes #3268)
> Fix WG opening route (#3399)

- packages/ui/src/forum/components/threads/ThreadListItem.tsx
Fixed) Forum: tooltip to show full thread title #3273
> added tooltip for thread title

- packages/ui/src/common/hooks/useProcessTransaction.ts
- packages/ui/src/proxyApi/models/payload.ts
- packages/ui/src/proxyApi/worker/tx.ts
> 📣 Report non fee related SignAndSend errors

- packages/ui/src/app/pages/Forum/ForumModule.tsx
- packages/ui/src/app/pages/Forum/ForumWatchlist.tsx
- packages/ui/src/common/components/page/PageContent.tsx
- packages/ui/src/forum/components/Thread/WatchlistButton.tsx
- packages/ui/src/forum/components/ThreadCard/ThreadCard.tsx
- packages/ui/src/forum/components/threads/ThreadList.tsx
⚠️ Should be reviewed after #3653 
Implements #3162
> Feature stack: Forum watchlist tab

- packages/ui/src/common/components/Search/SearchResultsModal.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterSearchBox.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/hooks/useSearch.ts
https://github.com/Joystream/pioneer/issues/3470
> Forum: cannot search for numbers #3470

- packages/ui/src/council/modals/WithdrawCandidacyModal/WithdrawWarningModal.tsx
- packages/ui/test/council/modals/WithdrawCandidacyModal.test.tsx
Fixes #2507
[broke test/council/modals/WithdrawCandidacyModal.test.tsx](https://github.com/Joystream/pioneer/actions/runs/3299590739/jobs/5443131106#step:7:255)
> Withdraw candidacy tooltip (#2507)

- packages/ui/src/working-groups/components/ApplicationsList.tsx
> Allow to withdraw stake of rejected applications (#3251)

- packages/ui/src/working-groups/components/Activities/ActivitiesModals/StakeChanged/StakeChangedModal.tsx
- packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
> Hide rationale from Slash and Decrease WGL stake details (#3458)

- packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
> Tooltips on `TriggerAndDiscussionStep` (#2346)

- packages/ui/src/accounts/providers/accounts/provider.tsx
> 🗝️  Keeping account provider empty while no wallet

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
> Show default target of WG Openings as 1 (#2539)

- packages/ui/src/app/components/ConnectionStatusDot.tsx
- packages/ui/src/common/hooks/useBlockHash.ts
- packages/ui/src/common/hooks/useQueryNodeTransactionStatus.ts
- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
- packages/ui/test/common/components/ConnectionStatusDot.test.tsx
> 🪠 Resubscribe to QN state to validate tx

- packages/ui/src/app/App.tsx
- packages/ui/src/common/utils/env.ts
> 🚧 Parse the value of `REACT_APP_IS_UNDER_MAINTENANCE`

- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilCandidateLockItem.tsx
- packages/ui/src/accounts/components/AccountItem/components/lockItems/VoteLockItem.tsx
- packages/ui/src/council/hooks/useCouncilRemainingPeriod.ts
- packages/ui/src/council/hooks/useElectionStage.ts
Fix the issue found during [3660 QA](https://github.com/Joystream/pioneer/issues/3660#issuecomment-1297078053)
> ⏳ Fix the recovery time of the voting and candidacy locks

- packages/ui/src/memberships/components/SelectMember/SmallMemberSelect.tsx
- packages/ui/src/memberships/hooks/useSearchMembers.ts
> 🎗️ Removing initial members on select on past proposals

- packages/ui/src/accounts/hooks/useMyTotalBalances.ts
Fixes latest additions to dev in e06495a9..bdfbdde9
> Hotfix: default to BN_ZERO in `useMyTotalBalances`

- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> 🍃 Execution consts validation for lead invitation quota

- packages/ui/src/common/components/SmallFileUpload/SmallFileUpload.tsx
- packages/ui/src/common/helpers.ts
- packages/ui/src/memberships/components/AvatarInput.tsx
- packages/ui/src/memberships/model/validation.ts
> ⚖️ Scaling down avatar before the upload

- packages/ui/src/working-groups/components/ApplicationsList.tsx
> Fix rejected application status on `ApplicationsList` (#2913)

- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
Past Proposals: Remember last search #2915
> FIX - Past Proposals: Remember last search #2915

- packages/ui/dev/node-mocks/commands/council/announce.ts
- packages/ui/dev/node-mocks/commands/council/vote.ts
- packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilorLockItem.tsx
- packages/ui/src/accounts/hooks/useGroupLocks/helpers.ts
- packages/ui/src/council/hooks/useCouncilRemainingPeriod.ts
- packages/ui/src/council/hooks/useElectionStage.ts
- packages/ui/src/council/hooks/useLatestElection.ts
> 😤 Fix voting lock recovery again

- packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
> Sort members (#2334)

- docs/README.md
- docs/mocks.md
- package.json
- packages/markdown-editor/package.json
- packages/ui/package.json
> 🔖 Set Pioneer the version to `0.1.0`

- packages/ui/src/app/pages/Forum/ForumArchived.tsx
- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/app/pages/Forum/ForumWatchlist.tsx
> 🍶 Adding refetch hook to the forum pages

- packages/ui/src/common/components/forms/TokenInput.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/TerminateWorkingGroupLead.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> 🤖 Terminate WG lead execution consts validation

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/RestoreVotes/RestoreVotesModal.tsx
Fixes #3670 + suggestion for RestoreVotesModal tooltip text
> Stake tooltip on announce candidacy signing modal (#3670)

- packages/ui/src/common/utils/validation.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> Ease validation for `minContext` and `maxContext` (#2601)

- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/common/utils/validation.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
- packages/ui/test/common/components/ConnectionStatus.test.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
- packages/ui/test/forum/modals/DeleteThreadModal.test.tsx
- yarn.lock
Fixes #3131
Added one more suggestion to the mix, please decide which one it is.
> Tweak validation error wording on `VoteForCouncil` (#3131)

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/providers/GlobalStyle.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/page/Page.tsx
- packages/ui/src/common/constants/styles.ts
- packages/ui/src/common/modals/ConfirmModal/ConfirmModal.tsx
- packages/ui/src/common/providers/modal/context.tsx
- packages/ui/src/common/providers/modal/provider.tsx
- packages/ui/src/common/providers/modal/types.ts
> 🎬 Modal closing on text selection

- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
> 🗺️ Rework on forum thread navigation

- packages/ui/src/common/modals/SignTransactionModal/SignTransactionModal.tsx
- packages/ui/src/forum/modals/DeleteThreadModal/DeleteThreadModal.tsx
- packages/ui/test/accounts/modal/RecoverBalanceModal.test.tsx
- packages/ui/test/bounty/modals/AddBountyModal.test.tsx
- packages/ui/test/bounty/modals/AnnounceWorkEntryModal.test.tsx
- packages/ui/test/bounty/modals/ClaimReward.test.tsx
- packages/ui/test/bounty/modals/ContributeFundsModal.test.tsx
- packages/ui/test/bounty/modals/SubmitJudgementModal.test.tsx
- packages/ui/test/bounty/modals/WithdrawContributionModal.test.tsx
- packages/ui/test/bounty/modals/WithdrawStakeModal.test.tsx
- packages/ui/test/bounty/modals/WithdrawWorkEntryWork.test.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
- packages/ui/test/council/modals/RevealVoteModal.test.tsx
- packages/ui/test/forum/modals/CreatePostModal.test.tsx
- packages/ui/test/forum/modals/CreateThreadModal.test.tsx
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
- packages/ui/test/forum/modals/DeleteThreadModal.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
- packages/ui/test/membership/modals/InviteMemberModal.test.tsx
- packages/ui/test/membership/modals/UpdateMembershipModal.test.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- packages/ui/test/proposals/modals/VoteForProposalModal.test.tsx
- packages/ui/test/setup.ts
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
- packages/ui/test/working-groups/modals/ChangeAccountModal.test.tsx
- packages/ui/test/working-groups/modals/LeaveRoleModal.test.tsx
> 🧪 Test fix on DeleteThreadModal tests

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Fixes #3263
Was already implemented just changed the string and optimized a little.
Tests report rerenders for untested state changes related to avatar upload. cc @mkbeefcake
> Membership handle validation (#3263)

- packages/ui/src/common/components/SmallFileUpload/SmallFileUpload.tsx
- packages/ui/src/common/helpers.ts
- packages/ui/src/memberships/hooks/useUploadAvatarAndSubmit.ts
- packages/ui/src/memberships/model/validation.ts
> 🌼 Considering blob in upload function

- packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
This correctly shows and uses total balance for accounts when voting.
> VoteForCouncil: Fix use total balance

- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilSuccessModal.tsx
- packages/ui/test/council/pages/Election.test.tsx
- packages/ui/test/setup.ts
> Votes backup CTA on `VoteForCouncilSuccessModal` (#1633)

- packages/ui/src/council/hooks/useElectionVotes.ts
> 🩹 Temp fix for the revealing stage

- packages/ui/test/forum/modals/DeleteThreadModal.test.tsx
> 🚶 Correctly await some test calls

- packages/ui/src/app/components/ConnectionStatusDot.tsx
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/common/components/NetworkInfo/NetworkInfo.tsx
- packages/ui/src/common/components/PolkadotAppInfo.tsx
- packages/ui/src/common/components/SettingsInformation.tsx
> 💅 Block height in Settings 

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/components/category/ForumMain.tsx
#3922 (no fix but less confusion)
> Hide empty `Moderators` (#3922)

- packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModal.tsx
> Wording on `MoveFundsModal` (#3835)

- packages/ui/src/app/pages/Profile/MyAccounts.tsx
fixes https://github.com/Joystream/pioneer/issues/2847#issuecomment-1334954504
> Total recoverable balance (#2847)

- packages/ui/package.json
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
- packages/ui/src/common/helpers.ts
- packages/ui/src/working-groups/components/WorkingGroupImage.tsx
- packages/ui/src/working-groups/constants/index.ts
- packages/ui/src/working-groups/model/workingGroupName.ts
- packages/ui/src/working-groups/types/locks.ts
- yarn.lock
This should solve #3889. I was convinced I had merged #3935 into `mainnet` but it looks like I merged it on `dev` :facepalm:
> 🔀 Merge `dev` into `mainnet`

- packages/ui/src/forum/modals/PostActionModal/components/PostInsufficientFundsModal.tsx
> 🪛 Fix insufficient funds modal copies

- packages/ui/src/proposals/components/ProposalDiscussions.tsx
- https://github.com/Joystream/pioneer/issues/3236#issuecomment-1342504628
https://pioneer-2-git-fix-proposal-discussion-crash-joystream.vercel.app/#/proposals/preview/41
> 🔧 Fix proposal discussion crash

- packages/ui/src/forum/components/Thread/WatchlistButton.tsx
Fixes #3769
2nd commit is optional, your choice.
> Don't overwrite watchlist (#3769)

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/components/ForumPageHeader.tsx
Fixed the issue #3904
https://github.com/Joystream/pioneer/issues/3904
> added description for ForumPageHeader (#3904)

- packages/ui/src/forum/components/category/LatestPost.tsx
- packages/ui/src/forum/components/category/PopularThread.tsx
> Forum refetch fix (#3915)

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/common/helpers.ts
> thread datetime

- packages/ui/src/council/modals/WithdrawCandidacyModal/WithdrawWarningModal.tsx
- packages/ui/test/council/modals/WithdrawCandidacyModal.test.tsx
> Update `Withdraw Candidacy` warning (#3895)

- CHANGELOG.md
- packages/ui/package.json
- #3730
Here's a preview of the [CHANGELOG.md](https://github.com/Joystream/pioneer/blob/version-1.0.0/CHANGELOG.md)
NOTE: the `v1.0.0` tag will be moved to `main` later on.
> 🚀 Introduce a changelog

- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/services/i18n/dict/en/settings.json
> Settings: Chain info formatting + i18n (#2342)

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/common/components/page/PreviousPage.tsx
Back button on openings now list to list page as requested from this https://github.com/Joystream/pioneer/issues/2977
@traumschule @oleksanderkorn
> Fixed back link issue on opening with empty referrer

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
Fixed the issue #3924 
https://github.com/Joystream/pioneer/issues/3924
> Fixed stake not displayed

- packages/ui/src/accounts/components/AccountItem/components/lockItems/InvitationLockItem.tsx
Fixes #3479
Failing forum tests are unrelated.
> Add InvitationLock tooltip on My Accounts (#3479)

- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
> Fix initial 'member.about' on `UpdateMembershipFormModal` (#3973)

- packages/ui/src/common/constants/videoHints.ts
> Empty videoHints for now (#3971)

- packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
> `StakeStep` tooltip (#3944)

- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipModal.tsx
- packages/ui/test/membership/modals/UpdateMembershipModal.test.tsx
Fixed https://github.com/Joystream/pioneer/issues/3133
https://user-images.githubusercontent.com/69617937/206702505-3ed71081-8aad-4dbc-bf6a-df80e9d3cbf4.MP4
> Fixed the issue on update membership

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/src/forum/types/ForumCategoryWithDetails.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
Fixed the issue
https://github.com/Joystream/pioneer/issues/3922
> fixed moderators in forum category

- packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
> Fix typo (#4025)

- packages/ui/src/forum/modals/PostReplyModal/PostReplyModal.tsx
Fixed issue #4022, #3967
Updated the transaction at the postText is updated in the modal
> update transaction at postText updated

- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
> Rename Proposal `Constants` to `Parameters` (#4046)

- packages/ui/src/accounts/components/StakeStep.tsx
> Fix typo and link on `StakeStep` (#4054)

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
#3904 ([according to](https://github.com/Joystream/pioneer/pull/3925/files#r1067399021))
> Don't truncate Category description (#3904)

- packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
Fix https://github.com/Joystream/pioneer/issues/3682
> Fix candidacy staking and voting stake tooltips

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
Fixes https://github.com/Joystream/pioneer/issues/4039
> open all Markdown links in new tab

- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> 🏁 Allow full UTF-8 in proposal titles

- packages/ui/src/proposals/model/proposalDescriptions.ts
> Update WG budget proposal description (#4010)

- packages/ui/src/memberships/components/MemberRoles.tsx
> Remove member role (#4004)

- packages/ui/src/forum/components/ThreadCard/ThreadCard.tsx
> Start replies count at zero and hide if empty (#4029)

- packages/ui/src/working-groups/components/ApplicationsList.tsx
Fix https://github.com/Joystream/pioneer/issues/3856
> Fix Rejected applicant is displayed as Pending

- CHANGELOG.md
- docs/mocks.md
- packages/ui/dev/helpers/decode.ts
- packages/ui/dev/helpers/index.ts
- packages/ui/src/accounts/components/StakeStep.tsx
- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/icons/symbols/LinkSymbol.tsx
- packages/ui/src/common/components/page/Sidebar/NavigationLink.tsx
- packages/ui/src/common/components/selects/components.tsx
- packages/ui/src/common/model/JoystreamNode/index.ts
- packages/ui/src/common/model/JoystreamNode/metadataFromBytes.ts
- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/forum/components/ThreadCard/ThreadCard.tsx
- packages/ui/src/memberships/components/InviteMemberButton.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/types.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/src/proposals/model/proposalDescriptions.ts
- packages/ui/src/working-groups/components/ApplicationsList.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroupOpening/OptionWorkingGroupOpening.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroupOpening/OptionsListWorkingGroupOpening.tsx
- packages/ui/src/working-groups/components/SelectWorkingGroupOpening/SelectWorkingGroupOpening.tsx
- packages/ui/test/membership/modals/InviteMemberModal.test.tsx
- Member handles when hovering candidacies.
- Allow full UTF-8 proposal titles.
- `decode` helper command for development.
- Open markdown links in a new tab.
- WG openings list items and selector options.
- Description of the update WG budget proposal.
- Rename proposal "Constants" to "Parameters".
- The virtual member role.
- Invite member modal.
- New posts preview modal.
- Status of rejected and canceled application.
- Block explorer icon look.
- Do not truncate forum category descriptions.
- Latest threads reply count.
- Typos.
> 🚀 Release `1.3.0`

- packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
> Clarify tooltip for `My contributed votes` (#4153)

- packages/ui/src/app/pages/Forum/ForumWatchlist.tsx
- packages/ui/src/forum/hooks/useWatchlistedThreads.ts
Fix https://github.com/Joystream/pioneer/issues/3642
> Update watchlist view to horizontal scroller

- packages/ui/src/proposals/components/ProposalHistory.tsx
- packages/ui/src/proposals/hooks/useVotingRounds.ts
- packages/ui/test/_mocks/server/seeds/index.ts
- packages/ui/test/app/pages/ProposalPreview.test.tsx
- packages/ui/test/proposals/hooks/useVotingRounds.test.ts
> Multiple Constitutionality Proposal View Fix

- packages/ui/src/proposals/components/ProposalStages.tsx
- #4239
Check:
- https://dao-git-feature-rename-proposal-preview-tab-joystream.vercel.app/#/proposals/preview/63
- https://dao-git-feature-rename-proposal-preview-tab-joystream.vercel.app/#/proposals/preview/175
> ✍ Rename proposal preview page tabs

- packages/ui/src/app/pages/Council/Council.tsx
#4043
It's easy to switch to monthly if preferred.
> Show Councilor reward per day and week (#4043)

- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
> AddNewProposal modal: Move up `Stake` and `Constitutionality` (#4044)

- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
This should unblock #4265 along with other PRs failing the CI ATM.
I'm confused on how #4050 passed the CI, @traumschule was there anything particular about it ?
> 🔧 Fix #4050 linting

- packages/ui/src/proposals/components/ProposalStages.tsx
> Multiple Constitutionality Proposal Tooltip Fix (#4241)

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
> fixes #4256  Links don't wrap

- packages/ui/src/common/hooks/useLocation.ts
- packages/ui/src/forum/components/PostList/PostListItem.tsx
#3968 and #4129 same issue
@chrlschwb check pls
> fixes #3968, fixes #4129 fix autoscroll to issue

- packages/ui/src/app/pages/Forum/ForumThread.tsx
> fixes #4272 Too wide empty space

- CHANGELOG.md
- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
- packages/ui/src/common/hooks/useLocation.ts
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
- packages/ui/src/proposals/components/ProposalStages.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
- packages/ui/src/working-groups/components/NextPayoutStat.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
- packages/ui/src/working-groups/hooks/useMyWorkers.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
- packages/ui/src/working-groups/queries/workingGroupsEvents.graphql
- packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
- Incorrect values in the "My Roles" tab.
- Working group history tab crashing.
- Infinite auto scroll to a post after opening a link to this post.
- Unclear councilor reward widget.
- Some posts overflowing on Webkit browsers.
- Improve stake and constitutionality visibility when creating a proposal.
- Copy improvements: proposal discussion status and voting rounds tabs tooltips, and forum empty category.
- Buggy link icon on proposal lists.
> 🚀 Release `1.3.2`

- packages/server/src/notifier/model/email/forum.ts
- packages/server/test/_mocks/notifier/createMember.ts
- packages/server/test/notifier.test.ts
- packages/server/test/notifier/createNotifications.test.ts
- packages/server/test/setup.ts
> 📏 Test the email notification integration

- packages/ui/src/proposals/components/ProposalStages.tsx
- https://github.com/Joystream/pioneer/issues/4348
> 🥊 Fix the first stage of multi round proposals

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/memberships/modals/EmailSubscriptionModal/EmaiSubscriptionFormModal.tsx
- packages/ui/src/memberships/modals/EmailSubscriptionModal/EmailSubscriptionModal.stories.tsx
- packages/ui/src/memberships/modals/EmailSubscriptionModal/EmailSubscriptionModal.tsx
- packages/ui/src/memberships/modals/EmailSubscriptionModal/index.tsx
- packages/ui/src/memberships/modals/EmailSubscriptionModal/machine.ts
- packages/ui/src/memberships/modals/EmailSubscriptionModal/types.ts
> #4232 signer modal component

- packages/ui/src/accounts/providers/balances/provider.tsx
> fixes #4434: Hide total balance when wallet was disconected

- packages/ui/.storybook/preview.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
- packages/ui/src/mocks/helpers/asChainData.ts
- packages/ui/src/mocks/helpers/index.ts
- packages/ui/src/mocks/helpers/transactions.ts
- packages/ui/src/mocks/providers/accounts.tsx
- packages/ui/src/mocks/providers/api.tsx
- packages/ui/src/mocks/providers/query-node.tsx
- packages/ui/test/_mocks/transactions.ts
Part of:
- #3521
[Screencast from 2023-06-23 14-11-41.webm](https://github.com/Joystream/pioneer/assets/6571453/7b52b884-05e5-40ff-be6c-d8b1d32e44ac)
> 📚 Add modals support in stories

- packages/ui/test/bounty/modals/AnnounceWorkEntryModal.test.tsx
seems to be the last remnant #4447
> fix `MoveFoundsModal` (#4447)

- packages/ui/.storybook/preview.tsx
- packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
- packages/ui/src/app/pages/Proposals/PastProposals.stories.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
- packages/ui/src/common/types/helpers.ts
- packages/ui/src/mocks/data/proposals.ts
- packages/ui/src/mocks/providers/api.tsx
- packages/ui/src/mocks/providers/index.tsx
- packages/ui/src/mocks/providers/query-node.tsx
- packages/ui/src/mocks/providers/router.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.stories.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ProposalTypeStep.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetCouncilBudgetIncrement.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetReferralCut.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateChannelPayouts/UpdateChannelPayouts.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CancelWorkingGroupLeadOpening.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/CreateWorkingGroupLeadOpening.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/FillWorkingGroupLeadOpening.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.stories.tsx
> 📖 Add stories for the current and past proposals pages

- .github/workflows/CI.yml
Eg. https://github.com/Joystream/pioneer/actions/runs/5477045920/jobs/9975576219
> 🩹 Fix backend CI

- packages/ui/src/common/components/Mention/Mention.tsx
> fix member handle issue from forum

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
- https://github.com/Joystream/pioneer/issues/3560
Used in #4461
[> Story](https://pioneer-2-storybook-git-fork-vrrayz-working-gr-873fcf-joystream.vercel.app/?path=/story/pages-working-group-workinggroup--default)
> working group page story

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
> Fix-4504: fixed the css for indents

- packages/ui/src/council/hooks/usePastCouncilWorkingGroups.ts
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/PastCouncilWorkingGroup.ts
- packages/ui/src/mocks/server.ts
- packages/ui/test/council/pages/PastCouncil.test.tsx
> Fix-3225: used BudgetUpdatedEvent instead of BudgetSetEvent

- packages/server/src/auth/model/token.ts
- packages/ui/src/app/pages/Settings/SettingsNotificationsTab.stories.tsx
- packages/ui/src/app/pages/Settings/SettingsNotificationsTab.tsx
- packages/ui/src/app/providers/backend/provider.tsx
- packages/ui/src/memberships/queries/__generated__/backend.generated.tsx
- packages/ui/src/memberships/queries/backend.graphql
- packages/ui/src/mocks/providers/gql.tsx
~**⚠️ Based on #4580, review first ⚠️**~
Resolves #4238
> add support for backend re-authentication

- packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
> My Voting Result was wrong!

- packages/ui/src/common/components/BlockTime/BlockInfo.tsx
- packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
fix wrong links in "past elections"
https://github.com/Joystream/pioneer/pull/4258#issuecomment-1783199572
> Fix the block link opening past elections

- packages/server/README.md
- packages/server/package.json
- packages/server/src/auth/model/token.ts
- packages/server/src/auth/scripts/generateToken.ts
> 🩹 Fix the `dev:authtoken` script

- packages/server/src/auth/api/auth.ts
- packages/server/src/auth/model/emailVerification.ts
- packages/server/src/common/utils/email.ts
Based on #4364 (add better log for #4606)
> 📜 Log email activity

- packages/server/src/notifier/model/email/forum.ts
- packages/server/src/notifier/model/event/forum.ts
- packages/server/src/notifier/queries/events.graphql
- packages/server/test/_mocks/notifier/events/forum.ts
- packages/server/test/notifier.test.ts
> 🗨️ Add `FORUM_POST_REPLY` notifications

- packages/ui/package.json
- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/App.tsx
- packages/ui/src/app/components/ErrorFallback.tsx
- yarn.lock
rebase https://github.com/Joystream/pioneer/pull/4439 , fixes https://github.com/Joystream/pioneer/issues/4052
> Error boundary

- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
Fixes https://github.com/Joystream/pioneer/issues/4122#issuecomment-1576978647
> Fix runtime upgrade proposal

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/council/components/election/VoteForCouncilButton.tsx
Fix for https://github.com/Joystream/pioneer/issues/4656
> vote again fix

- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/council/hooks/useCouncilStatistics.ts
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
Let's show reward per week but for a single council members, not for the full council, that's very confusing.
Close #4043
> show reward for single councillor on council page

- CHANGELOG.md
- packages/ui/.env.example
- packages/ui/package.json
- packages/ui/src/api/index.ts
- packages/ui/src/api/utils/getChainMetadata.ts
- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
- packages/ui/src/common/components/Stepper/HorizontalStaticStepper.tsx
- packages/ui/src/common/components/buttons/Links.tsx
- packages/ui/src/common/constants/styles.ts
- packages/ui/src/common/providers/responsive/context.ts
- packages/ui/src/common/providers/responsive/provider.tsx
- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/proxyApi/client/query.ts
- packages/ui/src/proxyApi/client/tx.ts
- packages/ui/src/proxyApi/index.ts
- packages/ui/src/proxyApi/types.ts
- packages/ui/src/proxyApi/utils/proxy.ts
- packages/ui/src/validators/components/ValidatorItem.tsx
- packages/ui/src/validators/modals/NominatingRedirectModal/NominatingRedirectModal.tsx
- packages/ui/src/validators/modals/NominatingRedirectModal/index.ts
- packages/ui/src/validators/modals/NominatingRedirectModal/types.ts
- packages/ui/src/validators/modals/validatorCard/ValidatorCard.tsx
- packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
- packages/ui/webpack.config.js
- Support for forum action and email registration on mobile.
> 🚀 Release `2.3.0`

- packages/ui/src/common/components/BlockTime/BlockInfo.tsx
> Block height link fix

- packages/ui/src/memberships/components/ProfileComponent.tsx
> Hide Total Balance

- packages/ui/src/council/components/PastVotes/PastVotesList.tsx
> 🐛 Fix continuously refreshing pages

- packages/ui/src/accounts/model/encodeAddress.ts
- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/constants/chain.ts
- packages/ui/src/app/constants/currency.ts
- packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
- packages/ui/src/common/constants/numbers.ts
- packages/ui/src/common/model/createType.ts
- packages/ui/src/proxyApi/client/query.ts
- packages/ui/src/proxyApi/client/tx.ts
- packages/ui/src/validators/providers/useValidatorsWithDetails.ts
- packages/ui/src/validators/providers/utils.ts
- #4723
:warning: depends on #4718
> 📡 Fix the queries broken by the `ProxyApi`

- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/pages/Profile/MyMemberships.stories.tsx
- packages/ui/src/app/pages/Validators/ValidatorList.stories.tsx
- packages/ui/src/app/pages/Validators/ValidatorList.tsx
- packages/ui/src/common/components/forms/ToggleCheckbox.tsx
- packages/ui/src/common/constants/numbers.ts
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/src/mocks/data/raw/members.json
- packages/ui/src/mocks/data/validators.ts
- packages/ui/src/mocks/helpers/asChainData.ts
- packages/ui/src/mocks/providers/api.tsx
- packages/ui/src/validators/components/ValidatorsList.tsx
- packages/ui/src/validators/components/statistics/Era.tsx
- packages/ui/src/validators/components/statistics/ValidatorsState.tsx
- packages/ui/src/validators/hooks/useStakingStatistics.tsx
- packages/ui/src/validators/hooks/useValidatorsList.tsx
- packages/ui/src/validators/modals/ValidatorsInfo.tsx
- packages/ui/src/validators/modals/validatorCard/ValidatorCard.tsx
- packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
- packages/ui/src/validators/providers/provider.tsx
- packages/ui/src/validators/providers/useValidatorsQueries.ts
- packages/ui/src/validators/providers/useValidatorsWithDetails.ts
- packages/ui/src/validators/providers/utils.ts
This PR removes some duplicated or unnecessary RPC queries, fixes a bunch of bugs, allow the data to update once a new era starts (I haven't tested this though), and refactor the mocks.
@eshark9312 please have a look when you can.
> 🧹 Finalize validator dashboard

- CHANGELOG.md
- packages/server/package.json
- packages/server/src/notifier/model/event/election.ts
- packages/server/src/notifier/model/event/forum.ts
- packages/server/src/notifier/model/event/utils/buildEvent.ts
- packages/server/src/notifier/model/event/utils/types.ts
- packages/server/test/notifier.test.ts
- packages/ui/package.json
- Don't notify people of their own messages in threads they created.
> 🚀 Release patch `2.4.1`

- packages/ui/src/app/pages/Proposals/Proposals.tsx
- packages/ui/src/proposals/hooks/useProposals.ts
> 🩹 Fix the infinite proposal page reload for CMs

- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/pages/Profile/MyMemberships.stories.tsx
- packages/ui/src/validators/components/statistics/ValidatorsState.tsx
> Fix nominator count in the validator dashboard

- CHANGELOG.md
- packages/ui/package.json
- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/app/pages/WorkingGroups/UpcomingOpening.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/proposals/components/CancelProposalButton.tsx
- packages/ui/src/proposals/modals/CancelProposal/CancelProposalModal.tsx
- packages/ui/src/proposals/modals/CancelProposal/index.ts
- packages/ui/src/proposals/modals/CancelProposal/types.ts
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/model/asWeeklyRewards.ts
- Cancel proposal button.
- Display weekly opening rewards instead of daily.
> 🚀 Release patch `2.5.0`

- packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/ExecutionRequirementsWarning.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdatePalletFrozenStatus.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/src/proposals/model/validation.ts
Address https://github.com/Joystream/joystream/issues/4878#issuecomment-1867715348
> 🔧 Fix freeze pallet proposal

- packages/ui/src/common/hooks/useSignAndSendTransaction.ts
Enable the usage of the OneKey extension
> 🙈 Make wallet metadata update optional

- README.md
> ✨ Add CHANGELOG link to the main README

- packages/server/codegen.ts
- packages/server/src/common/queries/schema.graphql
> 🩹 Use local schema schema to run the codegen

- packages/ui/src/memberships/components/ProfileComponent.tsx
> Format JOY ticker

- CHANGELOG.md
- packages/ui/package.json
- packages/ui/src/common/components/ContextMenu/ContextMenu.tsx
> 🔥 Hotfix the forum post context menu
