Joystream/pioneer

- packages/ui/src/components/notifications/HelpNotification.tsx
- packages/ui/src/hooks/useBalances.ts
- packages/ui/src/modals/TransferModal/SignTransferModal.tsx
- packages/ui/src/modals/TransferModal/TransferDetailsModal.tsx
- packages/ui/src/pages/Profile/Accounts.tsx
- packages/ui/test/mocks/keyring/signers.ts
- packages/ui/test/modals/TransferModal.test.tsx
- packages/ui/test/pages/Accounts.test.tsx
I've introduced a small set of UI tests for the modals. I've used here API mocking since I'm not happy with the limitations (re-run tests for instance) of the Sinon hooks stubbing.
I see two options:
1. Decide on using Jest for proper hooks mocking.
2. Refactor `useApi` (and ` useBalances`) to use Rx API flavor of the API and then see how hooks could be improved.
ps.: I look forward to Rx API as I think that it would play nicer with the hooks API ([link](https://soshace.com/react-hooks-rxjs-or-how-react-is-meant-to-be/), [link](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/docs/useObservable.md))
> ✍️ Sign transaction from extension

- packages/ui/src/hooks/useAccounts.ts
- packages/ui/src/providers/keyring/provider.tsx
As described in #209 – the extension was not always available (on Firefox at least) and the keys were not loaded. The library did not detect that extension was loaded later because of a hardcoded check that was evaluated when enabling the extension.
> ⏲ Make keys from extension more reliable

- packages/ui/src/accounts/model/sortAccounts.ts
- packages/ui/src/accounts/providers/accounts/provider.tsx
- packages/ui/src/app/pages/Profile/components/Accounts.tsx
- packages/ui/src/app/pages/Profile/components/Memberships.tsx
- packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
- packages/ui/src/memberships/components/CurrentMember/SwitchMemberModal.tsx
- packages/ui/src/memberships/hooks/useMyMemberships.ts
- packages/ui/src/memberships/model/sortMemberships.ts
- packages/ui/src/memberships/providers/membership/context.tsx
- packages/ui/src/memberships/providers/membership/provider.tsx
- packages/ui/test/accounts/components/MyAccounts.test.tsx
- packages/ui/test/accounts/hooks/useTotalBalances.test.tsx
- packages/ui/test/membership/components/MyMemberships.test.tsx
- packages/ui/test/membership/hooks/useMyMemberships.test.tsx
@p-sad FYI we had one nasty bug related to how JS sort work :cry: I've forgotten for some reason that `.sort()` is one in-place:
```javascript
const t = [8,3,7,1,5,8,1,3]
t.sort()
console.log( t )
// logs; [1, 1, 3, 3, 5, 7, 8, 8]
```
That made the dependency list of `useMemo()` useless and triggered re-render loop :man\_dancing: 
The other changes are related to reducing the number of initial calls to Hydra as:
*   The way how accounts were returned was causing re-renders (each account triggered hook change) I've added `debounceTime()` for that.
> 📡 Query my memberships once

- packages/ui/src/mocks/data/mockOpenings.ts
- packages/ui/src/working-groups/components/ApplicationQuestionInput.tsx
- packages/ui/src/working-groups/components/OpeningFormPreview.stories.tsx
- packages/ui/src/working-groups/components/OpeningsList.stories.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplicationStep.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRolePrepareModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSignModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleSuccessModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/test/_mocks/members/index.ts
- packages/ui/test/_mocks/server/index.ts
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
See #419 & #418.
The sign & send transaction works, but since we do not have any openings on the blockchain we can't verify if it is OK.
The follow-ups for this PR include:
> 💼 Apply for position transaction

- packages/ui/src/app/pages/Members/Members.tsx
- packages/ui/src/memberships/components/MemberList/Members.tsx
- packages/ui/src/memberships/hooks/useMembers.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/mocks/resolvers.ts
Should close #433
I followed the `packages/ui/src/common/api/schemas/schema.graphql` but Apollo generates the `GetMembersQueryVariables` type with `orderBy` at the root (along with `rootAccount_in` and `controllerAccount_in`)
> ⇅ Add members sorting

- packages/ui/src/common/components/forms/InputComponent.tsx
Incorrect CSS syntax in Textarea component. Firefox powers through it and uses the default `resize` style, but in Chrome the site breaks completely as soon as the component tries to render.
> 🚓 Correct `Textarea` CSS syntax

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.stories.tsx
- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
- packages/ui/src/working-groups/components/ApplicationsList.tsx
- packages/ui/src/working-groups/components/OpeningFormPreview.tsx
- packages/ui/src/working-groups/components/OpeningsList/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/OpeningListItem.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/UpcomingOpeningListItem.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.stories.tsx
- packages/ui/src/working-groups/components/Roles/RolesList.tsx
- packages/ui/src/working-groups/model/getReward.ts
- packages/ui/src/working-groups/types/Reward.ts
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/src/working-groups/types/WorkingGroup.ts
- packages/ui/src/working-groups/types/WorkingGroupApplication.ts
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
- packages/ui/src/working-groups/types/groupExtrinsics.ts
- packages/ui/test/working-groups/modals/constants.ts
- packages/ui/test/working-groups/model/getReward.test.ts
- packages/ui/test/working-groups/model/getRewardAmount.test.ts
- packages/ui/test/working-groups/pages/MyApplications.test.tsx
Closes #678 
A couple of considerations:
* Right now group name is cast from `string` to `GroupName` type inside the `getReward` function; I think it could be beneficial to use `GroupName` in every instance of group name in objects from the Working Groups domain. I added a simple test to illustrate the case - also in the end the names will be known and finite. 
* Values in `GroupRewardPeriods` are taken from Joystream node code cited in the issue. I'm not 100% sure if they're correct (maybe I'm not imagining the scale of numbers right though)
> 🏗️ Display "Reward per x blocks"

- packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRoles.tsx
- packages/ui/src/common/hooks/useCurrentBlockNumber.ts
- packages/ui/src/working-groups/components/NextPayoutStat.tsx
- packages/ui/src/working-groups/model/getNextPayout.ts
- packages/ui/test/working-groups/model/getNextPayout.test.ts
See: #685 
Right now it says (blocks) JOY, I feel like setting up styles (currently hard-coded for JOY token values) is worthy of a separate PR
> 🎺 Display blocks until next payout

- packages/ui/src/memberships/hooks/useMemberRoles.ts
- packages/ui/src/working-groups/components/Roles/RolesList.stories.tsx
- packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
- packages/ui/src/working-groups/hooks/useOpening.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/Worker.ts
- packages/ui/src/working-groups/types/WorkingGroup.ts
- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
See #769 
Updated two kinds of queries so far, workers and working groups.
I think Openings have potential to be slimmed down as well, seeing that the multiple openings query gets an entire list of applicants. They're already a bit complicated though, being inherited from BaseOpening interface
> 🪗 Optimize queries

- packages/ui/package.json
Rationale: now that we run Prettier after ESLint, ESLint warnings and errors get completely drowned out by Prettier output in terminal. `useWorkers.ts` taking 2ms to check isn't critical information and no-one reads that stuff anyway.
> ✂️ Decrease Prettier's log level

- packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
- packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
- packages/ui/src/common/components/selects/select.tsx
- packages/ui/src/memberships/components/SelectMember/SelectMember.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
- packages/ui/src/working-groups/modals/ChangeAccountModal/ChangeAccountSelectModal.tsx
- packages/ui/test/accounts/components/SelectAccount.test.tsx
Turns out account selectors didn't display selected accounts because the selected account was given to them by the form they're in via props. It makes sense since the form state should be the "master index" of all values filled in ­— so I've made sure to avoid confusion by completely removing the selected item from select components' state - it can only be supplied by props now. The select components' main job is to pass the correct data back to form upon selection.
I have also noticed that "unsaved accounts" weren't being passed back to the form (while their internal state made them display the account, meaning that displayed values were inconsistent with the form state) so I fixed that as well. This use case is a bit odd/specific to the Account Selector, so I went ahead and added a test …
> 🔫 Select components - assorted fixes

- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/common/components/Activities/Activities.stories.tsx
- packages/ui/src/common/components/Activities/Activities.tsx
- packages/ui/src/common/components/Activities/ActivitiesBlock.tsx
- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/ModalLink.tsx
- packages/ui/src/common/components/Notifications/Notifications.tsx
- packages/ui/src/proposals/hooks/usePastProposals.ts
- packages/ui/src/working-groups/components/Activities/ApplicationWithdrawnContent.tsx
- packages/ui/src/working-groups/components/Activities/AppliedOnOpeningContent.tsx
- packages/ui/src/working-groups/components/Activities/BudgetSetContent.tsx
- packages/ui/src/working-groups/components/Activities/BudgetSpendingContent.tsx
- packages/ui/src/working-groups/components/Activities/LeaderSetContent.tsx
- packages/ui/src/working-groups/components/Activities/OpeningAddedContent.tsx
- packages/ui/src/working-groups/components/Activities/OpeningCanceledContent.tsx
- packages/ui/src/working-groups/components/Activities/StakeChangedContent.tsx
- packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
- packages/ui/src/working-groups/components/Activities/StatusTextChangedContent.tsx
- packages/ui/src/working-groups/components/Activities/WorkerExitedContent.tsx
- packages/ui/src/working-groups/components/Activities/WorkerStartedLeavingContent.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
Changed member notifications to refer to the selected member in 2nd person. It's done through a prop in `ActivitiesBlock` and introduces some unfortunate prop drilling, but this way seems to be most efficient overall.
I've also refactored `ActivityContent` to use a `Record` as a map, instead of an elaborate switch. The final version of the refactor is pretty much on par with the previous one, gaining some strengths in one way while getting weaker in another.
The Good:
* `Record` enforces mapping of all activity categories to components, making sure no category is omitted by mistake
* `ActivityContent` is much easier on the eyes
The Bad:
* Type checking in respective content components is completely gone. However, this shouldn't pose a problem as long as activity contents are only used in …
> 🧬 Adapt activity text to context

- packages/ui/dev/scripts/generators/generateEvents.ts
- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/Activities/ActivityToIconMap.tsx
- packages/ui/src/memberships/hooks/useMemberNotifications.ts
- packages/ui/src/mocks/data/raw/statusTextChangedEvents.json
- packages/ui/src/mocks/data/raw/workerExitedEvents.json
- packages/ui/src/mocks/data/raw/workerStartedLeavingEvents.json
- packages/ui/src/mocks/data/seedEvents.ts
- packages/ui/src/mocks/server.ts
- packages/ui/src/working-groups/components/Activities/OpeningAnnouncedContent.tsx
- packages/ui/src/working-groups/components/Activities/StatusTextChangedContent.tsx
- packages/ui/src/working-groups/components/Activities/WorkerExitedContent.tsx
- packages/ui/src/working-groups/hooks/useGroupActivities.ts
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
- packages/ui/src/working-groups/types/WorkingGroupActivity/casts.ts
- packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
* Added worker exited + started leaving activities. Might want to add a more descriptive text for the worker exited activity, to at least hint at what they were doing and in which group
* Added activities for `StatusTextChangedEvent`. There might be more activities tied to it that haven't been designed yet, e.g. cancelled upcoming openings. The event itself is quite confusing overall, it has fields for changed metadata and added openings but then it also has a "result" type field which potentially doubles both above mentioned fields and at the same time seems to hint at them being mutually exclusive... I think it could use a redesign.
> 🦀 Add worker leaving + status changed activities

- .github/workflows/CI.yml
One job ran for 144 min ... and I had to cancel it
> ⏲ Set CI job timeout to 30 minutes

- .github/workflows/CI.yml
- packages/ui/src/mocks/data/seedMembers.ts
- packages/ui/test/_helpers/getButton.ts
- packages/ui/test/_mocks/server/index.ts
- packages/ui/test/accounts/components/MyAccounts.test.tsx
- packages/ui/test/accounts/modal/RecoverBalanceModal.test.tsx
- packages/ui/test/accounts/modal/TransferModal.test.tsx
- packages/ui/test/app/pages/Members.test.tsx
- packages/ui/test/app/pages/MyProfile/MyAccounts.test.tsx
- packages/ui/test/membership/components/CurrentMember.test.tsx
- packages/ui/test/membership/components/MyMemberships.test.tsx
- packages/ui/test/membership/hooks/useMyMemberships.test.tsx
- packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
- packages/ui/test/membership/modals/InviteMemberModal.test.tsx
- packages/ui/test/membership/modals/TransferInviteModal.test.tsx
- packages/ui/test/membership/modals/UpdateMembershipModal.test.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
- packages/ui/test/working-groups/modals/ChangeAccountModal.test.tsx
- packages/ui/test/working-groups/modals/LeaveRoleModal.test.tsx
Comparison on my local machine:
Before:
After:
Few findings:
*   `findByRole()` is very slow, most of my changes relate to that by adding `getButton()` helper. See the "AddNewProposalModal.test.tsx" above :scream:
*   The `--runInBand` has no effect on CI
*   Not so great improvement on CI :disappointed:
*   Some server seeds can be created once per file (only reads, no writes) or reducing number of seeds (especially with Members)
> 🚀 Improve tests performance

- packages/ui/src/common/components/icons/FileIcon.tsx
- packages/ui/src/common/components/statistics/StatisticButton.tsx
- packages/ui/src/common/components/statistics/StatisticItem.tsx
- packages/ui/src/proposals/components/ProposalPreview/CreateLeadOpeningDetailsComponent.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.tsx
Added the statistic button to the create working group lead opening proposal
@ClumsyVlad I think that we miss [the title's icon](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=2059%3A20) still
> 🫐 Update styles for lead opening proposal

- packages/ui/src/app/pages/Proposals/PastProposals.tsx
- packages/ui/src/mocks/resolvers/baseResolvers.ts
- packages/ui/src/proposals/hooks/useProposals.ts
- packages/ui/test/_mocks/proposals/index.ts
- packages/ui/test/proposals/hooks/useProposals.test.tsx
Closes #586 
Filters work well with past proposals at the moment. Their behaviour for active proposals is currently undefined, but by design they aren't meant to used with Active ones. The only filter that would cause problems with active proposals would be the lifetime filter since active proposals don't have an end date.
Lifetime filter has been tested for start date only/end date only, as we don't have an OR clause resolver in our mocks. The intervals used are correct in theory however.
> 🥑 Apply filters to past proposals

- packages/ui/src/proposals/components/ProposalPreview/RuntimeUpgradeComponent.tsx
- packages/ui/src/proposals/hooks/useRuntimeBytecode.ts
See #1042 
Doesn't open a modal anymore, though it could use a fancy spinner still
> 🦔 Change runtime download to inline component

- packages/ui/src/forum/modals/PostActionModal/DeletePostModal/DeletePostModal.tsx
- packages/ui/test/_mocks/forum/posts.ts
- packages/ui/test/forum/modals/DeletePostModal.test.tsx
Also removed the requirement for active member being identical to post author, as this is checked before opening the modal and should not be reachable with normal use
> 🦘 Add a sufficient funds requirement to Delete Post modal

- packages/ui/src/common/components/Stepper/Stepper.tsx
- packages/ui/src/common/model/machines/getSteps.ts
- packages/ui/src/forum/modals/PostHistoryModal/PostHistoryModal.stories.tsx
- packages/ui/src/forum/modals/PostHistoryModal/PostHistoryModal.tsx
Closes #1192 
Passing element refs upwards like this is extremely cursed, but it works fairly well
> 🩴 Scroll to edits on stepper click in edits history

- packages/ui/src/app/pages/Forum/ForumOverview.tsx
Closes #1066 but in reverse
I think we're not doing polls for now, so that element should be replaced with something else, maybe we should get back to the design team on this
> 🙈 Hide some overview items from non-members

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/common/components/Search/HighlightedText.stories.tsx
- packages/ui/src/common/components/Search/HighlightedText.tsx
- packages/ui/src/common/components/Search/SearchResultBreadcrumbs.tsx
- packages/ui/src/common/components/Search/SearchResultItem.tsx
- packages/ui/src/common/components/Search/SearchResultsModal.stories.tsx
- packages/ui/src/common/components/Search/SearchResultsModal.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/common/hooks/useSearch.ts
- packages/ui/src/forum/components/ForumPageHeader.tsx
- packages/ui/src/forum/hooks/useForumMultiQueryCategoryBreadCrumbs.ts
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/forum/queries/forum.graphql
- packages/ui/test/common/components/HighlightedText.test.tsx
> 🐶 Implement the forum search results popup

- packages/ui/src/forum/components/threads/ThreadBrowser.tsx
Add min height for thread browser item to resolve content jumping on load state
Closes #1347
> 📭 Min height for thread browser

- packages/ui/src/common/components/Search/SearchResultsModal.tsx
- packages/ui/src/common/components/SidePane/SidePane.tsx
Since the search pane also allows to explore categories with each results breadcrumbs, you can now navigate through the all forum with the search result pane open. The overlay disappears once the route changes.
Closes #1326
> ⛵ Make the forum navigable with the search pane

- packages/ui/src/common/components/page/Sidebar/Breadcrumbs/BreadcrumbsItem.tsx
- packages/ui/src/forum/components/threads/ThreadItem.tsx
Closes #1062 
Final touch for thread overview - breadcrumbs would get massive and take up half the space in the component, so they need to be truncated if they're too verbose. The style was changed site-wide but in practice we shouldn't see it much outside forum overview, and if someone's screen is narrow enough the crumbs should sit neatly in a single line anyway.
Also removed the thread title breadcrumb from there since the thread title is at the top of the component anyway.
> 🥖 Truncate breadcrumbs in thread items

- packages/ui/src/common/components/Activities/ActivityContent.tsx
- packages/ui/src/common/components/Activities/ActivityToIconMap.tsx
- packages/ui/src/common/types/Activity.ts
- packages/ui/src/forum/components/Activities/CategoryCreatedContent.tsx
- packages/ui/src/forum/components/Activities/ThreadCreatedContent.tsx
- packages/ui/src/forum/hooks/useForumActivities.ts
- packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
- packages/ui/src/forum/queries/forumEvents.graphql
- packages/ui/src/forum/types/ForumActivity/casts.ts
- packages/ui/src/forum/types/ForumActivity/types.ts
Just two activities for forum. Without mocks, since they can now be witnessed on testnet.
There are a bunch more activities designed, but I'm kinda skeptical as to whether users would want to see them/ have some of their actions announced (like deleting a post). I think Proposals still use a mocked hook for activities, so I'll take a look at that in the meantime.
> 🕳 Add Thread/Category Created forum activities

- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/forum/components/PostList/PostListItem.tsx
- packages/ui/src/forum/components/Thread/NewThreadPost.tsx
- packages/ui/src/forum/modals/PostActionModal/DeletePostModal/DeletePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/index.ts
- packages/ui/src/forum/modals/PostActionModal/PostActionSignModal.tsx
- packages/ui/test/forum/components/PostEditor.test.tsx
- packages/ui/test/forum/modals/EditPostModal.test.tsx
See #1465
Alright, it was pretty hard to make perfect UX. 
I've come up with these solutions:
1) On success - we update text and time of post
2) On error or on canceling modal - we focus user back to inline editor. Previously it was looking really weird.
Regarding 2nd point - that was the big fight against react ref types. But it works nice as I think
> 🥴 Handle actions on success and canceled/failed post editing

- packages/ui/src/accounts/hooks/useStakingAccountStatus.ts
- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/machine.ts
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
Closes #1171
This PR adds the real-world handling of the two-step modals (mostly those that require staking). It is not ideal as it has some code duplication for the modal and for the machine as well. However, I thought that it is OK for now as we have only two modals that require staking.
It would be nice that you could verify (for instance for proposals) that this works. I was able to test that using two steps:
*   at a first run, I used an account that was not bounded and I've passed two transactions (staking + proposal creation)
*   for the second check, I've used the same account for bonding (so it was already bounded) so I had only one transaction (proposal creation)
> 🐫 Multi transaction modals updates

- packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/machine.ts
- packages/ui/src/proposals/modals/ChangeThreadMode/SignTransactionModal.tsx
- packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
Closes #1509 
Added a transaction for setting the discussion mode; the transaction modal is located in a separate dir called `ChangeThreadMode`, since I expect that a standalone functionality for changing the thread mode will be added as well.
> 🦵 Set discussion mode when creating a proposal

- .env
- packages/ui/dev/chain-spec/configs/announcing.ts
- packages/ui/dev/chain-spec/configs/index.ts
- packages/ui/dev/chain-spec/configs/revealing.ts
- packages/ui/dev/chain-spec/configs/voting.ts
- packages/ui/dev/chain-spec/docker-compose.yml
- packages/ui/dev/chain-spec/index.ts
- packages/ui/package.json
It needs some documentation.
In the meantime (with all commands ran from the repository root):
1. The chain spec (`packages/ui/dev/chain-spec/data/chain-spec.json`) is at `Announcing` by default. To switch the stage:
- `yarn workspace ui run set-chain-spec <stage>` (the stages are lowercase)
2. The node can be run either with:
- docker compose: `docker-compose up node`
- or `<path to the runtime> --tmp --alice --validator --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --chain packages/ui/dev/chain-spec/data/chain-spec.json --log runtime`
3. When the runtime is changed the default chain spec might need to be rebuilt (I used docker for this):
- `docker-compose run --rm build`
Both voting and revealing periods are extra long regardless of the chosen `olympia` runtime thanks to the …
> 🤖 Generate chain specs which force an election stage

- packages/ui/test/membership/components/CurrentMember.test.tsx
It looks that this test might randomly fail due to long execution times, see: [https://github.com/Joystream/pioneer/runs/4091235975?check_suite_focus=true.](https://github.com/Joystream/pioneer/runs/4091235975?check_suite_focus=true.)
In this PR I refactored the way how the test is built.
> 🚜 Refactor current member tests

- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/forum/hooks/useForumThreadPosts.ts
- packages/ui/test/forum/hooks/useForumThreadPosts.test.ts
Closes #1683
I've forced watch queries to have `cache-and-network` policy and common queries to have `standby` - seems working nice for our case.
fetchPolicy determines where the client may return a result from. The options are:
* cache-first (default): return result from cache. Only fetch from network if cached result is not available.
* cache-and-network: return result from cache first (if it exists), then return network result once it's available.
* cache-only: return result from cache if available, fail otherwise.
* no-cache: return result from network, fail if network call doesn't succeed, don't save to cache
* network-only: return result from network, fail if network call doesn't succeed, save to cache
* standby: only for queries that aren't actively watched, but should be available …
> 🍜 Change fetching policy

- packages/ui/src/working-groups/components/ApplicantsList.tsx
Issue: https://github.com/Joystream/pioneer/issues/1480
Show warning only in case there is an application and a member is not hired.
> 1480 - Hiring complete is wrongfully displayed

- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
- packages/ui/src/common/components/Modal/Modal.tsx
I propose a fix for the Issue https://github.com/Joystream/pioneer/issues/1566
Add `resize: vertical;` to CKEditor to allow changing CKEdit height.
Add `max-height: 800px;` and  `overflow: auto;` to the modal to be able to scroll the modal in case when CKEditor is resized and modal is bigger than the screen.
> 1566 - Allow user to change height of the editor

- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/common/components/forms/FileInput.stories.tsx
- packages/ui/src/common/components/forms/FileInput.tsx
- packages/ui/src/common/components/icons/DropFileIcon.tsx
- packages/ui/src/common/utils.ts
See #1633
Here are the wireframes: [@figma](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=1752%3A36146)
Because only one file is needed to restore the votes I didn't implement the delete file/dust bin button.
> 📠 Add a FileInput component

- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/hooks/useNetwork.ts
- packages/ui/src/common/providers/api/provider.tsx
This is a simple update to the network settings:
- added new network type `local-mocks` (will work as current `local`)
- removes MirageJS mocks from `local` (to enable `query-node` actions)
- updated settings page to handle any network type
> 🏡 Use local query-node instance

- packages/ui/src/accounts/modals/RecoverBalance/RecoverBalanceModal.tsx
- packages/ui/src/accounts/modals/RecoverBalance/RecoverBalanceSignModal.tsx
Bugfix: use controller account to sign recover staked balance transaction (it can be different than root account)
> 🔙  Fix recovering locked balance

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/proposals/components/ProposalDetails/renderers/ProposalLink.tsx
- packages/ui/src/working-groups/types/WorkingGroup.ts
- packages/ui/test/council/pages/PastCouncil.test.tsx
- packages/ui/test/working-groups/model/workingGroupName.test.ts
Closes #1864 
In addition to these small changes, I've decided to change the way working groups' display names are shown. I think the original intent was for them to be proper names, so I've changed the name strings to always have capital first letters.
> 🧂 Proposal properties style improvements

- packages/ui/src/common/utils/bn.ts
- packages/ui/src/council/hooks/useElectionVotes.ts
- packages/ui/src/council/types/PastElection.ts
- packages/ui/src/working-groups/model/getAverageStake.ts
After an election was completed successfully the PastElections page was crashing, because of a `BN::addn` being used to sum the candidates stakes which are strings.
> 🔧 Fix the PastElections page crashing

- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/app/pages/Council/PastCouncils/PastCouncil.tsx
- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
- packages/ui/src/council/components/pastCouncil/PastCouncilsList/PastCouncilListItem.tsx
- packages/ui/src/council/components/pastCouncil/PastCouncilsList/PastCouncilsList.stories.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/ElectedCouncil.ts
- packages/ui/src/council/types/PastCouncil.ts
See #1825
This PR adds handling of expected schema upgrade for councils "atBlock" dates: elected at and terminated at.
I suppose that this could work, but more work on mocks might be needed.
> 🌇 Sync schema for council block & date

- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/council/components/ViewElectionButton.tsx
Closes #1914 
According to the [Joystream handbook](https://joystream.gitbook.io/joystream-handbook/governance/council#council), Normal Period and Election Period are mutually exclusive. This would mean that the normal period remaining length shouldn't be displayed during the election period; instead, I decided to display a link to the election module instead.
> 🪃 Hide normal period remaining length when election is in progress

- packages/ui/src/council/components/election/announcing/AnnouncingStage.tsx
- packages/ui/src/council/components/election/voting/VotingStage.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/Candidate.ts
See #1953 
I think displaying only active candidacies in the revealing stage does the job with both hiding withdrawn candidacies and hiding previous candidates after a missed election. The filtering takes place in the frontend and not in a query, since the current query is simple and elegant enough (and not really in need of optimization yet).
I wasn't able to find a reason why the last point would happen - from what I could gather from the [runtime code](https://github.com/Joystream/joystream/blob/db3885858a7812377a19390968bdbf65221f0270/runtime-modules/council/src/lib.rs#L1476), there is a check for an existing candidacy. Maybe the announcing period number was wrong on-chain?
> 🐸 Announcing stage fixes

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionSignModal.tsx
- packages/ui/src/bounty/modals/WithdrawContributionModal/index.ts
- packages/ui/src/common/components/SuccessModal.tsx
- packages/ui/src/common/model/machines/defaultTransactionModalMachine.ts
- packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/DeletePostModal/DeletePostModal.tsx
- packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
- packages/ui/test/bounty/modals/WithdrawContributionModal.test.tsx
Closes #2021 
I believe for now ticket worth closing, and mb we should create follow-up for **Revisit withdraw contribution modal**:
- Allow actor as council (not done now, because I don't see the app behaviour for council member in the design)
- Display amount of contributed locks amount in SignModal(not done now, because initial bounty queries are still in review and it's lot of stuff to be done in mocks, best way is to postpone this)
I can create follow-up on my own, just tell me what column in ZenHub it should be in 🙈
> 🎁 Introduce basic bounty withdraw contribution modal

- packages/ui/src/mocks/data/seedForum.ts
- packages/ui/test/_mocks/bounty/helpers.ts
Closes  #2071
Usage:
```ts
seedMembers(mockServer.server, 2)
seedBountyThread(mockServer.server)
seedSafeBounties(mockServer.server, [
{ stage: 'Funding' },
{ stage: 'Funding' },
{ stage: 'WorkSubmission' },
{ stage: 'Terminated' },
{ stage: 'Terminated' },
])
```
This seeds 5 bounties with different stages.
There is no need for helpers for the contributions and the entries. If needed they can already be seeded like this:
```ts
seedBountyContributions(server, [{ bountyId: '2' }, { bountyId: '3' }])
seedBountyEntries(server, [{ bountyId: '3' }, { bountyId: '3' }])
```
> 🤿 Add helpers to simplify seeding bounties in tests

- packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
- packages/ui/src/common/api/schemas/schema.graphql
This helps solving #857 by allowing to replace:
```gql
memberships( where: { roles_some: { group: { id_in: [ ... ] } } } ) { ... } # Fails
```
by:
```gql
memberships( where: { roles_some: { groupId_in: [ ... ] } } ) { ... } # Works
```
As long as the changes from https://github.com/Joystream/joystream/pull/3043 aren't deployed to the testnet, this is only testable with local query nodes:
1. Run local query nodes following the query nodes [README.md](https://github.com/Joystream/joystream/blob/f278f8763bd7df57ffcbcb716347e8fc1e3fcf16/query-node/README.md)
2. On pioneer select: `Settings` > `Select network` > `Local`
But because the role query is already failing I think we could still merge this PR, without waiting for https://github.com/Joystream/joystream/pull/3043.
> ✏️ Update schema to allow filtering by `groupId_in`

- packages/markdown-editor/src/MarkdownEditor.js
- packages/ui/src/common/components/CKEditor/CKEditor.stories.tsx
- packages/ui/src/common/components/CKEditor/CKEditor.tsx
- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
Closes #2096 
Closes #2097 
**Proposed solution**
Users could filter mentions by category by using proper syntax
```
@<category>:<name>
```
For the purpose of this POC only filtering by `proposal` and `member` is supported.
- When the user types `@`, he would see the window with available categories
- When the user types a mention without a specific category eg. `@test`, he would see results from all supported resources
- When the user types mention with the category eg. `@member:test`, he would see results from the desired category
TODO: 
- Linking mentions to proper resources.
- Prepare dedicated queries for resources searching
> POC: Add mentions for one or more resources

- packages/ui/src/app/config/network.ts
Proposing to update the default local-network settings for faucet url to match the playground settings in: https://github.com/Joystream/joystream/blob/eed6f9ae78d721db625cf00da8798e035a17fce5/docker-compose.yml#L259
> Update local network settings faucet url to match playground

- packages/ui/src/common/model/JoystreamNode/metadataFromBytes.ts
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
Closes  #2095
This also solves the first part of #2284
Weirdly `ApplyForRoleModal` creates 2 `applyOnOpening` and sends the 2de after validating the staking account (this is why we missed this in #2239). It would be great to try to simplify this logic when working on the second part of #2284.
> 🧑‍🔧 Fix apply for role staking account

- packages/ui/src/common/hooks/useProcessTransaction.ts
Closes #2289
Turns out the block height is not easy to get, but the block hash is just as good to check the error on https://polkadot.js.org/apps
Also showing successful transaction details could be really useful too.
> 🕵️ Show transaction errors details in the console

- docs/README.md
- packages/ui/.env.example
- packages/ui/src/app/config/network.ts
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/common/providers/network-endpoints/provider.tsx
Made an attempt to improve on the custom endpoint feature.
Introduced a new network type called 'auto-conf' for which we store the custom endpoint settings. And this can only be set at runtime through the url query `network-config`. No network config url is hard-coded in code or taken from env variables, to allow changes to endpoints to be done dynamically otherwise they are persisted in local storage when first loading the site.
env variables `REACT_APP_OLYMPIA_TESTNET_xxx` only configure the the olympia-testnet. If not all values are provided the olympia-testnet option is not displayed in drop-down on settings page. Also made all var names consistent renamed `REACT_APP_MEMBERSHIP_FAUCET_URL` to `REACT_APP_OLYMPIA_TESTNET_MEMBERSHIP_FAUCET_URL`.
Fallback to local network if network …
> Add auto-conf NetworkType variant to store custom endpoints config

- packages/ui/src/accounts/modals/RecoverBalance/RecoverBalanceModal.tsx
This PR is implementing different logic for `Voting` lock type. It's driven by that as all locks should we recovered with controller account of the member on whose behalf staking was committed, but for voting lock there is an exception, because voting requires only account for casting a vote, so recovering of voting stake should be signer with same account which commited a vote.
> Fix for recover lock wrong signer

- packages/ui/src/app/config/network.ts
- packages/ui/src/app/index.ts
- packages/ui/src/app/pages/Settings/Settings.tsx
- packages/ui/src/app/providers/QueryNodeProvider.tsx
- packages/ui/src/common/hooks/useNetwork.ts
- packages/ui/src/common/providers/network-endpoints/context.ts
- packages/ui/src/common/providers/network-endpoints/provider.tsx
- packages/ui/src/mocks/server.ts
This goes straight to `olympia` because the `Settings` test suite is failing there, and merging it to `dev` would create conflicts.
In addition to fixing the failing tests this PR also prevents getting a blank page when loading a Pioneer instance where `olympia-testnet` is not defined. It also simplifies the logic a bit.
> 🥅 Hotfix no `olympia-testnet` support

- packages/ui/src/working-groups/components/MyStakeStat.tsx
When a user has more than one role, stakes are reduces to a sum, but the stake property is of string type, so it leads to wrong result: 
Fixes #2427
> MyStakeStat: String Concatenation in getTotalStake

- packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
- packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
- packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
- packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.tsx
- packages/ui/src/common/components/forms/InputComponent.tsx
- packages/ui/test/bounty/modals/SubmitWorkModal.test.tsx
Additionally in this PR following issues should be resovled:
- Markdown editor shouldn't expand modal container on text overflow
- Correct entry will be chosen when user with try to withdraw second and subsequent work entries
- Correct entry will be chosen when user this to submit work on second and subsequent work entry
- Now we display Withdraw entry CTA for members that have entry, previously we did it for workers when submittions
> 💪 Fix on submit work validation and more

- packages/ui/src/memberships/model/validation.ts
> 🎖️ Fix on flashing validation when selecting staking account

- packages/ui/src/memberships/model/validation.ts
:warning: This should be merged not squash merged
This is a cherry pick from `dev` into `staging` back into `dev` because I should have merged #2852 to `staging` directly so now I'm merging it back into `dev` again :tired_face: 
(cherry picked from commit 3e9f6871205fe090231a682142cf12e16c4f19df)
> 🎖️ Fix on flashing validation when selecting staking account (#2852)

- packages/ui/dev/node-mocks/commands/opening/create.ts
- packages/ui/src/common/components/forms/Checkbox.tsx
- packages/ui/src/forum/components/PostList/PostEditor.tsx
- packages/ui/src/proposals/components/ProposalDiscussions.tsx
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/ProposalWithDetails.ts
Closes #2476 
Issue scope:
Beyoynd issue:
so far when user created editable post the checkbox stayed marked (because it didn't update properly) after transition, so if user creates another post they may think it would be editable too, but it won't. This is a change inside `Checkbox` component so it may fix other similar issues (if there are)
> 📝 Fix editable posts in proposal discussion

- packages/ui/src/council/components/Activities/NewCouncilElectedContent.tsx
Technically `have been` is only correct [while](http://www.differencebetween.net/language/difference-between-were-and-have-been/) they are elected - it is likely the notification will disappear until next election finished,
If you like we could drop it altogether (`5 councilors elected to the council` or `New council elected`).
@blrhc how would a mother tongue say it?
> Council announcement wording

- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/RewardAccountStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/SummaryAndBannerStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/components/TitleAndBulletPointsStep.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/helpers.ts
- packages/ui/src/council/modals/AnnounceCandidacy/machine.ts
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
> ✌️ AccounceCandidacyModal validation refactor

- packages/ui/src/common/components/Modal/Modal.tsx
https://github.com/Joystream/pioneer/issues/3025
Lower padding-top to 60px for modal size `m`
> #3025 Update medium modal padding to better fit on smaller screens.

- packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
Fixes #3281
@WRadoslaw I don't know what it was for in #3233:
```css
.ckeditor-anchor {
display: none;
}
```
so I removed it for now
> ✍️ Fix the post editing feature

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/test/council/pages/Election.test.tsx
#2795 
- My stake on candidate stake to be renamed to "Staked"
> Fix Candidates Card "Staked" copy

- packages/ui/src/accounts/components/SelectAccount/OptionAccount.tsx
- packages/ui/src/accounts/components/SelectAccount/OptionListAccount.tsx
- packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
- packages/ui/src/accounts/hooks/useBalance.ts
- packages/ui/src/accounts/hooks/useStakingAccountsLocks.ts
- packages/ui/src/accounts/model/lockTypes.ts
- packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
- packages/ui/src/common/utils/validation.ts
- packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
- packages/ui/src/council/modals/AnnounceCandidacy/helpers.ts
- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilFormModal.tsx
- packages/ui/src/memberships/model/validation.ts
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/helpers.ts
- packages/ui/test/_helpers/selectFromDropdown.ts
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
#3319
~It looks like non-rivalrous locked funds are not included in the transferable balance (`DeriveBalancesAll[DeriveBalancesAll]` in polkadotjs):~
The same fund can be staked under multiple locks at the same time:
~Although voting is the only non-rivalrous lock where the stake needs to be set manually, I also fixed the validation on announce  candidacy, and apply for role.~
➕ improved `useBalance` a bit because it was making the API unavailable for some length of time. That said I thought that we had taken care of that already... did we revert this change before for some reason ?
> ⚖️ Fix available staking balances

- packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.stories.tsx
- packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.tsx
Fixed the issue : [USERSNAP] Approval / Slashing votes bars show all votes #2715
https://github.com/Joystream/pioneer/issues/2715
changed the approval / slash quorum bar. 
The following is the formula for those bars.
- approval quorum bar :  
blue bar indicates approve / councilSize & quorum ratio
- slash quorum bar
blue bar indicates slash / councilSize & quorum ratio
- approval threshold bar :
blue bar indicates approve / total (councilsize - remain) & thresold ratio
- slash threshold bar :
blue bar indicates slash / total (councilSize - remain) & thresold ratio
I checked the notes about reject bar, so should i add new one reject bar or twos like above?
> changed quorum bar with council's size

- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
Changed the "Blog Posts" text to "Forum posts" in the MemberDetails.tsx file from issue [#3471](https://github.com/Joystream/pioneer/issues/3471)
> Updated text "Blog Posts" to "Forum Posts"

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
Fixes https://github.com/Joystream/pioneer/issues/2929
> fix: avg stake tooltip typos and link

- packages/ui/src/app/pages/Election/Election.tsx
- packages/ui/src/app/pages/Profile/MyAccounts.tsx
- packages/ui/src/app/pages/WorkingGroups/UpcomingOpening.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/council/components/pastCouncil/PastCouncilStats.tsx
- packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
> Update handbook links and tooltips (#2847)

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSignModal.tsx
Fixes #3479
Note: Is this the right spot? Took the liberty to also address `Creation fee`, feel free to expand.
> Invitation lock tooltip (#3479)

- packages/ui/src/common/hooks/useLocalStorage.ts
- packages/ui/src/council/hooks/useCommitment.ts
- packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
- #3711 
I'm guessing that in the issue multiple tabs were opened so the local storage item kept on getting overridden (that's the source of most local storage issue). The empty `accountId` entry was due the commitment first getting calculated before the staking account was set.
> 🗃️ Fix votes storage

- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
> Add handle / name tooltips on `BuyMembershipFormModal` (#3024)

- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipModal.tsx
> Update Sidebar membership display after edit tx (#3133)

- packages/ui/src/proposals/components/ProposalDiscussions.tsx
> 👾 Sort proposal discussion by block (#3236)

- packages/ui/src/council/components/election/CandidateVote/CandidateVote.stories.tsx
- packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
- packages/ui/src/council/components/election/CandidateVote/RevealingStageVotes.tsx
- packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
- packages/ui/src/council/components/election/revealing/RevealingStage.tsx
- packages/ui/src/council/hooks/useMyCastVotes.ts
- packages/ui/test/council/components/ElectionVotes.test.tsx
#2985
Renames `ownStake` to `myStake` in line with  `CandidateVote` view to prevent confusion with candidate's "own" stake.
> Show sum of my vote stakes on `CandidateVote` (#2985)

- packages/ui/src/accounts/modals/ClaimVestingModal/ClaimVestingModal.tsx
> Hide error while loading on `ClaimVestingModal` (#3838)

- packages/ui/src/working-groups/types/WorkingGroupOpening.ts
The issue is manifested when WG opening is created with Joystream CLI.
The variable "fields.metadata?.hiringLimit" is NULL when CLI is used.
> hiringLimit 0 to 1 (#2451)

- packages/ui/src/working-groups/components/Activities/ActivitiesModals/StakeChanged/StakeChangedModal.tsx
- packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
- packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
Fixes https://github.com/Joystream/pioneer/issues/3458#issuecomment-1309116376
- Add 'Read more' on `StakeSlashedContent` to open `StakeChangedModal`
- Rename `Slashed By` with' to `Amount`
- Rename `Status` with `Action`
- Hide Amount if empty
- Hide Rationale if empty
Note: To display more slashing details on the modal the `activity` object / QN fragment is missing: slashedAmount suggestedAmount rationale
```
query { 
stakeSlashedEvents { id inBlock createdAt groupId slashedAmount requestedAmount rationale worker { membershipId } }
stakeDecreasedEvents { id inBlock createdAt groupId amount worker { membershipId } }
stakeIncreasedEvents { id inBlock createdAt groupId amount worker { membershipId } }
stakeReleasedEvents { id inBlock createdAt stakingAccount }
}
``` …
> Stake changed Activities (#3458)

- packages/ui/src/proposals/components/ProposalDetails/ProposalDetails.tsx
- packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.tsx
- packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/proposals/queries/proposals.graphql
- packages/ui/src/proposals/types/ProposalDetails.ts
> Show new invitation quota on `ProposalDetails` (#3902)

- packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
- packages/ui/src/working-groups/hooks/useWorkerEarnings.ts
> Hide `Earned in 24h` until calculation fix (#3181)

- package.json
- packages/markdown-editor/package.json
Just like on [Atlas](https://github.com/Joystream/atlas/blob/master/package.json).
It simplifies the version management. Otherwise it's confusing when `/package.json` and /packages/ui/package.json` versions don't match due to mistakes.
> 🙈 Do not version the root `package.json`

- packages/ui/src/app/pages/Settings/Settings.tsx
> Hide Languages tab (#3955)

- packages/ui/src/forum/components/threads/ThreadListItem.tsx
issue #3912 
I have found the line of code related to this issue
(packages\ui\src\forum\components\threads\ThreadListItem.tsx)
`<TextMedium bold>{thread.visiblePostsCount - 1}</TextMedium>`
The problem is that the variable `thread.visiblePostsCount` is zero.
> the replies counter is not working properly (#3912)

- packages/ui/src/proposals/types/ProposalDetails.ts
- #3994
https://dao-git-fix-proposal-view-crash-joystream.vercel.app/#/proposals/preview/12?network-config=https://atlas-next.joystream.org/network/config.json
> 🩹 Fix proposal view crashing due to high amounts of JOY

- docs/mocks.md
- packages/ui/dev/helpers/decode.ts
- packages/ui/dev/helpers/index.ts
- packages/ui/src/common/model/JoystreamNode/index.ts
- packages/ui/src/common/model/JoystreamNode/metadataFromBytes.ts
- #3525
This command requires two arguments:
- `-t`, `--type`: The expected type of the value to decode.
- `-v`, `--value`: The hash or the string representation of the `Uint8Array` to decode.
With `-t text` this command will simply decode encoded plaint text values. E.g:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t text -v 0x4c6f72656d20697370756d
Lorem ispum
```
Otherwhise the type options should refer to a metadata class. It can be the name of the class:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t CouncilCandidacyNoteMetadata -v 0x0a0a616...
CouncilCandidacyNoteMetadata {
...
}
```
Or it can be an alias:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t candidacy -v 0x0a0a616...
CouncilCandidacyNoteMetadata {
...
}
```
The …
> 🔬 Add a decode helper command

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/memberships/components/InviteMemberButton.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberModal.tsx
- packages/ui/src/memberships/modals/InviteMemberModal/types.ts
- packages/ui/test/membership/modals/InviteMemberModal.test.tsx
Fixes https://github.com/Joystream/pioneer/issues/4053
Make InviteMemberModal a global modal.
> Invite A Member Modal bug #4053

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
#4057
To retain candidate's control over design this only reveals the handle on hover.
> Show member handle as 'title' hovering `CandidateCard` (#4057)

- packages/ui/src/common/components/page/Sidebar/NavigationLink.tsx
> Fix icon on the Polkadot Block Explorer Menu item #3974

- packages/ui/src/app/pages/Forum/ForumThread.tsx
- packages/ui/src/common/hooks/useRefetchQueries.ts
- packages/ui/src/forum/components/PostList/PostList.tsx
- packages/ui/src/forum/hooks/useForumThread.ts
> fixes #4108 Forum returns 404 for correct links

- packages/ui/.env.example
- packages/ui/src/app/Providers.tsx
- packages/ui/src/app/config/network.ts
- packages/ui/src/app/providers/backend/context.ts
- packages/ui/src/app/providers/backend/provider.tsx
- packages/ui/src/common/hooks/useBackend.ts
- packages/ui/src/common/hooks/useIsMemberRegistered.ts
- packages/ui/src/common/providers/network-endpoints/provider.tsx
Add a `useBackend` hook to connect to the backend. See the usage example: [`useIsMemberRegistered`](https://github.com/Joystream/pioneer/blob/feature/backend-connection/packages/ui/src/common/hooks/useIsMemberRegistered.ts)
This might not be the best/final solution but it should be good enough to get started implementing #4230.
> **Warning**
> The connection endpoint should be set in the `package/ui/.env` file. When using the development backend deployment from #4364:
> ```
> docker run --rm -it -e POSTGRES_PASSWORD="my-password123" --name api -p 3000:3000 thesan/pioneer-backend
> ```
> The mainnet backend endpoint should: `REACT_APP_MAINNET_BACKEND=http://localhost:3000`
> 🔌 Add an Apollo client instance for the backend

- packages/ui/src/common/hooks/useBackend.ts
This PR expands the scope of the `useBackend` hook.
```js
const query = gql`
query QueryX($input: Input) {
queryX(input: $input)
}
`
export const useQueryX = (input) => {
const { data, error } = useBackend({ query, variables: { input }, skip: condition }) // `skip` is optional
return { data, error }
}
```
```js
const query = gql`
query QueryX($input: Input) {
queryX(input: $input)
}
`
export const useLazyQueryX = (input) => {
const { data, error, send } = useBackend({ query })
useEffect(() => {
if (condition) {
try {
send({ input })
} catch (error) {
// do something...
}
}
}, [deps])
return { data, error }
}
```
```js
const mutation = gql`
mutation MutationX($input: Input) {
mutationX(input: $input)
}
`
export const useLazyQueryX = (input) => {
const { data, error, send } = useBackend({ …
```
> 👾 Enable mutations and lazy queries on `useBackend`

- .eslintrc.json
- packages/ui/jest.config.js
- packages/ui/src/bounty/components/BountyFooter.tsx
- packages/ui/src/common/components/BlockTime/BlockTime.tsx
- packages/ui/src/common/model/formatters.ts
- packages/ui/src/forum/components/threads/ThreadItemBreadcrumbs.tsx
- packages/ui/src/forum/hooks/useForumMultiQueryCategoryBreadCrumbs.ts
- packages/ui/test/_helpers/mockUniqueQuery.ts
- packages/ui/test/common/model/formatters.test.ts
- packages/ui/test/council/modals/RestoreVotesModal.test.tsx
- packages/ui/test/forum/components/ThreadItemBreadcrumbs.test.tsx
- packages/ui/tsconfig.json
Changes initially made while debugging on #3872
> 🩹 Address some slow or inconsistent tests

- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplicationStep.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
- packages/ui/src/working-groups/modals/ApplyForRoleModal/helpers.ts
> 🧮 Sort application answers before submitting them

- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/ApplicantsList.tsx
#4035
left: before, right: after [2d4dc50](https://github.com/Joystream/pioneer/pull/4426/commits/2d4dc501a6f4702ca65ebff539c305adbe676375)
> query { workingGroupOpenings (where:{ id_eq: "storageWorkingGroup-3" }) { id applications { status { __typename } applicant{handle} } } }
```
{
"data": {
"workingGroupOpenings": [
{
"id": "storageWorkingGroup-3",
"applications": [
{
"status": {
"__typename": "ApplicationStatusAccepted"
},
"applicant": {
"handle": "Craci_BwareLabs"
}
},
{
"status": {
"__typename": "ApplicationStatusAccepted"
},
"applicant": {
"handle": "maxlevush"
}
},
{
"status": {
"__typename": "ApplicationStatusWithdrawn"
},
"applicant": {
"handle": "0x2bc"
}
},
{
"status": {
"__typename": "ApplicationStatusAccepted"
},
"applicant": {
"handle": "goksel"
}
},
{
"status": { …
```
> Show all applicants

- .github/workflows/CI.yml
- packages/ui/package.json
- packages/ui/test-runner-jest.config.js
- yarn.lock
- #4436
Once this is merged I will change the merge requirement to `test (18.x, ubuntu-latest)` and ` storybook-test (18.x, ubuntu-latest)` so existing PRs should should pull `dev` or rebase on it
> 🧪 Add Storybook tests to the CI

- .github/workflows/CI.yml
This PR fixes the new CI for PRs made from forks, which basically will be all PRs made to Pioneer very soon.
E.g this is why the CI failed on #4453.
The previous version required secrets to use the Vercel CLI, but secrets are not available on workflows triggered from a fork. So now the CI generates the Storybook deployment URL following [the Vercel doc](https://vercel.com/docs/concepts/deployments/generated-urls#url-with-git-branch) and relies on one of the few public endpoints from the Vercel REST API to wait for the deployment to complete.
I couldn't find a way to rely on the `deployment_status` trigger [like in the Storybbok doc example](https://storybook.js.org/docs/react/writing-tests/test-runner#run-against-deployed-storybooks-via-github-actions-deployment) because of the 2 other …
> 🔧 Fix the storybook CI

- packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
- packages/ui/src/council/components/election/CandidateCard/CandidateCardList.tsx
- packages/ui/src/council/components/election/voting/VotingStage.tsx
According to [#4312](https://github.com/Joystream/pioneer/issues/4312)
> Total Votes per candidate #4312

- packages/ui/src/app/pages/Forum/ForumCategory.tsx
- packages/ui/src/forum/hooks/useForumCategoryThreads.ts
- packages/ui/test/forum/hooks/useForumCategoryThreads.test.ts
Fixed #4485 and  checked #4484
> Fix: issue 4485, check 4484

- .github/workflows/CI.yml
Address CI failing in:
- #4511
- #4518
> 🔧 Fix wrong Vercel URL due to double "-" in the CI

- packages/server/src/common/email-templates/pioneer-email.tsx
Small style adjustments for the template based on discussion in Discord: https://discord.com/channels/811216481340751934/1035125691034910800/1146821307875475679
> [backend] adjust email template styling

- packages/server/README.md
- packages/server/src/auth/api/auth.ts
- packages/server/src/auth/api/member.ts
- packages/server/src/auth/model/emailVerification.ts
- packages/server/src/auth/model/token.ts
- packages/server/src/common/api/context.ts
- packages/server/src/common/api/email.ts
- packages/server/src/notifier/api/entitySubscription.ts
- packages/server/src/notifier/api/generalSubscription.ts
- packages/server/src/notifier/api/notification.ts
- packages/server/test/api/auth.test.ts
- packages/server/test/api/notifier.test.ts
- packages/server/test/api/utils.ts
Based on #4522, will rebase after it's merged
Summary of changes:
- Added `initEmailChange` mutation
- Added authenticated `member` to Context so each mutation doesn't have to extract it manually
- Added explicit errors when user is not authenticated or token/signature is invalid. This should give clients more info to work with instead of just returning `null`
- Added auth tests that check email verification
- Added auth tests that check email change
- Minor misc auth and tests improvements
Resolves #4278
> [backend] improve auth, add change email mutation

- packages/server/prisma/migrations/20231004111039_init/migration.sql
- packages/server/prisma/schema.prisma
- packages/server/src/auth/api/auth.ts
- packages/server/src/auth/api/member.ts
- packages/server/src/notifier/api/notification.ts
- packages/server/src/notifier/createNotifications.ts
- packages/server/src/notifier/model/notifications.ts
- packages/server/src/notifier/processNotifications.ts
- packages/server/src/notifier/scripts/mockEmail.ts
- packages/server/test/_mocks/notifier/createMember.ts
- packages/server/test/api/auth.test.ts
- packages/server/test/api/notifier.test.ts
- packages/server/test/notifier.test.ts
1. Adds `receiveEmails` field to member that indicates whether notifications should be sent as emails
2. Adds `unverifiedEmail` field to member that holds an email that wasn't yet verified
3. Renames `status` field on notification to `emailStatus`
> [backend] update schema

- packages/ui/src/forum/hooks/useCategoryLatestPost.ts
- packages/ui/src/forum/hooks/useForumCategoryThreadCount.ts
- packages/ui/src/forum/hooks/useForumPopularThreads.ts
- packages/ui/src/forum/hooks/useThreadLatestPost.ts
- #4484
integrated persist cache with local storage.
need to discuss more with @thesan about the point when can fetch 500 posts from server.
> Reduce `ForumPost` requests on category pages

- packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
- packages/ui/src/council/hooks/usePastCouncil.ts
- packages/ui/src/council/hooks/usePastCouncilStats.ts
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/council/queries/council.graphql
- packages/ui/src/council/types/PastCouncil.ts
- packages/ui/test/council/pages/PastCouncil.test.tsx
Fix the #4121 (wrong values in Councils and past councils)
> Fix past councils spending amounts

- packages/ui/src/common/components/ListItemLoader.tsx
- packages/ui/src/validators/components/ValidatorItemLoading.tsx
- packages/ui/src/validators/components/ValidatorsList.tsx
> replace spinner with skeleton

- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
- packages/ui/src/mocks/data/proposals.ts
- packages/ui/src/mocks/helpers/transactions.ts
I realized this could be useful while debugging #4428
> 🔍 Check transaction signer addresses in interactions tests

- packages/ui/src/app/pages/WorkingGroups/UpcomingOpening.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
- packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
- packages/ui/src/working-groups/model/asWeeklyRewards.ts
> change openings reward display

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
- packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
- packages/ui/src/proposals/components/CancelProposalButton.tsx
- packages/ui/src/proposals/modals/CancelProposal/CancelProposalModal.tsx
- packages/ui/src/proposals/modals/CancelProposal/index.ts
- packages/ui/src/proposals/modals/CancelProposal/types.ts
> cancel proposal feature

- packages/ui/src/common/components/forms/FilterBox/FilterSearchBox.tsx
- packages/ui/src/common/utils/object.ts
- packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
- packages/ui/src/memberships/constants/externalResourceLink.ts
- packages/ui/src/memberships/constants/index.ts
- packages/ui/src/validators/components/ValidatorInfo.tsx
- packages/ui/src/validators/components/ValidatorsFilter.tsx
- packages/ui/src/validators/components/ValidatorsList.tsx
- packages/ui/src/validators/components/statistics/Era.tsx
- packages/ui/src/validators/components/statistics/Rewards.tsx
- packages/ui/src/validators/components/statistics/Staking.tsx
- packages/ui/src/validators/components/statistics/ValidatorsState.tsx
- packages/ui/src/validators/hooks/useValidatorsList.tsx
- packages/ui/src/validators/modals/NominatingRedirectModal/NominatingRedirectModal.tsx
- packages/ui/src/validators/modals/validatorCard/Nominators.tsx
- packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
- packages/ui/src/validators/providers/utils.ts
[Validator dashboard QA #4743](https://github.com/Joystream/pioneer/issues/4743)
> Address Validator dashboard QA issues

- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.stories.tsx
- packages/ui/src/bounty/queries/__generated__/bounty.generated.tsx
- packages/ui/src/council/queries/__generated__/council.generated.tsx
- packages/ui/src/forum/queries/__generated__/forum.generated.tsx
- packages/ui/src/memberships/components/MemberRoles.stories.tsx
- packages/ui/src/memberships/components/MemberRoles.tsx
- packages/ui/src/memberships/hooks/useAllMemberRoles.ts
- packages/ui/src/memberships/queries/__generated__/members.generated.tsx
- packages/ui/src/memberships/queries/members.graphql
- packages/ui/src/memberships/types/Member.ts
- packages/ui/src/memberships/types/casting.ts
- packages/ui/src/overview/queries/__generated__/overview.generated.tsx
- packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/test/membership/helpers.test.ts
- [Member roles do not update when member leaves the role #4355](https://github.com/Joystream/pioneer/issues/4355)
- [[USERSNAP] worker tags display already abandoned roles #4620](https://github.com/Joystream/pioneer/issues/4620)
> Show only current roles for the member

- packages/ui/src/app/App.stories.tsx
- packages/ui/src/app/pages/Profile/MyMemberships.stories.tsx
- packages/ui/src/common/components/Modal/Modals.tsx
- packages/ui/src/common/components/Warning.tsx
- packages/ui/src/common/components/forms/ToggleCheckbox.tsx
- packages/ui/src/common/model/Polyfill.ts
- packages/ui/src/memberships/components/SelectValidatorAccounts.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSignModal.tsx
- packages/ui/src/memberships/modals/BuyMembershipModal/machine.ts
- packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
- packages/ui/src/memberships/modals/UpdateMembershipModal/types.ts
- packages/ui/src/memberships/modals/UpdateMembershipModal/utils.ts
- packages/ui/src/mocks/data/validators.ts
> Address create/update validator membership QA issues

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroupHistory.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroupOpenings.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/components/WorkerListSidebar.tsx
- packages/ui/src/app/pages/WorkingGroups/WorkingGroup/components/WorkingGroupPageHeader.tsx
- packages/ui/src/common/components/buttons/LinkButtons.tsx
- packages/ui/src/working-groups/components/CreateOpeningButton.tsx
- packages/ui/src/working-groups/hooks/useRoleAccount.ts
- packages/ui/src/working-groups/modals/CreateOpening/CreateOpening.tsx
- packages/ui/src/working-groups/modals/CreateOpening/components/Success.tsx
- packages/ui/src/working-groups/modals/CreateOpening/machine.ts
- packages/ui/src/working-groups/modals/CreateOpening/types.tsx
- packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
- packages/ui/src/working-groups/queries/workingGroups.graphql
> [!NOTE]
> Merge after #4771 to take care of the conflicts
> 🩹 Sign `addOpening` tx with role account

- packages/ui/src/common/components/forms/FilterBox/FilterBox.tsx
- packages/ui/src/common/components/forms/FilterBox/FilterSearchBox.tsx
- packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
- packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
- Fix spacec in proposals search box [#4219](https://github.com/Joystream/pioneer/issues/4219)
- Reset the search filter after type enter when the string is empty [#4470](https://github.com/Joystream/pioneer/issues/4470) [#4524](https://github.com/Joystream/pioneer/issues/4524) [#4696](https://github.com/Joystream/pioneer/issues/4696)
-  Search members bi ID with <3 digits [#4764](https://github.com/Joystream/pioneer/issues/4764)
> Search box fixes

- packages/ui/src/accounts/providers/accounts/useWallets.ts
That's a small detail since only the constructor would be called twice the first instance is garbage collected.
> 🪛 Do not create to WalletConnect instances

- CHANGELOG.md
- packages/ui/package.json
- packages/ui/src/app/components/SideBar.tsx
- packages/ui/src/app/pages/Council/Council.tsx
- packages/ui/src/app/pages/Election/Election.stories.tsx
- packages/ui/src/app/pages/Election/Election.tsx
- packages/ui/src/app/pages/Election/components/ElectionTabs.tsx
- packages/ui/src/council/hooks/useElectionStage.ts
- packages/ui/test/council/components/ElectionTabs.test.tsx
- packages/ui/test/council/pages/Election.test.tsx
- Show election tab during idle stage.
- Rename "Normal period" to "Idle stage".
> 🔥 Hotfix: Show election tab during idle stage

- packages/ui/src/app/pages/Profile/components/BannerSection.tsx
> 💱 Update exchanges info

- packages/ui/src/proposals/components/ProposalDetails/renderers/Numeric.tsx
Both reward curve (payout damping factor) and crt constraints proposals need this.
> 📊 Add a unit prop to the `Numeric` proposal details renderer

- packages/ui/src/common/components/forms/InputNumber.tsx
- packages/ui/src/common/utils/bn.ts
- packages/ui/src/common/utils/validation.tsx
- packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteFormModal.tsx
- packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
- packages/ui/src/working-groups/modals/CreateOpening/types.tsx
Prevent the InputNumber behavior of sometime adding a 0 when a field is emptied.
Based on #4818
> 📟 Fix the InputNumber behavior

- packages/server/src/notifier/model/email/election.ts
At first I thought of adding a "new council elected" notification, but there's no CTA so I think it would be best to skip this one.
> 🔧 Change the election announcing period notification copy

- packages/ui/src/app/GlobalModals.tsx
- packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
- packages/ui/test/forum/modals/CreateThreadModal.test.tsx
- packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
> Open `OnBoardingModal` for modals requiring a membership
